capnproto/capnproto

- c++/src/kj/io.h
Without this change, the following code compiles:
kj::AutoCloseFd fd;
if (!fd) return;
In my opinion, this is a bit dangerous, although I could easily agree that it's too much of a corner case to waste header space on.
> Prevent accidental bool conversion of AutoCloseFd.

- c++/src/capnp/compiler/capnp.c++
Before this patch, `capnp id` reports its version as "0.2":
```
$ capnp id --version
Cap'n Proto multi-tool 0.2
```
> fix 'capnp id' version string

- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
This is analogous to shutdownWrite, but for the read end of the stream
Should the default implementation raise a KJ_UNIMPLEMENTED instead of doing nothing? Making it pure virtual breaks anyone who has already inherited from AsynIoStream (ie. node-capnp).
> Add abortRead to AyncIoStream

- c++/src/kj/arena.c++
- c++/src/kj/string.c++
one function in arena.c++ and several snprintf_result local vars
in string.c++ get optimized away because they're only used in
KJ_DASSERT() invocations.
tthis patch thus identifies those unused declarations with KJ_UNUSED
> zero warnings: use KJ_UNUSED for unused constexpr & local vars

- c++/src/capnp/compiler/capnp.c++
In the typical build process for a Rust project that uses Cap'n Proto code generation, we have access to capnpc-rust as a library, but not as an executable. (See [this thread](https://github.com/rust-lang/cargo/issues/872) for some discussion.)  The `compile()` function, defined [here](https://github.com/dwrensha/capnpc-rust/blob/master/src/lib.rs), is designed to handle this case. It spawns a child that runs `capnp compile -o/bin/cat`, and forwards the child's stdout to the usual codegen procedure. Things get more complicated when `/bin/cat` is not present, like on Windows, or even when it is not in its usual location (https://github.com/dwrensha/capnpc-rust/issues/9). Adding an option for `capnp compile` to directly write to stdout should make things simpler.
I had thought that "-o -" …
> Hardcode /bin/cat output option for `capnp compile`.

- c++/src/capnp/any-test.c++
- c++/src/capnp/any.c++
- c++/src/capnp/any.h
- c++/src/capnp/common.h
- c++/src/capnp/layout.c++
- c++/src/capnp/layout.h
This is a "simplest thing that could possibly work" implementation.  I'm fully expecting to reorganize the code, change the types around, etc - after hearing feedback.  I'll also clean up the git history at that point, which has rather unhelpful commit messages right now.
> Add equal / operator == method

- c++/src/kj/io.h
The comment on `InputStream::read()` describes a contract that would cause problems if actually followed. In particular, a `BufferedInputStreamWrapper` can issue a `read()` request to its inner stream with `maxBytes` reaching past the end of a message. This occurs [here](https://github.com/sandstorm-io/capnproto/blob/b059922062be4d1a500b12748760507c0b60e0d6/c%2B%2B/src/kj/io.c%2B%2B#L106), where the stream refills its buffer. It would be incorrect for the inner stream to throw a exception just because `maxBytes` could not be reached in this case.
> Fix incorrect, confusing comment.

- c++/src/capnp/layout.h
Original credit to John David Anlin on [Debian bug 781787](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781787) who noticed the hppa architecture was affected in the same way as mips wrt NaN quirks. In his own words:
> The hppa and mips architecture have the same nan format (i.e., quiet and signalling nans are
> different from x86, etc).  With the attached change, capnproto builds successfully on hppa.  See:
> http://buildd.debian-ports.org/status/fetch.php?pkg=capnproto&arch=hppa&ver=0.4.1-3&stamp=1428027386
> Canonicalize NaN on the hppa architecture

- c++/src/kj/exception.c++
This avoids an unused function warning for crashHandler.
> Fix -Werror build without KJ_HAS_BACKTRACE

- highlighting/qtcreator/capnp.xml
Apparently Kate requires the `<itemDatas>` to be inside the `<highlighting>`
tag whereas QtCreator also accepts it a level higher.
Tested using this DTD:
https://github.com/jgm/highlighting-kate/blob/master/xml/language.dtd
> Fix Syntax highlighting for Kate/KDevelop

- c++/src/capnp/CMakeLists.txt
If building the lite target only (i.e. having run CMake with `-DCAPNP_LITE=1 -DEXTERNAL_CAPNP=1`) then the c++.capnp and schema.capnp files were missing from the install folder, meaning that for example you couldn't set a namespace.
This changes the schema files to be installed along with their respective headers.
> Fixed installation of schema files via CMake.

- c++/src/capnp/rpc-prelude.h
It turns out that somehow these templates were missing InternalOwner and
ExternalOwner definitions, which was causing problems if a RealmGateway
was defined with them.
> Fix problem with some RealmGateway template helpers

- c++/Makefile.am
- c++/src/capnp/CMakeLists.txt
- c++/src/capnp/compiler/lexer-test.c++
- c++/src/capnp/compiler/lexer.c++
Add tests to verify this behavior.
Also, include `schema-parser-test.c++` in the CMake and autotools test suites.  Somehow it got left out.
> Allow trailing commas in parenthesized and bracketed lists.

- c++/src/kj/async-io.c++
> Workaround nonexistent EPROTO on OpenBSD

- doc/cxxrpc.md
9a32fa73 changed the way that getting an initial / public capability works, but the online docs were not updated to match.
Probably rpc.md (the language-agnostic docs) could also use a sentence or two talking about how you get an initial capability, how you should authenticate users, etc.
> Update RPC docs for the change to a single bootstrap interface

- c++/src/capnp/message.h
Builds on 32-bit systems (x86 and armv7) fail because `arenaSpace` is 4 bytes too small. 
The size of `arenaSpace` was last increased in 62c0270, but it looks like the change to `BuilderArena::localCapTable` in 5413038 introduced a new vtable pointer.
> Increase arenaSpace to fix 32-bit builds.

- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc-twoparty.h
This patch makes TwoPartyServer more useful. TwoPartyServer could previously only be used with AsyncIoStreams accepted by a ConnectionReceiver listener. Two-way pipes (socketpairs) for example can't be accepted in this way.
It (appears to) work(s) correctly in my application which is providing one end of a socketpair.
> Added method accept() to TwoPartyServer for servicing arbitrary AsyncIoStreams.

- c++/Makefile.am
- c++/src/capnp/CMakeLists.txt
- c++/src/capnp/compiler/node-translator.h
- c++/src/capnp/serialize-text-test.c++
- c++/src/capnp/serialize-text.c++
- c++/src/capnp/serialize-text.h
I've been looking at using the schema text format as a convenient way of specifying unit test cases that contain Cap'n Proto data, and as a runtime format for user configuration (already backed by a Cap'n Proto schema). But there's no API for reading these messages at runtime (aside from rolling them into a constant in a schema and using `SchemaParser`).
Reading the mailing lists, I see there's resistance to exposing an API for reading text messages because it has some undesirable effects if it's abused as a long-term storage or interchange format. This is understandable, but I think there are valid use cases for using the text format at runtime, and that the caveats are no worse than if JSON or the `SchemaParser` APIs are used instead. In particular, my use cases are similar to that …
> Add TextCodec to expose an API for the schema's text format.

- c++/src/kj/async-unix.c++
toRegularSiginfo attempts to convert signalfd_siginfo.ssi_ptr (a 64-bit
integer across all architectures) to a pointer. On 32-bit big endian
architectures, sival_int/sival_ptr will be stored in the high 32-bits
of the ssi_ptr value.
Prior to this change, the value was "lost" as we cast away the high
bits of ssi_ptr in the conversion to a 32-bit pointer.
This fixes AsyncUnixTest::SignalWith{,Pointer}Value on affected archs.
The comment in AsyncUnixTest::SignalWithValue mentions sigqueue() is broken on droid bionic -- not entirely clear to me if this is related & I don't have the hardware to check.
> Fix UnixEventPort value on 32-bit big endian archs

- CONTRIBUTORS
- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
- c++/src/capnp/compat/json.h
This is the first step towards JSON decoding, implementing the basic
functionality of JsonCodec::decodeRaw. The main outstanding issues are:
- it allows trailing commas in arrays and objects
- it is too liberal in number syntax, eg allowing a leading +
- it does rejects non-ASCII characters in \u escapes
Refs https://github.com/sandstorm-io/capnproto/issues/255
> Implement most of JsonCodec::decodeRaw

- doc/_includes/header.html
- doc/javascripts/main.js
- doc/stylesheets/stylesheet.css
This should look and act exactly the same as the current version, except:
1. The header of the currently-selected section is no longer clickable. (Currently it has an `onclick()` handler that maps it to "#".)
2. You can now command-click (or middle-click or whatever) the links and have them open in a new tab, without changing the state of the current tab.
> Drop onlick() handlers in documentation, in favor of simple links.

- doc/_includes/header.html
- doc/stylesheets/stylesheet.css
This addresses some of the review comments in #268.
This makes the [diff from how things were before](https://github.com/sandstorm-io/capnproto/compare/b820678de0c630da3ef672688bcfd28b62f6c47c...dwrensha:even-simpler-links) even smaller.
> Prefer display:block over inserting new <p> elements.

- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
It seems the JSON parsing is potentially reading past the end of the input buffer.
I'm pretty confident the patch should work but I need to verify that by installing Ekam and run the tests. I'll probably be able to do that before the end of this month.
> Check num remaining bytes of escaped json character

- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
Vertical tab and form feed are not specified as white space characters 
in RFC7159 but they are used as such in the parsing code:
c++/src/capnp/compat/json.c++
This patch corrects this.
> adjust the set of white space characters to the set described by RFC7159

- c++/src/capnp/layout.c++
- c++/src/capnp/orphan-test.c++
Fixes a bug reported by David Buckley in this thread: https://groups.google.com/forum/#!topic/capnproto/3MIU8xZBX1Q
Adds a test that fails before the fix and succeeds after the fix.
> Account for the possibility of adopting an empty struct.

- c++/src/kj/exception.c++
The MSVC runtime was heavily refactored, so the internal function we call to
get the current exception count changed for newer MSVC versions (as did the
offset).
I have not actually tested this code, as I don't have a native Windows dev
environment available at the moment. I just saw the `uncaught_exceptions`
proposal in #273 and remembered this comment, and realized I could fix it.
> Support extracting the current exception count on MSVC2015.

- c++/CMakeLists.txt
- c++/capnp-rpc.pc.in
- c++/kj-async.pc.in
- c++/kj.pc.in
- c++/src/kj/async-test.c++
- c++/src/kj/async.h
This would allow applications to use kj only as the promise implementation is really interesting also for projects which don't want to make RPC calls.
> Generate separate .pc files for kj and kj-async

- c++/capnp-rpc.pc.in
- c++/capnp.pc.in
- c++/kj-async.pc.in
- c++/kj.pc.in
The removal of exec_prefix in a900f2002e7489c20755235612386cebab7823bf caused the generated .pc files to be unusable when built with autotools.
The generated libdir value would read:
```
libdir=${exec_prefix}/lib`
```
but since exec_prefix was unspecified, pkg-config would choke:
```
zarvox@localhost $ pkg-config capnp-rpc --cflags --libs
Variable 'exec_prefix' not defined in '/usr/local/lib/pkgconfig/capnp-rpc.pc'
```
> *.pc.in: add exec_prefix lines

- c++/src/kj/vector.h
=nullptr releases memory
https://github.com/sandstorm-io/capnproto/issues/292
> kj/vector: add methods operator = nullptr and truncate

- c++/src/capnp/layout.c++
- c++/src/capnp/layout.h
Adding a `KJ_DASSERT` in the `setListPointer` logic flagged
non-word-multiple data sections in `INLINE_COMPOSITE` lists, which
should be impossible. This traced back to uninitialized member variables
in `ListBuilder` in the case that it was created from a null pointer.
> Fix uninitialized members of ListBuilder

- style-guide.md
Problems:
* missing ; after struct declarations
* missing static for constexpr bool value
* UnConst_<T> -> UnConst_<const T>
* UnConst = -> UnConst = typename
> style-guide: fix isConst and UnConst examples

- c++/src/capnp/compat/json.c++
This pull requests fixes the following compiler error of the master branch with Apple's latest toolchain:
```
src/capnp/compat/json.c++:521:20: error: no member named 'strtod' in namespace 'std'; did you mean simply 'strtod'?
double value = std::strtod(numberStr.begin(), &endPtr);
^~~~~~~~~~~
strtod
/usr/include/stdlib.h:162:9: note: 'strtod' declared here
double   strtod(const char *, char **) __DARWIN_ALIAS(strtod);
^
1 error generated.
make: *** [src/capnp/compat/json.lo] Error 1
```
> Fix building with Xcode 7.3

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
The method to determine, if a pointer to a member function points to a virtual method or not, depends on the ABI. Please see also:
* http://infocenter.arm.com/help/topic/com.arm.doc.ihi0041e/IHI0041E_cppabi.pdf chapter 3.2
* https://blog.mozilla.org/nfroyd/2014/02/20/finding-addresses-of-virtual-functions
To reproduce it, run unit test Async/GetFunctorStartAddress on an ARM hardware. If you don't have one, just compile cap'n'proto with an ARM compiler and run it via QEMU. #
> Fixed access violation in GetFunctorStartAddress()

- c++/src/capnp/any-test.c++
- c++/src/capnp/arena.h
- c++/src/capnp/common-test.c++
- c++/src/capnp/common.h
- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/capnpc-capnp.c++
- c++/src/capnp/compiler/evolution-test.c++
- c++/src/capnp/compiler/module-loader.c++
- c++/src/capnp/encoding-test.c++
- c++/src/capnp/fuzz-test.c++
- c++/src/capnp/message.c++
- c++/src/capnp/schema-parser.c++
- c++/src/kj/CMakeLists.txt
- c++/src/kj/common.h
- c++/src/kj/main.c++
- c++/src/kj/miniposix.h
- c++/src/kj/mutex-test.c++
- c++/src/kj/units.h
This branch contains the changes required to make lite-mode Cap'n Proto master compile again under MSVC. I tested this branch by using it to do the three-step "external capnp" bootstrapping dance (Linux, then MinGW, then MSVC).
There were a couple tests which needed at least partial disabling because they used either RPC features, or a brand pointer, neither of which are available in lite-mode.
Otherwise, all MSVC-compiled lite-mode tests pass except Exception/TrimSourceFileName: https://gist.github.com/harrishancock/6dcec0534341876a3356d081d841a79c
MSVC choked on the current implementations of both Kind_ and FromAny_. I replaced them with a std::void_t-style implementation (I named the voider alias kj::VoidSfinae). It is more verbose, but MSVC accepts it.
I replaced unistd.h with …
> Re-enable MSVC lite-mode

- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/test.capnp
Union with group in generic struct leads to compilation error in generated header:
````cpp
In file included from external/capnproto/c++/src/capnp/test_capnp/capnp/test.capnp.c++:4:0:
external/capnproto/c++/src/capnp/test_capnp/capnp/test.capnp.h:9565:10: error: need ‘typename’ before ‘capnproto_test::capnp::test::TestGenerics<Foo, Bar>::Ug::Reader’ because ‘capnproto_test::capnp::test::TestGenerics<Foo, Bar>::Ug’ is a dependent scope
inline Ug::Reader getUg() const;
````
Relavant parts in header file:
````cpp
template <typename Foo = ::capnp::AnyPointer, typename Bar = ::capnp::AnyPointer>
struct TestGenerics {
...
struct Ug;
};
template <typename Foo, typename Bar>
class TestGenerics<Foo, Bar>::Reader {
...
inline Ug::Reader getUg() const;
};
````
Compiler misses `typename` keyword …
> Bka fix union with group in generic struct

- c++/src/capnp/compat/json.c++
- c++/src/kj/string-test.c++
- c++/src/kj/string.c++
- c++/src/kj/string.h
This  PR moves number parsing code from capnp json decoder to kj::StringPtr as discussed [here](https://github.com/sandstorm-io/capnproto/pull/297#issuecomment-212764806).
Questions:
1. Integer parsing methods use base 10. My problem with auto detected base is that 0 prefixed numbers are correct decimal numbers but they are interpreted as octal. Does anybody use octal numbers? I would be ok to automatically interpret hexadecimal numbers prefixed with "0x" or "0X". 
2. There is no optional base parameter to integer parsing. I am not sure how to write the template magic that accepts optional argument only for integral types. Is this important / necessary?
3. There is one more call to `strtod` in json parser. But it throws when HUGE floating number overflows instead of interpreting the …
> Implement method kj::StringPtr:parseAs<NUMBER_TYPE>

- c++/src/kj/io.c++
Completely irrelevant change, but it bothered me just enough.
> kj/io: Make FdOutputStream::write fallback to OutputStream::write.

- c++/src/capnp/compiler/compiler.c++
Fixes #345.
I'm not sure whether the bug this fixes is observable from the public API. For example, `SchemaParser` avoids the problem by [being careful to clear the workspace](https://github.com/sandstorm-io/capnproto/blob/49ce5c971845823c09139ab269d58b6c2962172f/c%2B%2B/src/capnp/schema-parser.c%2B%2B#L191).
> prevent use-after-free in internal compiler API

- c++/CMakeLists.txt
- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-io.c++
- c++/src/kj/miniposix.h
Discovered trying to build on Android using CMake.  UIO_MAXIOV is only
exported by the linux/uio.h header which was never included.  Not sure
how normal Linux builds work.
There's also a missing reinterpet_cast & linking against -pthread is implicit on Android, so omit the -pthread flag when building against the NDK.
> Add missing include when building on Linux

- c++/src/capnp/any.h
- c++/src/capnp/capability.h
- c++/src/capnp/list.h
Fixes https://github.com/sandstorm-io/capnproto/issues/349.
> Mark Builder::operator Reader/asReader() member functions const.

- c++/src/kj/exception.c++
Fix as done elsewhere so that it builds correctly on Musl libc
as well as Glibc.
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
> Only Glibc on Linux has execinfo.h

- c++/src/capnp/compiler/node-translator.c++
Fixes [this problem](https://github.com/sandstorm-io/capnproto/commit/af899ceb5fc1c650090d7ae8ff79e925b1c7e9a9#commitcomment-18895614) reported by @kaos.
> include stdlib.h to fix build on OSX

- c++/src/kj/thread-test.c++
- c++/src/kj/thread.c++
- c++/src/kj/thread.h
I haven't actually tested the Win32/MSVC parts but I think capnp still largely doesn't compile on Win32 as-is... so we'll deal with it later I guess.
> Fix that Thread::detach() prematurely deleted objects the thread might be using.

- c++/src/capnp/layout.c++
- c++/src/kj/thread.c++
- c++/src/kj/thread.h
A few trivial fixes to get capnproto mostly compiling on windows.
I'm not a windows expert so I suggest someone who is reviews these changes.  After this change kj and capnproto seem to compile but the full build still fails on something in the test, with
6>  Compiling Cap'n Proto schema test.capnp
6>  '""' is not recognized as an internal or external command,
6>  operable program or batch file.
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 9009.
I suspect it's an issue with cmake not passing on the path of the external capnp executable but I don't know enough about it.
Tested on
* Windows 10 + cmake 3.4.3 + MSVC 2015 (partial build success)
* Ubuntu + gcc 4.8 (`make check` run successfully)
> Fixes for windows

- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.h
As suggested by @mologie in https://github.com/sandstorm-io/capnproto/issues/374.
> Disable UrgentObserver test on macOS.

- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.h
- c++/src/kj/tuple.h
Previously, in the presence of promise capabilities, a save() request could cross over the same gateway twice (or more!). Some gateways (e.g. Sandstorm's) implement one-way transformations, so this could cause the request to fail when it shouldn't.
> Fix RealmGateway to avoid double-transforms on loopback.

- c++/Makefile.am
- c++/configure.ac
- c++/src/capnp/fuzz-test.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/serialize-async-test.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
- c++/src/kj/async-unix.h
- c++/src/kj/async-win32-test.c++
- c++/src/kj/async-win32.c++
- c++/src/kj/async-win32.h
- c++/src/kj/debug.c++
- c++/src/kj/debug.h
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
- c++/src/kj/io.c++
- c++/src/kj/io.h
- c++/src/kj/main.c++
- c++/src/kj/string.c++
- c++/src/kj/time.c++
- c++/src/kj/time.h
- c++/src/kj/units.h
With these changes, all RPC tests work on Windows when compiling with MinGW.
The meat of this change is implementing EventPort and async-io in terms of Winsock and I/O completion ports.
Things still to do:
* Update cmake files.
* Make it compile in MSVC. (May or may not be a lot of work.)
* Support waiting on signalable HANDLEs (a la WaitForMultipleObjects()). This looks like it will require a thread pool since there's no way to wait on IOCP and objects in the same thread.
* The interface change to LowLevelAsyncIoProvider::wrapConnectingSocketFd() should perhaps be used on Unix too, so that they can be consistent. Maybe this method should change to `wrapSocketAndConnect()`.
* debug.c++ has some TODO(now)s.
* It looks like there is one spurious test failure when running on actual Windows …
> Support RPC on Windows (MinGW)

- c++/Makefile.am
- c++/src/capnp/canonicalize-test.c++
- c++/src/capnp/layout.c++
Fixes #394 and adds some tests that pass only after the fix is applied. 
The main problem was that `isCanonical()` did not consider the case when the struct is empty. This case is somewhat subtle, as [discussed here](https://groups.google.com/forum/#!msg/capnproto/3MIU8xZBX1Q/9oO1VouXDQAJ).
This pull request also fixes a couple other small issues: canonicalize-tests.c++ was not getting picked up by the autotools build, and the "isCanonical requires pointer preorder" test had some wrong constants.
> handle empty structs in isCanonical()

- c++/src/kj/io.h
These methods are useful if you're receiving a generic stream in application code and would like to check some non-stream behavior about the file (e.g. stat or isatty).  Of course, downcasting can fail and code should not rely on the file descriptor being available.
(Contribution is copyright Google Inc.)
> Add getFd method to FdInputStream and FdOutputStream

- c++/src/capnp/layout.h
This patch fixes a build error with Clang 4.0. The emitted error is:
> /tmp/capnproto/c++/src/capnp/layout.h:129:65: error: value of type 'bool' is not implicitly convertible to 'capnp::Kind'
However I think this change is a general bug fix, since it appears that the `ElementSizeForType` specialization for `List` was incorrect, and should have always specialized the second parameter as type `Kind` not `bool`.
> Fix conversion build error when building with Clang 4.0

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/common.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/parse/char.h
- c++/src/kj/string.h
Properties:
- Presented as a LIBRARY, designed to be unopinionated about the application using it.
- Uses KJ async framework.
- Header parsing is zero-copy. The whole header block is read into a contiguous buffer, then parsed all at once. Avoids complicated state machinery (and is probably pretty fast).
- Known headers are parsed to numeric identifiers so that the application doesn't need to look them up by string name. The app registers all headers it is interested in upfront, receiving numeric IDs for each. Some common headers also have pre-defined constants, avoiding the need for registration.
- Connection-level headers (e.g. Content-Length, Transfer-Encoding) are handled entirely internally.
- WebSocket support (planned).
Not done yet:
- Implement the version of HttpClient that …
> Add HTTP client and server implementation.

- c++/src/capnp/test.capnp
- c++/src/kj/parse/char.h
`spk dev` currently fails on Wekan due to a [non-ascii character](https://github.com/wekan/wekan/blob/81de7bceecf96c31a49baee67abfd6e597652e18/sandstorm-pkgdef.capnp#L166) in its sandstorm-pkgdef.capnp file.
This problem was introduced in https://github.com/sandstorm-io/capnproto/commit/9182e67f146d81cbb6865230172ba6a7bbd81ec6.
This commit fixes the problem.
> fix bug in parsing of non-ascii constants

- c++/src/capnp/layout.c++
The existing error message suggests this case can only arise if there is a
a bug in the library. However, malformed input can trigger the error too.
In particular, the error gets thrown when a non-double far pointer resolves
to another far pointer.
> Edit error message for the case where copyPointer() hits a FAR pointer.

- c++/src/capnp/layout.c++
> Make sure to clear tag word when upgrading a struct list.

- c++/src/capnp/canonicalize-test.c++
- c++/src/capnp/layout.c++
- c++/src/capnp/layout.h
- c++/src/capnp/message.c++
These were found with the help of [afl](http://lcamtuf.coredump.cx/afl/).
Both of the added test cases fail when run on the current master branch.
> fix various bugs in canonicalization

- c++/src/capnp/layout.c++
`ptr` is freshly allocated, so the memory it points to is already zeroed, so this `memset()` is always a no-op. For reference, it traces back to https://github.com/sandstorm-io/capnproto/commit/bd49b14a657664ddc714f905f2077e6ad99d52e1.
> omit needless memset

- c++/src/capnp/any.c++
- c++/src/capnp/any.h
- c++/src/capnp/arena.c++
- c++/src/capnp/arena.h
- c++/src/capnp/capability.h
- c++/src/capnp/common.h
- c++/src/capnp/compat/json.capnp.h
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/grammar.capnp.h
- c++/src/capnp/compiler/lexer.capnp.h
- c++/src/capnp/dynamic.c++
- c++/src/capnp/dynamic.h
- c++/src/capnp/generated-header-support.h
- c++/src/capnp/layout-test.c++
- c++/src/capnp/layout.c++
- c++/src/capnp/layout.h
- c++/src/capnp/list.h
- c++/src/capnp/message.c++
- c++/src/capnp/orphan.h
- c++/src/capnp/persistent.capnp.h
- c++/src/capnp/pointer-helpers.h
- c++/src/capnp/rpc-twoparty.capnp.h
- c++/src/capnp/rpc.capnp.h
- c++/src/capnp/schema.capnp.h
- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/mutex.h
- c++/src/kj/units-test.c++
- c++/src/kj/units.c++
- c++/src/kj/units.h
Way back in this blog post, I described how I used template metaprogramming to detect integer overflows in Cap'n Proto:
https://capnproto.org/news/2015-03-02-security-advisory-and-integer-overflow-protection.html
Unfortunately, at the time I only got that code up to the point of being able to compile layout.c++ without errors. I didn't ever get it _running_, much less did I merge it. And over the years, it of course got out-of-date.
This PR updates the code to the current master and actually runs, with all tests passing.
I ran all the benchmarks and determined that if there is any performance impact, it is within the noise.
Code size has increased by 5%-ish. Remarkably, though, there is little difference between CAPNP_DEBUG_TYPES vs. not, so this increase seems to be coming from some …
> Actually implement integer overflow guards

- doc/cxxrpc.md
This change takes a comment about lazy execution from
https://github.com/sandstorm-io/capnproto/issues/263#issuecomment-158564701 and
adds it to the C++ RPC documentation.
Although lazy execution is described in `Promise::then()` method documentation,
it's unfortunately buried in the *Advanced implementation tips* section, and
described as an optimization rather than as a more general feature of the
asynchronous execution model. Since I recently got tripped up by this behavior,
I thought it would be worth trying to document better.
> doc/cxxrpc: Document lazy execution

- c++/Makefile.am
- c++/src/kj/compat/http.c++
After https://github.com/sandstorm-io/capnproto/commit/df2c7ec2e17b01c79dff2dc213fe77b367f77a10, the build fails for me on MacOS 10.12.4.
```
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.41)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
These changes get things working again.
> Fix autotools build on MacOS

- c++/src/capnp/message.c++
MallocMessageBuilder::allocateSegment increases the segment size on each sequential invocation, irrespective of the size actually requested by the caller. After enough invocations, it allocates more than MAX_SEGMENT_WORDS even if the caller didn't request so much. Then BuilderArena rejects the returned segment (verifySegmentSize) leading to breakage.
This would only affect multi-gigabyte messages where we also (foolishly) raise the traversal limit to accommodate. By capping excess segment allocation to MAX_SEGMENT_WORDS, @orodeh and I buy ourselves more headroom before we have to fix our application to not depend on such huge messages. (cc @ekg who had a related question on #245)
Thank you for this awesome tool!
> MallocMessageBuilder: don't allocate segments above the max serializable size

- c++/cmake/CapnProtoConfig.cmake.in
- c++/samples/CMakeLists.txt
- c++/samples/calculator-server.c++
- c++/src/kj/test-helpers.c++
This PR:
- Installs the external capnp tools if `CAPNP_BUILD_TOOLS=OFF`. This allows MSVC CMake builds to install complete, working distributions of Cap'n Proto.
- Adds a CMakeLists.txt and applies the mutable capture bug workaround for MSVC (`KJ_CPCAP`) to the C++ samples (`addressbook`, `calculator-{client,server}`).
This may resolve the immediate issue in #413, but it doesn't resolve the underlying problem, so I'm not sure if it should be closed yet.
> Build samples with MSVC

- c++/src/capnp/any-test.c++
- c++/src/capnp/any.c++
> ignore pad bits when checking for bit list equality

- c++/src/capnp/canonicalize-test.c++
- c++/src/capnp/layout.c++
Fixes #429.
I've not yet been able to figure out how to get this to pass the `-DCAPNP_DEBUG_TYPES` analysis. @kentonv, maybe you can help me with that?
> canonicalization: make sure that pad bits of primitive lists are zeroed

- appveyor.yml
- c++/src/capnp/compiler/evolution-test.c++
This commit adds an AppVeyor configuration file (appveyor.yml) and a build script (appveyor-build.bat). These files could just as well live in the c++/ directory, although that would add a step in configuring AppVeyor to build the project.
AppVeyor will autoconfigure this project from the configuration stored in appveyor.yml, so setting up an AppVeyor project for Cap'n Proto should be as simple as:
1. Log into ci.appveyor.com. You can use a GitHub account for this.
2. Select "New Project."
3. Select capnproto from the list of GitHub projects.
At this point, you should have a functioning AppVeyor project, and can select "New Build" to build the latest commit on the default branch.
A few things to note:
- To test this commit before it's merged into mainline, you'll need to fork …
> Add initial AppVeyor support

- c++/src/capnp/any-test.c++
- c++/src/capnp/any.c++
I think the most sensible definition of equality is: two values are equal if and only if they canonicalize to exactly the same bytes.
This patch fixes a case where are current implementation of equality does not match that definition.
> adjust AnyList::equals(): a list of pointers cannot be equal to a struct list

- c++/src/capnp/layout.c++
`getStructListField()`, `getStructListElement()`, `getListField()`, and `getListElement()` were removed in https://github.com/sandstorm-io/capnproto/commit/76bda20eda5eec9a811bb8d25921357b9e6736a6.
> update method names in error messages

- c++/src/kj/filesystem-disk-generic-test.c++
- c++/src/kj/filesystem-disk-old-kernel-test.c++
- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-disk.c++
- c++/src/kj/filesystem-test.c++
- c++/src/kj/filesystem.c++
- c++/src/kj/filesystem.h
I've long wanted a filesystem API that:
- Is resistant to path injection bugs.
- Uses a representation of paths that is easy to manipulate (flat strings with `/` as separators are actually incredibly tedious!).
- Canonicalizes ".." logically (by removing the previous path component) rather than physically (by climbing the directory tree), especially when dealing with the current working directory.
- Is RAII.
- Does not assume a singleton filesystem (= implements abstract interfaces so that you can provide a different implementation when desired).
- Throws exceptions on error, but lets you opt-in to programatically handling the kinds of errors that one commonly wants to handle (namely, doesn't-exist and already-exists).
- Directly supports the write-to-temp-then-atomically-replace pattern. …
> KJ Filesystem API

- c++/src/capnp/rpc.capnp
At some point isCallersFault was marked as obsolete, but the description
of abort still referenced it, suggesting particular usage. This patch
removes said references.
Since `git-diff` does *such* a good job with prose: This just removes
the two parentheticals and re-flows the paragraph.
> Remove references to obsolete isCallersFault

- c++/Makefile.am
- c++/src/capnp/compat/json.h
- c++/src/capnp/compiler/node-translator.c++
- c++/src/capnp/stringify.c++
- c++/src/kj/CMakeLists.txt
- c++/src/kj/common.h
- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/encoding.h
In particular: UTF-{8,16,32}, hex, URI encoding, C-escaped strings, and base 64.
I've historically found myself wanting these all the time in many different kinds of code.
> Add KJ utility functions to encode/decode blobs in common formats.

- CMakeLists.txt
This makes it easy to use capnproto using in source builds using git submodules. Currently once you checkout capnproto as a submodule and want to integrate it into an existing CMake build, the missing CMakeLists.txt in the base capnproto directory causes things to not work. If you would like to address this usecase via other means please let me know and I would be happy to rework the commit. For instance we could pull out the project definition in the CMakeLists.txt under c++ directory to the top level.
> Add CMakeLists.txt to top level

- c++/src/capnp/common.h
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/test.capnp
Issue #479 turns out to be a run-of-the-mill expression SFINAE / constexpr problem in MSVC. This PR:
- Adds the offending case to `test.capnp`.
- Fixes it by reverting the definition of `CAPNP_KIND(T)` back to the lite mode way of doing it.
- Sneaks in a couple comment improvements in `capnpc++.c++`, unrelated to the problem at hand.
> Fix MSVC build error when using List<T> with generic T

- CMakeLists.txt
There was already a minimum version specified in the actual CMakeLists file in the C++ directory, but since the parent file does not have it you get a warning if you build in the idiomatic cmake fashion:
```bash
mkdir build
cd build
cmake .. # <---- warning here because no minimum version specified
```
I used 3.1 as min version because that is the same as specified in child file.
> Add cmake_minimum_required to root CMakeLists.txt

- c++/src/capnp/CMakeLists.txt
- c++/src/kj/CMakeLists.txt
The Autotools and CMake builds are almost the same, except for
the libraries not being generated as versioned libraries in CMake.
Fixing this lets Linux CMake builds be on the same level as Autotools ones.
> Add versioning to the libraries in the CMake build

- doc/language.md
While comments should appear after the code, some examples violate the convention. This commit enforces the rule.
Also, some additions are made for consistency.
> Doc: Enforce comment-after-code rule

- c++/src/kj/CMakeLists.txt
synchrozines behavior with autoconf build
https://github.com/capnproto/capnproto/issues/515
> cmake: do not install header miniposix.h

- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/mutex.h
Currently only implemented for Linux (when using futexes), since that's what I use. Will expand to other platforms later.
> Implement MutexGuarded::when() to wait for a condition.

- c++/src/capnp/capability.c++
- c++/src/capnp/layout.c++
When building on gcc 5.4.0 with -fsanitize=vptr (enabled by -fsanitize=undefined) linking libcapnp.a fails in layout.c++.o with `undefined reference to `typeinfo for capnp::ClientHook'.
This is because `ClientHook::NULL_CAPABILITY_BRAND` is defined in layout.c++ and fsanitize=vptr makes that definition depend in some way on the vtable. Simplest workaround is to drag the vtable in as well by defining the first virtual function. Fortunately in this case this is `ClientHook::getLocalServer(_::CapabilityServerSetBase&)` which has a trivial implementation and does not drag in any other symbols.
Note https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64670
> Fix link errors with -fsanitize=vptr

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- doc/cxxrpc.md
Since `kj::StringPtr` supports embedded `NULL`s, copy its entire data buffer to the `sockaddr_un` structure instead of using `strcpy`.
On Linux, this allows the use of the abstract socket namespace, where the first character in the path is `\0`
> RPC: Support abstract unix socket addresses on Linux

- c++/src/kj/array.h
ubsan complains about the invalid reference even if it is unused:
```
../src/kj/parse/../array.h:453:59: runtime error: reference binding to misaligned address 0x7fa57ffffffa for type 'const kj::ArrayDisposer', which requires 8 byte alignment
```
> avoid passing invalid reference to Array<T> constructor

- c++/src/capnp/serialize-packed-test.c++
- c++/src/capnp/serialize-packed.c++
- c++/src/capnp/serialize-packed.h
Fixes an error in the test suite that was reported by ubsan, and adds documentation about `PackedOutputStream`'s alignment assumptions.
As far as I can tell, the error cannot occur through normal usage of `serialize_package::write_message()`.
> buffers passed to PackedOutputStream::write() must be word-aligned

- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
- c++/src/kj/compat/tls.h
Use case for me is Cloudflare's "Authenticated Origin Pulls", in which Cloudflare authenticates itself to the origin server using client certificates. Thus the origin server can ensure that it only accepts traffic through Cloudflare, without resorting to IP whitelists.
> Implement TLS option to verify client certificates.

- c++/src/capnp/layout.c++
When I run the test suite with `clang++ -fsanitize=undefined`, I see some errors of the form `runtime error: left shift of negative value -15`. This change makes the errors go away.
> ubsan: cast to unsigned integer before performing left shift

- c++/src/capnp/ez-rpc.c++
- c++/src/kj/async-io-internal.h
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/common.h
- c++/src/kj/compat/tls.c++
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
This is an important security feature for many applications which is really difficult to implement on top of the KJ interfaces prior to this change.
> Extend kj::Network interface for easy SSRF protection

- c++/src/kj/common.c++
- c++/src/kj/common.h
- c++/src/kj/parse/common.h
> Avoid MSVC workaround in parse/common.h for clang.

- c++/src/kj/one-of-test.c++
- c++/src/kj/one-of.h
This change allows:
```c++
const OneOf<Foo, Bar> var = ...;
KJ_SWITCH_ONEOF(var) {
// ...
}
```
> Allow KJ_SWITCH_ONEOF to work on const variables

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/io.h
This allows a lot of nice design patterns, and might later the the basis for capnp 3-party handoff within a machine.
(This is not needed for anything we're working on right now, but it was a fun thing to build.)
> Add AsyncCapabilityStream, an abstraction of unix sockets SCM_RIGHTS FD passing.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
(Or if it didn't send the entire request body.)
> Don't reuse HTTP client connections if the previous request didn't read the entire response.

- c++/src/kj/compat/http.c++
- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
This lets us delete a bunch of code in http.c++.
It's also really useful when you have a class that takes its dependencies by reference (probably to allow you to stack-allocate them), but you need a single Own<T> for it and its dependencies, e.g. to return from some factory function.
> Add Own<T>::attach() which is much like Promise<T>::attach()

- c++/src/kj/exception.c++
- c++/src/kj/exception.h
Currently requires KJ_HAS_LIBDL to be defined by the upstream build. Later on we can instrument the makefiles to auto-detect.
> Generate ASLR-friendly numeric stack traces.

- c++/src/kj/common.h
>  If the size is an expression that is not an integer constant expression [...], each time it is evaluated it shall have a value greater than zero.
Detected by -fsanitize=vla-bound
> Variable-length arrays must have positive bound.

- c++/src/kj/compat/http.c++
If recvData is empty, recvData.begin() is a null pointer and binding a Header reference to it is invalid.
Detected by -fsanitize=null.
> Don't bind Header reference to a null pointer.

- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
If we finish decoding in step_a state, there is no current output character, so reading *plainchar will either be an uninitialized read or (if the output buffer is minimally sized) a past-the-end read.
Detected by -fsanitize=address.
> Don't read past the end of the base64 decode out buffer.

- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
Reverts capnproto/capnproto#570
Broken -- goes into infinite loop on MSVC.
> Revert "Don't read past the end of the base64 decode out buffer."

- c++/src/capnp/layout.c++
- c++/src/capnp/serialize-packed-test.c++
- c++/src/kj/array.h
- c++/src/kj/parse/char.h
- c++/src/kj/string-test.c++
- c++/src/kj/string.c++
- c++/src/kj/string.h
It is invalid to pass null as a pointer argument to memcpy/memcmp/memset, even if the count argument is zero:
> Where an argument declared as size_t n specifies the length of the array for a
function, n can have the value zero on a call to that function. Unless explicitly stated
otherwise in the description of a particular function in this subclause, pointer arguments
on such a call shall still have valid values [...]
Detected by -fsanitize=nonnull-attribute.
Additionally, when constructing StringPtr from String, ensure that content does not bceome null. Test.
> Memcpy null src

- c++/src/kj/array.h
Reverts capnproto/capnproto#549
Introduced memory leak because zero-sized arrays are often allocated on the heap and they need to be deleted too.
> Revert "avoid passing invalid reference to Array<T> constructor"

- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
- c++/src/kj/async-unix.h
(Later, we should add a nice subprocess API around this, maybe even one that can work on Windows too...)
> Extend UnixEventPort with the ability to listen for subprocess exit.

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
Howdy @kentonv,
I'm currently porting `mozilla/rr` to FreeBSD and it depends on captnproto, so I decided to fix the build there :)
cc: @sfwhittaker/@espindola
> Add missing headers to unbreak the build on FreeBSD/Clang.

- c++/src/capnp/compiler/parser.c++
Visual Studio 2017 (14.11.25503, 19.11.25508.2) needs `#include <wincrypt.h>` for CryptGenRandom etc.
> Include <wincrypt.h> directly for WIN32_LEAN_AND_MEAN

- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
Any `Own<T>` can be converted to `Own<void>` (or `Own<const void>`). The main purpose of this is to give someone a way to invoke an object's disposer without them having to know anything about the type.
> Add support for Own<void>.

- c++/src/kj/one-of-test.c++
- c++/src/kj/one-of.h
This allows us to deal with Maybe<OneOf<...>> variables properly inside a KJ_IF_MAYBE block.
> KJ_SWITCH_ONEOF should parenthesize its argument

- c++/src/capnp/compiler/capnp-test.sh
- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/error-reporter.h
- c++/src/capnp/compiler/module-loader.c++
- c++/src/capnp/compiler/module-loader.h
- c++/src/capnp/schema-parser-test.c++
- c++/src/capnp/schema-parser.c++
- c++/src/capnp/schema-parser.h
- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/filesystem-disk-win32.c++
- c++/src/kj/filesystem-test.c++
- c++/src/kj/filesystem.c++
- c++/src/kj/filesystem.h
- c++/src/kj/refcount.c++
- c++/src/kj/refcount.h
- c++/src/kj/time.c++
- c++/src/kj/time.h
In addition to cleaner code, this has the effect of fixing a number of issues:
- Fixes #494: Windows paths are now parsed and handled a lot better. On Windows, backslashes are handled appropriately, as are absolute paths with drive letters.
- Fixes #288: Specifing a source path starting with ".." without an appropriate --src-prefix will no longer cause output files to be generated outside of the specified output directory. Instead, the output name will be based on the absolute path, and a warning will be written since this is probably not what anyone wants.
- It's no longer necessary for --src-prefix to exactly match character-for-character. Instead, the prefix and source paths are canonicalized before matching. It even works if one is relative and the other absolute.
- Relative paths are …
> Change capnp compiler to use KJ filesystem API.

- c++/src/capnp/membrane-test.c++
- c++/src/capnp/membrane.c++
- c++/src/capnp/membrane.h
- c++/src/capnp/test.capnp
I realized upon trying to use this framework in Sandstorm that proper revocation was not easy to implement as-is. It's easy enough to revoke new calls, but canceling existing calls requires implementing a custom RequestHook and such. Since revocation is arguably the most important thing one might want to do with a membrane, this should be built-in.
@harrishancock Since this is purely for Sandstorm, not for Cloudflare, I'm not marking you as a reviewer. Just doing the PR to get CI results.
> Extend membrane framework to make revocation easy.

- c++/src/kj/compat/gzip.h
The usual drill, just needed to add some `final` keywords.
> Silence compiler warning about non-virtual dtor on non-final classes

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Although applications in theory shouldn't care to see connection-level headers (e.g. `Transfer-Encoding`), higher-level specs like the JavaScript Fetch API often specify that these headers should be visible, and they can be useful for debugging. So, this change makes it so that the application can see the connection-level headers on incoming requests.
For outgoing requests, the application can provide an HttpHeaders object that specifies these headers (important especially for the pass-through case), but the HTTP implementation will ignore them.
Additionally, we can now allow the application to set WebSocket connection-level headers on non-WebSocket requests. This is useful for frameworks that emulate WebSocket over HTTP and assume the ability to set WebSocket headers (especially …
>  Refactor handling of connection-level headers.

- c++/src/kj/async-io.c++
- c++/src/kj/compat/gzip.c++
Unfortunately TCP does not always distinguish between dirty connection failure and clean connection shutdown. In practice, though, "Premature EOF" errors on streams basically always appear to be due to disconnects (including when the peer crashes).
> Treat 'Premature EOF' error on async stream as DISCONNECTED.

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
AFAICT, without this, there's no way to convince capnp to send a message larger than 64MB, even if you know the other side will accept it. This should cause it to work reasonably, assuming both sides set their message limits identically.
> Allow working around the message size limit

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/common.h
- c++/src/kj/memory.h
Array::attach() is like Own::attach().
ArrayPtr::attach() promotes an ArrayPtr to an Array by attaching other objects to it. (Hopefully one of those objects actually owns the underlying array data.)
> Add Array::attach() and ArrayPtr::attach().

- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/encoding.h
The main point here is to prevent escaping '+' in a query string as '%2B'. It should instead be interpreted as a space.
Note that application/x-www-form-urlencoded is the format that the WHATWG URL spec uses to serialize query's through its URLSearchParams interface: https://url.spec.whatwg.org/#concept-urlsearchparams-update
> Use application/x-www-form-urlencoded for URL query strings

- c++/src/kj/async-io.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
This allows an application which calls drain() to potentially pass off HTTP connections to a new HttpServer afterwards. Without this, the application has no way to know if the connections are in an indeterminant state.
This change also makes it OK for an application to fail to read the whole request body. Previously, if an app returned a response without reading the whole request, an exception would eventually be thrown, but potentially not until the client had initiated a new request on the same connection. The client would then get a spurious 500 error.
> Extend HttpServer to inform the caller when a connection ends cleanly on drain().

- c++/src/capnp/compat/json.capnp.h
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/grammar.capnp.h
- c++/src/capnp/compiler/lexer.capnp.h
- c++/src/capnp/rpc.capnp.h
- c++/src/capnp/schema.capnp.h
Various versions of MSVC have various troubles deducing the Kind K of a List<T, K>. This change removes any need for the compiler to deduce the Kind, and just hard-codes it into the generated code.
Fixes #642.
> Explicate List element Kinds in generated code

- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
The relative URL parser allowed certain hosts which the absolute parser correctly weeded out. This change copies two lines from the absolute parser over to the relative parser.
> Fix bugs in relative URL parser

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Primarily, we want to support proxies passing through such requests blindly. So, I didn't add any new API for this, just added some hacks so that things "just work" when proxying.
> Support sending GETs with bodies.

- c++/src/kj/async-io-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/filesystem-disk-old-kernel-test.c++
In particular, when using the new Ekam cross-compiling support that I'm working on.
> Make all tests pass on qemu-aarch64

- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/encoding.h
~DRAFT - do not merge yet. See below about path serialization for my main concern.~
This adds `encodeUriFragment()`, `encodeUriPath()`, and `encodeUriUserInfo()` to kj-encoding, and uses them in `kj::Url::toString()` to become slightly more conformant in the eyes of the WHATWG URL spec.
It's worth noting that the reserved character set of `encodeUriFragment()` is a subset of `encodeUriPath()`, which in turn is a subset of `encodeUriUserInfo()`, owing to their positions in URL strings. All three functions' reserved character sets are subsets of `encodeUriComponent()` (RFC 2396).
~**Path serialization:** I implemented `encodeUrlPath()` the obvious way: by following what the spec says to do. However, the spec says not to encode `/` characters. This means that if we parse a URL with one path …
> Implement various WHATWG URL percent encoding functions

- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
- c++/src/kj/compat/url.h
~This makes `kj::Url::query`'s value type a `Maybe<String>` instead of just a `String`. **This is a breaking source change.** I think we could get the best of both worlds if we include `kj/encoding.h` and make it an `EncodingResult<String>` instead, with a "failed" empty string value for null valued query parameters, and a "successful" empty string value for empty valued query params. Any preference?~
~Also, note that this PR is based on the WHATWG URL percent-encoding PR (to avoid conflicts), which isn't merged yet. Hopefully when that gets merged, this one will magically become one single commit? Or maybe this one will break and I'll have to rebase manually anyway. :)~
Edit: now distinguishes based on allocated-ness of `QueryParam::value`, as discussed.
> Distinguish between empty- and null-valued query parameters

- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
We'll need more hostname-related code changes in the future, but for now this will solve a Cloudflare customer's existing bug report.
> Allow underscores in URL hostnames

- c++/src/kj/compat/url-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/encoding.h
Our query string encoding function (encodeWwwForm()) was already doing the right thing.
I changed the comment in encodeUriPath() to clarify that it's intended to implement a URL class which stores its path in percent-decoded form, not either/or. I was wrong before.
> Ensure '%' signs get round-tripped in URL path, fragment, userinfo

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/refcount.h
This lets you construct an AsyncInputStream / AsyncOutputStream pair that operates entirely within userspace, rather than pushing through a kernel-level pipe. This is far more efficient, avoiding system calls and reducing copies.
The pipe does not buffer at all. Instead, it waits for both a read() and a write() call to be active at the same time, and then it fulfills one with the other.
This implementation also optimizes pumps. Imagine the situation: you create a pipe; you call pumpTo() on the write end to pump it to some other; then you write to the write end of the pipe. In this case, the write will *directly* call the target stream to which the pipe is being pumped. Hence, adding daisy-chained pipes on top of a final output stream does not incur additional copies of the data. …
>  Implement in-process byte stream pipes.

- c++/src/kj/filesystem-disk-test.c++
Some memory-based filesystems, namely tmpfs, select their underlying block size
equal to the configured page size of the platform/OS.
On systems with page size not equal to 4K (for example, arm64 can be configured
to have 16K or 64K page sizes -
https://www.kernel.org/doc/Documentation/arm64/memory.txt) "DiskFile holes"
test fails, when creating a file on a memory-based filesystem, because it
"punches" a 4096 byte hole in the file (using fallocate) and expects the number
of filesystem blocks used by the file to decrease. When the system page size is
greater than 4K, 4096 byte hole is not enough to make the OS release the
underlying blocks.
Need to punch a whole, which is equal to the underlying filesystem block size at
least.
> Fix filesystem-disk-test to support platforms with non-4K filesystem block size

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
It turns out wrapping an HttpService in an HttpClient is considerably more complicated than vice versa, due to the need for pipes. This commit adds a WebSocket pipe implementation very similar to the recent byte-stream pipe (though considerably simpler since there's no need to deal with mismatched buffer sizes).
> Implement newHttpClient(HttpService&).

- c++/src/kj/debug.c++
This fixes a problem when building for older android versions,
```
capnproto/c++/src/kj/debug.c++:250:23: error: no viable overloaded '='
sysErrorArray = strerror_r(errorNumber, buffer, sizeof(buffer));
~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
capnproto/c++/src/kj/string.h:53:7: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'int' to 'const kj::StringPtr' for 1st argument
class StringPtr {
^
capnproto/c++/src/kj/string.h:53:7: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'int' to 'kj::StringPtr' for 1st argument
1 error generated.
```
I've rewritten it slightly to make it more obvious when it applies.
> Fix problem on android api < 23

- CONTRIBUTORS
- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
- c++/src/capnp/compat/json.h
- Add support for decoding with Orphanage (as a consequence, allow decoding of non-struct root objects).
- Add support for custom decoding type and field handlers.
- Make basic tests verify that they roundtrip to the same string.
- Simplify implementation of number decoding and, as a bonus, allow overflowing floating numbers to convert to +/-`Infinity` like they do in `JSON.parse`.
> Rewrite JSON decoding

- c++/src/kj/async-io.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
I ran into these because the userspace pipe's `BlockedWrite` state uses a gather-write in its `pumpTo()` implementation.
> Chunked body fixes in kj-http

- c++/src/kj/compat/http-test.c++
The braced array literals seem to be constructed as temporaries. The test passes in debug builds, but in optimized builds, the arrays have been overwritten by the time they are used.
> Fix chunked body gather-write test.

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/io-test.c++
- c++/src/kj/io.c++
- c++/src/kj/io.h
Reading an unbounded amount of data from a stream is a potential DoS vector. To manage this risk, `readAllText()` and `readAllBytes()` now accept a `limit` parameter. For source backwards-compatibility, this limit defaults to `kj::maxValue`.
The presence of this limit might make it seem that `readAllText()`/`readAllBytes()` are now misnamed. If we care, we could add `read*Until()` overloads that accept a mandatory parameter, and deprecate the `readAll*()` versions.
> Add limit to readAllBytes()/readAllText()

- c++/src/kj/CMakeLists.txt
- c++/src/kj/compat/gzip-test.c++
- c++/src/kj/compat/gzip.c++
- c++/src/kj/compat/gzip.h
- Split gzip tests
- Add kj-gzip to CMakeLists.txt
- Add decompress mode to `GzipAsyncOutputStream` for granular push-based decompression API.
- Add ability to flush `GzipAsyncOutputStream` at an arbitrary point.
> Add GzipAsyncOutputStream::Decompress and ::flush

- c++/src/kj/async-io.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Before this change, if *either* the `from` or the `to` end of the pump threw a DISCONNECTED exception, we'd then try to call `to.disconnect()`. But if the exception had been thrown from `to` in the first place, then this would throw again, this time complaining about a previous write not having completed. But the whole point was always to propagate errors from the *receiving* end to the sending end. An error on the sending end should just propagate up the stack.
> Fix handling of disconnect during WebSocket::pumpTo().

- c++/src/capnp/any.c++
- c++/src/capnp/any.h
- c++/src/capnp/layout.c++
- c++/src/capnp/layout.h
Stumbled upon this, by writing a gtest like this:
```c++
AnyStruct as1;
AnyStruct as2;
// do stuff with as1 & as2…
EXPECT_EQ(as1, as2); // does not compile because ==/!= operators are expected to be const
// we can workaround this currently by using the "equals" function
EXPECT_EQ(capnp::Equality::Equal, as1.equals(as2));
```
Compiles fine in local build setup (Clang 6.0,Debian 9); Waiting for Travis and Appveyor builds…
> fix const-correctness on AnyPointer equality checks

- appveyor.yml
- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.h
- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async.h
- c++/src/kj/common.h
Just like `Promise<Promise<T>>` reduces to `Promise<T>`, we should be able to reduce `Promise<RemotePromise<T>>`. Moreover, this reduction should support pipelining, hence the reduced type should itself be `RemotePromise<T>`.
Fixes #341
> Automatically reduce `Promise<RemotePromise<T>>` -> `RemotePromise<T>`.

- c++/src/kj/exception.c++
- c++/src/kj/exception.h
- c++/src/kj/string-test.c++
- c++/src/kj/string-tree.c++
- c++/src/kj/string-tree.h
- c++/src/kj/string.c++
- c++/src/kj/string.h
This mainly requires avoiding `malloc()`.
> Add functions for async-signal-safe stringification

- c++/cmake/CapnProtoTargets.cmake
It looks like pkg-config silently drops -I and -L flags pointing to
default directories:
```
$ cat /usr/lib/pkgconfig/capnp.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
Name: Cap'n Proto
Description: Insanely fast serialization system
Version: 0.7-dev
Libs: -L${libdir} -lcapnp -pthread  -lpthread
Libs.private:  -lpthread
Requires: kj = 0.7-dev
Cflags: -I${includedir} -pthread
$ pkg-config --libs capnp
-lcapnp -pthread -lpthread -lkj -pthread -lpthread
```
Ideally, however, we should use FindPkgConfig.cmake's own facilities
to generate IMPORTED targets from pkg-config files.
> cmake: drop NO_DEFAULT_PATHS when searching libraries

- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
If no child process has changed state, `waitpid()` returns zero. But if there are no more child processes at all, it returns -1 and sets `errno` to `ECHILD`.
Since `checkExits` calls `waitpid()` in a loop, it should probably not throw an exception, and instead ignore `ECHILD`.
+Unit test modified to exhibit the behaviour
> Ignore ECHILD in UnixEventPort::ChildSet::checkExits

- c++/src/kj/refcount.h
If a multiply-inherited subclass of `kj::Refcounted` is move-assigned from an object of its other parent class's type, the reference count would get zeroed out. This change makes such mistakes a compile error.
> Disallow copy construction/assignment of (Atomic)Refcounted classes

- c++/src/kj/CMakeLists.txt
Add `units.c++` and `encoding.c++` to allow the linking of `kj::ThrowOverflow::operator()()` and `kj::decodeWideString` respectively. The lite build remains a fair amount smaller than heavy build and has been tested as working on Clang and GCC both.
This is needed in order to fix #576 and other undefined symbols with current CMake setups. I am unsure of the scope of lite builds and their exact exclusions but, without these two sources in the build process, the library seems to have major issues linking to a usable state.
> Fix linking during lite builds

- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/table.c++
Hi! I've noticed that master fails to compile for Android but I needed that to verify some things. Tested with the fixes and it still builds fine on Linux, Mac OS 10.13 and Android using NDK r16b. Linux build still uses aligned_alloc because _ISOC11_SOURCE is actually defined in C++ as well with g++ and clang++ both. Using feature test macros seemed more robust to me than sprinkling `__ANDROID__` everywhere.
> Two fixes for build failure on Android (resubmit)

- c++/src/capnp/compat/json.c++
- c++/src/capnp/compiler/capnp.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/string.c++
- super-test.sh
No real bug fixes here, just:
- Update bitrot in super-test.sh, e.g. GCC is deprecated in favor of Clang on Android.
- Fix warnings due to char being unsigned.
- Fix NaN canonicalization, which only matters for tests doing bitwise comparisons.
- Fix tests using /tmp, which is in a different location on Android.
> Fix Android build/test issues.

- c++/src/kj/compat/tls-test.c++
These errors apparently don't show up until the first read with 1.1.1, and may have different messages.
Apparently this landed on my Debian machine *today* and then all of the sudden the test was failing. I was so confused.
> Fix tls-test for OpenSSL 1.1.1.

- .travis.yml
- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/compat/url.h
`kj::newTee()` accepts an `Own<AsyncInputStream>` and returns two `Own<AsyncInputStream>`s which provide access to the same data as the original.
The two new `Own<AsyncInputStream>` objects are called branches of the tee. Each branch may have a sink. A caller may create a sink on a branch by calling `tryRead()` or `pumpTo()` on it. The returned promise *is* the sink.
Sinks created by `tryRead()` provide vacuum, whereas sinks created by `pumpTo()` do not. If a tee has at least one branch with a sink with vacuum, it will wait for any backpressure from any `pumpTo()` sinks to subside, then perform an inner read to try to fill the vacuum. This means that in a pristine state, the first `tryRead()` finishes as soon as data is available (because the pump has zero backpressure), but subsequent …
> Implement kj::newTee()

- c++/src/kj/debug.h
This fixes "dangling else" warnings when KJ_LOG is used after unbraced if statement.
The code such as:
```
if (some_function1())
KJ_LOG(ERROR, "failed1");
if (some_function2())
KJ_LOG(ERROR, "failed2");
```
produces warnings about ambiguous or dangling else. I know this form is sometimes frowned upon but I do not think that the library provided macro should impose any particular style on the surrounding code.
> Wrap KJ_LOG in braces

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
Previously we depended on the compiler to implicitly invoke the copy constructor followed by the assignment operator, but this can lead to the compiler making surprising decisions in some cases, such as deciding that the literal 0 is a better match for nullptr than for T. Overloading operator=() to match every copy constructor is the safe thing to do.
> Overload Maybe::operator=() to match all copy constructors.

- c++/src/capnp/compat/json-rpc-test.c++
- c++/src/capnp/compat/json-rpc.c++
- c++/src/capnp/compat/json-rpc.capnp
- c++/src/capnp/compat/json-rpc.h
- c++/src/capnp/compat/json.capnp
- c++/src/capnp/compat/json.h
- c++/src/capnp/dynamic.h
- c++/src/capnp/serialize-async.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
I wrote this in order to implement the vscode Language Server Protocol for Ekam, but @RReverser might find it interesting for work he has been doing.
Ekam vscode integration implemented in: https://github.com/capnproto/ekam/pull/20
> Implement JSON-RPC adapter to Cap'n Proto interfaces.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
There is currently no way to explicitly omit a Content-Length/Transfer-Encoding header on an HTTP response. This is awkward for a proxy, which would ideally pass along responses as-is, even if they have no such headers.
This change allows an author to pass zero as the expected body length to HttpService::Response::send() to mean "do not set any body header." This means that a proxy might strip Content-Length: 0 headers, but will never add a Content-Length header where there was none before.
> Zero-length HTTP responses get no Content-Length header

- c++/src/capnp/compat/json.c++
Forward slashes don't need to be escaped in JSON.
Not tested but I assume you have some kind of CI system (and it's a trivial change anyway).
> Don't escape forward slashes in JSON output

- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
- c++/src/kj/compat/url.h
This is to fix a complaint about Cloudflare Workers removing these components as requests pass through, which apparently breaks someone's funky URLs.
Arguably "." and ".." processing presents a similar problems. But, allowing ".." to pass through is much more likely to lead to security problems. Browsers will generally process "." and ".." before sending a request (whereas they won't collapse double-slashes), so we're following their lead here.
> Extend kj::Url with option to not collapse empty path/query components.

- c++/src/capnp/serialize-packed.c++
The overflow happens e.g. when using an ArrayInputStream over an array larger than max unit32.
> Fix overflow in PackedInputStream.

- c++/src/kj/filesystem-disk-unix.c++
If holes are not supported on the target system and size to `copy` was passed as `kj::maxValue()`, this could lead to near-infinite loops.
> Detect EOF in copyChunk

- c++/src/kj/async-unix-test.c++
This seems to be the case, for example, on WSL.
@RReverser
> In AsyncUnixTest::UrgentObesrver, work around MSG_OOB not being supported.

- c++/src/kj/io-test.c++
- c++/src/kj/io.c++
This is to help debug an issue in Cloudflare Workers. I also added the same debug info to the ArrayOutputStream case, mostly for pleasing symmetry.
/cc @RReverser
> Log more info in VectorOutputStream::write() KJ_REQUIRE

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
The client app will typically discard the returned response body upon reading EOF. However, the server app may not actually be "done" with the service callback yet at this point. Usually it completes very soon after, but it may need another turn or two of the event loop. If the client discards the response body stream, the server-side promise is discarded, cancelling whatever was left. This is awkward, so we should instead delay the client from seeing EOF until the server has actually finished up.
> Fix HttpClient-from-HttpService wrapper prematurely cancelling service promise.

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/async-unix.c++
- c++/src/kj/async-unix.h
- c++/src/kj/compat/gzip-test.c++
- c++/src/kj/compat/gzip.h
- c++/src/kj/compat/http-socketpair-test.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/compat/tls.c++
NOTE: The first two commits are from PR #787, on which the rest of this is based.
The strategy here is to add a method `AsyncOutputStream::whenWriteDisconnected()` which detects when the stream becomes writable-but-errored -- i.e. write() won't block, but will fail with some other error. This is indicated on Unix by POLLHUP or POLLERR.
Once we have that, we can easily join it with the promise returned by `HttpService::request()` to cancel processing on disconnect.
To help thoroughly test this, I arranged for http-test to run twice, once using userspace pipes (as it did before this change) and once using kernel socketpairs. The latter test is only run in the Ekam build at present, not automake/cmake. I expect it would fail on Windows (due to a missing implementation of …
> Make HttpServer detect client disconnect and cancel request processing

- c++/src/kj/array.h
For trivial types, we already had this const_cast (line 622), but for non-trivial types it was missing.
> Fix compile error with Array<const T>.

- c++/src/kj/table-test.c++
- c++/src/kj/table.c++
- c++/src/kj/table.h
InsertionOrderIndex manages memory, but it didn't have an explicit move constructor or move assignment operator, causing segmentation faults and double frees.
> Implement InsertionOrderIndex move constructor/assignment operator

- c++/src/capnp/CMakeLists.txt
- c++/src/capnp/compiler/capnp.c++
On Windows executables needs to end with .exe.
Fix this in CMakeLists.txt and update capnp detection code accordingly.
> Fix capnpc extension handling on Windows

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
`Maybe<T&>` does not own the `T` it points to. But, before this change, initializing a `Maybe<T>` from a `Maybe<T&>` would inadvertently perform a move, stealing the `T` away from its owner.
> `Maybe<T>(Maybe<T&>&&)` should do a copy, not a move.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
WIP... Seems to work OK, but I still need to make it use PromiseOutputStream instead of the pipe.
> Add HttpClient wrapper for limiting concurrent connections

- c++/src/kj/filesystem-disk-unix.c++
for #800 
Verified with the latest NDK bundle, version 19.2.5345600
> Fix #800 : pwritev() missing before Android API Level 24.

- c++/src/kj/encoding-test.c++
Initializer lists are temporaries. The code apparently works in debug mode but fails when optimized.
> Fix uninitialized byte arrays in encoding-test.

- c++/src/kj/async-io-test.c++
(This should solve the problem with the Workers CI failure.)
> Skip test that fails under qemu-user, probably due to a qemu bug.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
The main case where the code was wrong is when neither Content-Length nor Transfer-Encoding was provided on a response. In this case the response is delimited by closing the connection, but KJ previously rejected it outright. AFAICT almost no one on the whole internet relies on this anymore... almost.
> Align HTTP entity-body delimiting rules with RFC 7230.

- c++/src/capnp/arena.h
- c++/src/capnp/capability-test.c++
- c++/src/capnp/message-test.c++
- c++/src/capnp/message.c++
- c++/src/capnp/message.h
- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
These have repeatedly come up as something that would be useful.
See individual commits for details.
> Introduce kj::attachVal(), kj::attachRef(), and capnp::clone() utility functions

- c++/Makefile.am
- c++/configure.ac
BSD Make does not support `$(shell ...)`. It does support an alternative, `!=` assignments (which, confusingly, don't mean "not equal" but rather "evaluate the right in the shell before assignment"). GNU Make also supports `!=` as of version 4.0, released in 2013. Unfortunately, f***ing Apple ships GNU Make version 3.81, from 2006, with MacOS/XCode.
@pwrdwnsys can you please test whether this fixes your build issue? I don't have a BSD box available to test with.
> Calculate SO_VERSION in configure for compatibility with BSD make.

- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/mutex.h
Also, add support for passing a timeout to when().
> Implement MutexGuarded::when() (i.e. condvars) on all platforms.

- doc/encoding.md
It helps to list, in one place, both ways the list size is conveyed.
> Doc fix: Expand the short description of the list pointer.

- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/filesystem-disk-win32.c++
I had a snarky comment in the Windows code being annoyed that mapping an empty file was documented to fail... but it turns out zero-length mappings fail on Linux, too. Also my work-around on Windows didn't work (but was never tested).
This PR fixes both.
This was prompted by @KubaO observing that `capnp compile` on an empty source file failed with a cryptic mmap error.
Closes #854, @KubaO's attempt at fixing this, since the correct fix is in the filesystem API, not in the compiler.
> Fix filesystem API: Empty mmaps should succeed.

- c++/Makefile.am
- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-unix.c++
- c++/src/kj/async-unix.h
- c++/src/kj/async-win32.c++
- c++/src/kj/async-win32.h
- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/test.c++
- c++/src/kj/time-test.c++
- c++/src/kj/time.c++
- c++/src/kj/time.h
- c++/src/kj/timer.h
This eliminates the use of `std::chrono`, helps clean up some code in the condvar implementation, and is something I've wanted on several occasions.
> Add basic system clock APIs.

- c++/src/kj/common.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
~~This avoids needing to add another option flag to control whether or not to log protocol errors. It's a bit more flexible, too -- we could use these hooks to log 400 responses, but ignore other errors or record them only as metrics.~~
Updated: separated the hook out into an interface and provided a `Response&` for response customization.
> Add HttpServerErrorHandler interface to provide visibility and customization of protocol errors

- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
- c++/src/capnp/compat/byte-stream-test.c++
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/byte-stream.capnp
- c++/src/capnp/compat/byte-stream.h
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/http-over-capnp.capnp
- c++/src/capnp/compat/http-over-capnp.h
- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
~*[NOTE: This PR is targeting the `streaming` branch because it builds on top of that, but should be redirected to `master` once `streaming` has been merged.]*~
This allows an HTTP request/response to be forwarded over Cap'n Proto RPC, multiplexed with arbitrary other RPC transactions.
This could be compared with HTTP/2, which is a binary protocol representation of HTTP that allows multiplexing. HTTP-over-Cap'n-Proto provides the same, but with some advantages inherent in leveraging Cap'n Proto:
- HTTP transactions can be multiplexed with regular Cap'n Proto RPC transactions. (While in theory you could also layer RPC on top of HTTP, as gRPC does, HTTP transactions are much heavier than basic RPC. In my opinion, layering HTTP over RPC makes much more sense because of this.)
- HTTP …
>  Define and implement HTTP-over-Cap'n-Proto

- c++/src/capnp/message.h
Building with Emscripten fails with
capnproto\capnproto\c++\src\capnp\message.c++:55:5: error: static_assert failed "arenaSpace is too small to hold a ReaderArena.  Please increase it.  This will break ABI compatibility."
Is constexpr usable? I don't know what C++ standards this project aims to be compatible with.
> Increase arenaSpace for emscripten builds

- c++/src/kj/string.h
I initially didn't read the docs carefully enough and returned a StringPtr to a locally allocated string. Whoops. Make the doc a little clearer about this.
> Give an example of returning an owning string for KJ_STRINGIFY

- c++/src/capnp/rpc-twoparty.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
- c++/src/kj/compat/http-test.c++
For regular (non-RT) POSIX signals, the process can only have at most one instance of each signal queued for delivery at a time. If another copy of the signal arrives before the first is delivered, the new signal is ignored. The idea was that signals are only meant to wake the process up to check some input; the signal itself is not the input.
POSIX RT signals are different. Multiple copies of the same signal can be queued, and each is delivered separately. Each signal may contain some additional information that needs to be processed. The signals themselves are input.
UnixEventPort's `onSignal()` method returns a Promise that resolves the next time the signal is delivered. When the Promise is resolved, the signal is also supposed to be blocked until `onSignal()` can be called again, so …
> Fix handling of queued RT signals, plus some other crap

- c++/src/capnp/compat/std-iterator.h
- c++/src/capnp/list.h
Allow including a header to obtain the iterator traits instead of
needing to carefully define a slightly more obscure macro that someone
might be tempted to define globally.
Fixes #892
> Add compat/std-iterator.h

- c++/src/capnp/compat/http-over-capnp.c++
`task` needs to be the last member of ServerRequestContextImpl, because when we construct it, we call `service.request()`, which may call back to send() or acceptWebSocket(), which require `replyTask` to be initialized.
> Fix failures in http-over-capnp-test.

- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
This is a no-brainer given AsyncIoStream has getsockopt() and getsockname(), whereas ConnectionReceiver has only getsockopt().
> Add getsockname() to ConnectionReceiver.

- c++/src/kj/compat/tls-test.c++
Introduced in 58d56f4c5 ("Enable TLS 1.3 by default").
> tls-test: Update error message to match new boringssl behavior

- c++/src/kj/compat/tls-test.c++
Note that I only care about supporting BoringSSL at master since BoringSSL does not do versioned releases.
> Update tls-test for BoringSSL changes.

- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
When VatNetwork::connect() returns nullptr, it means that the caller is trying to connect to itself.
rpc-test.c++ failed to test this in two ways:
- The test VatNetwork's connect() never returned null.
- There was no test case for loopback connect.
As a result, the code to handle loopback in rpc.c++ had bitrotted. It failed to handle the new bootstrap mechanism introduced in v0.5, and instead only implemented the restorer mechanism from 0.4.
/cc @bretthoerner
> Fix RPC loopback bootstrap().

- c++/src/capnp/compat/http-over-capnp.c++
Some applications expect to be able to inspect these headers in order to learn about the properties of the entity-body. Currently, over RPC, the sender could send arbitrary header values that have nothing to do with the actual body. Instead, let's just overwrite them to match.
/cc @bretthoerner -- this fixes your "missing body" issue
> Override Content-Length and Transfer-Encoding in http-over-capnp.

- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
Fibers allow code to be written in a synchronous / blocking style while running inside the KJ event loop, by executing the code on an alternate call stack and switching back to the main stack whenever it waits.
We introduce a new function, `kj::startFiber(stackSize, func)`. `func` is executed on the fiber stack. It is passed as its parameter a `WaitScope&`, which can then be passed into the `.wait()` method of any promise in order to wait on the promise in a blocking style. `startFiber()` returns a promise for the eventual value returned by `func()` (much as `evalLater()` and friends do).
WIP DO NOT MERGE: I haven't done Windows yet. But it should be easy since Windows' fibers API is actually really good. Putting up this PR now to get ahead of MacOS failures.
> Implement fibers

- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/compat/http.c++
This just moves Promise{Io,Output}Stream from http.c++ to PromisedAsync{Io,Output}Stream in async-io.c++ and exposes them via newPromisedStream() so other code can use them.
No substantive code changes.
> Make newPromisedStream() generally available

- c++/cmake/CapnProtoConfig.cmake.in
as kj/test.c++ contains "KJ_MAIN(kj::TestRunner);", this will generate the main entry for a process, so as to hidden the one defined in the main program(which is maybe the most common use case of CAPNP_LIBRARIES)
> remove kj-test from CAPNP_LIBRARIES

- c++/src/capnp/schema-parser.h
In the documentation of parseFromDirectory():
* parseFromDirectory() is equivalent to parseFile(...), not
parseFromDirectory(...).
* Use `.` to dereference instead of `->`. `parser` is not a pointer.
> Fix method name and dereferencing in parseFromDirectory() comments

- c++/src/kj/map-test.c++
- c++/src/kj/table.h
If the creator callback throws, we shouldn't leave the table broken.
> Fix Table::findOrCreate() to be exception-safe.

- c++/src/kj/one-of-test.c++
- c++/src/kj/one-of.h
E.g. it should be possible to initialize `OneOf<T, U, V>` from `OneOf<T, V>`.
This change also makes the error messages nicer when someone tries to access a OneOf member type that it doesn't have. This will now fire a static_assert with an error message rather than produce an obscure error about `TypeIndex_` being incomplete.
> Allow OneOf to be initialized from a subset OneOf.

- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.h
If the RpcSystem is destroyed, the underlying VatNetwork will probably be destroyed too, and reading messages from it may be a use-after-free.
This fixes valgrind errors in rpc-twoparty-test.
Closes #941
> Cancel every RPC connection's incoming message loop when the RpcSystem is destroyed.

- c++/src/capnp/any.h
- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
- c++/src/capnp/compat/byte-stream-test.c++
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/layout.c++
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/test-util.h
Apparently, I only initiated capability promise resolution in one of LocalClient's two constructors. Ironically, the other constructor is always the one used by ByteStreams created by ByteStreamFactory, because they are always placed in a CapabilityServerSet. The effect is that ByteStreams couldn't be path-shortened in cases that require promise capabilities to resolve before unwrapping can occur, such as over RPC.
This PR fixes the bug and adds a test covering the RPC use case.
> Fix bug in byte stream path-shortening.

- c++/src/kj/function.h
Since we store a different type in this space, we need to allocate the space as `char` to comply with aliasing rules. This actually caused a problem under GCC 10 on armv7hl with optimizations enabled, and this patch is reported to fix it.
Fixes #937.
> Fix aliasing violation.

- c++/Makefile.am
Automake was installing it to `$PREFIX/include/capnp/json.capnp` and not `$PREFIX/include/capnp/compat/json.capnp`.
> Fix install location of json.capnp.

- super-test.sh
It turns out that this doesn't really work:
kill %+
wait %+
The problem is, as soon as bash notices that the job has exited, it reaps the job and forgets about it. If this happens before executing `wait %+`, then it will wait for the wrong thing. If there are no other background jobs, then it just fails (probably why I added `|| true`), but if there is some other background job, it'll wait for that, perhaps forever. This seems to be happening with our Cygwin build.
We can fix this by being more specific about which job we're trying to kill and wait for, namely `./calculator-server`. If bash reaps the job too quickly, the `wait` will now just fail since no jobs will match (... one hopes).
> Fix cygwin hang.

- c++/src/kj/mutex.c++
This fixes a failure I observed on my Windows VM at mutex-test.c++:281, in which value.when() was timing out up to 6ms too early.
I preserved the existing behavior in the event endTime is null and the error is ERROR_TIMEOUT. I'm not sure it's correct, though.
> Double check endTime in Mutex::wait() on Windows

- c++/src/capnp/arena.c++
- c++/src/capnp/layout.c++
- c++/src/capnp/message-test.c++
- c++/src/capnp/message.h
- c++/src/capnp/serialize-test.c++
- c++/src/capnp/serialize.c++
- c++/src/capnp/serialize.h
This reverts commit 3aa2b2aa02edb1c160b154ad74c08c929a02512a.
This is not safe, even on x86. Unaligned access is undefined behavior in C/C++. Compilers can and do optimize under the assumption that access is aligned. For example, GCC may use SIMD instructions in optimizations, and these do in fact require alignment. In principle, a compiler could also choose to mask away the lowest bits of a pointer that should always be zero when aligned.
I considered deprecating this class instead of deleting it, but a Google search came up with no mentions of this class anywhere except our own code and issues, suggesting it is not used in any open source code. If it's used in any closed source codebases, then the code's own developers will be the first to see the build breakage and will be …
> Remove `UnalignedFlatArrayMessageReader`.

- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
> Add `KJ_DECLARE_NOT_POLYMORPHIC(T)` to allow `Own<T>` with incomplete types.

- .github/workflows/quick-test.yml
- .github/workflows/release-test.yml
- README.md
Based on @haata's #979, but I changed the badges to show specifically the master branch, and made the actions actually run at master -- including the release tests. It'll be nice to find out when the release tests break without having to explicitly ask for them, but also without having to run them on every PR commit.
> Make actions run at master and power CI badges

- README.md
Since you aren't using Travis-CI and Appveyor anymore, might as well show GitHub Action badges.
One limitation of the GitHub Action badges is that you can only show status at a workflow level (each yaml file).
> Fixing CI badges to use new GitHub Actions.

- doc/language.md
Properly fixes #897.
It turns out Jekyll just doesn't let you render a highlighted code block inside of a list item anymore. It used to, I guess. Probably my `<div>`s were a work-around to make it work before, but at some point that stopped working.
Solution: Manually embed the highlighted HTML.
> Fix markup of code blocks within lists.

- c++/src/capnp/schema.capnp
The first time I learned about Cap'n Proto generics, and again this weekend while trying to relearn them, I spent a long amount of time trying to understand the meaning of `Brand.Scope.inherit`. I found the existing doc comment to be unhelpful: what exactly is a "reference point" and what does it mean to inherit from one?
What finally made things click was to think of `Brand`s as type substitutions, and to think of `inherit` as an identity substitution -- it just replaces the parameters with themselves.
This pull request expands the documentation and adds an example that should make things more clear.
> expand comments for Brand.Scope.inherit

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
This may not be suitable since it requires exceptions to be enabled to use fibers as the new exception type isn't a kj exception.
> Add a seperate CanceledException type for fiber cancelation.

- c++/src/kj/async-test.c++
> Skip test that ticles MinGW 32-bit compiler bug.

- .github/workflows/quick-test.yml
- CMakeLists.txt
- c++/CMakeLists.txt
- c++/cmake/CapnProtoConfig.cmake.in
- c++/configure.ac
- c++/src/capnp/CMakeLists.txt
- c++/src/kj/CMakeLists.txt
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
This PR tries to address #973 and also fix an issue with a header installed to the wrong place.
I tried to compare the install trees generated by autotools and CMake to make sure there was no functional differences.
I see that @harrishancock said he will do the CMake part here https://github.com/capnproto/capnproto/pull/978#pullrequestreview-397491907, but seeing the imminent release, I thought it was worth trying to do it before the release is official, in case the merge window was still open.
My apology if this feels inappropriate.
> Fix/complete CMake installation

- c++/src/kj/encoding.c++
Apparently clang has enabled a warning (`-Wnon-c-typedef-for-linkage`) for when a C-style anonymous struct uses C++ features that make it incompatible with C. We introduced such code in f3e0ed22 when we effectively added a constructor to `base64_decodestate`.  Naming the struct quells the warning.
> kj/encoding.c++: Fix clang warning

- c++/src/kj/encoding.c++
Closes https://github.com/capnproto/capnproto/issues/815.
According to [**char8_t backward compatibility remediation**](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r0.html) I tried to implement `reintrerpret_cast` case:
File [encoding.c++:242](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/kj/encoding.c%2B%2B#L242) was changed:
```
-    result.addAll(StringPtr(u8"\ufffd"));
+    result.addAll(StringPtr(reinterpret_cast<const char *>(u8"\ufffd")));
```
It works for me!
> Fix build for C++20 via reinterpret_cast

- c++/src/kj/async-inl.h
- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
In practice, we've found that Executor is hard to use correctly if it's possible that the target event loop might exit while other threads are still trying to queue things to its executor. This change makes handling that case more graceful. Now, if an event loop exits without completing a cross-thread task, the requesting thread gets a DISCONNECTED exception (instead of hanging forever or crashing). It's also now possible to hold on to an Executor reference beyond the lifetime of the destination thread, and to query whether its event loop still lives.
>  Extend Executor to gracefully handle remote event loop exits.

- c++/src/kj/async-xthread-test.c++
Note that executor disconnects still aren't super-usable when exceptions are disabled as trying to schedule on an executor whose thread is _already_ gone throws a fatal exception. I don't care to put in the effort to fix this because I don't think anyone will use this feature with exceptions disabled. TBH, we should probably define a small subset of KJ/capnp that are expected to work with exceptions disabled and stop trying to test the rest in this configuration...
> Fix -fno-exceptions build.

- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
This abstracts the fiber stack implementation into a separate `FiberStack` class, allowing stacks to be saved and freelisted via `FiberPool`.
> Add freelisting fibers API

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
- c++/src/kj/async.h
Should've been done originally since `FiberPool` is thread-safe.
> Add const modifier to FiberPool::startFiber

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/exception.h
The event loop will use the main stack while sleeping waiting for I/O, but will switch to a FiberPool stack while running event callbacks. Programs with many threads that spend most of their time sleeping can use this to save memory by sharing a small number of "big stacks" when actually executing.
/cc @ObsidianMinor (would set you as a reviewer but GitHub won't let me...)
> Extend event loop to support switching stacks while running callbacks. 

- style-guide.md
Typo in 'No Singletons' section. 
Here is the change, since the diff is multi-line:
`Singleton interfaces ofter turn` -> `Singleton interfaces often turn`
> Doc: fix typo in style guide

- .github/workflows/quick-test.yml
- super-test.sh
Both MinGW and Cygwin builds spontaneously broke in recent weeks for different reasons -- not due to any change to Cap'n Proto, but some external factors.
MinGW seems to have picked up an errant include of `windows.h` which is shitting all over the global namespace and breaking the build.
Cygwin has started hanging after running the calculator demo, just like it used to do on Travis before we switched to GitHub Actions.
> Try to fix new MinGW and Cygwin build failures

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
It turns out HTTP 205 is weird. Like 204 or 304, it can't have a body. But unlike those, it must include headers to indicate a body. The body just has to be empty. So we need to add content-length: 0 to these responses.
Spec: https://tools.ietf.org/html/rfc7231#section-6.3.6
> HTTP 205 responses must have content-length: 0

- c++/src/capnp/reconnect-test.c++
- c++/src/capnp/reconnect.c++
- c++/src/capnp/reconnect.h
- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.h
Sandstorm has had hackier versions of these for a long time, but lots of Cap'n Proto applications will need these, so I went and wrote clean versions in capnp itself.
@a-robinson
> Utilities for handling network disconnects

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.h
Rather than synchronously the first time and async the second, which
makes it tougher to deal with locks.
Minor follow-up to #1017
> Make retryOnDisconnect call the provided func asynchronously both times

- c++/src/kj/time.c++
clang-cl rightly points out that the const in its current spot doesn't
do anything as it's applying the const to the function type. Instead
make the pointer itself const which is what's intended.
> Fix ignored qualifier

- c++/src/kj/async-inl.h
clang-cl warns about this as a Microsoft extension:
```
async-inl.h(922,16): warning: unqualified friend declaration referring
to type outside of the nearest enclosing namespace is a Microsoft
extension; add a nested name specifier [-Wmicrosoft-unq
ualified-friend]
friend class WaitScope;
^
::kj::
```
> Fix unqualified friend declaration

- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/mutex.h
Not supported on Windows since slim rw locks don't support timeouts.
> Add lock timeout support to MutexGuarded

- c++/src/capnp/any-test.c++
- c++/src/capnp/any.h
- c++/src/capnp/common.h
- c++/src/capnp/compat/json.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/generated-header-support.h
- c++/src/capnp/layout.c++
- c++/src/capnp/raw-schema.h
- c++/src/capnp/schema-loader.c++
- c++/src/capnp/schema.capnp.c++
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/common.h
- c++/src/kj/debug-test.c++
- c++/src/kj/debug.h
- c++/src/kj/exception-test.c++
- c++/src/kj/filesystem-disk-win32.c++
- c++/src/kj/parse/char.h
- c++/src/kj/refcount.c++
- c++/src/kj/refcount.h
- c++/src/kj/string.c++
- c++/src/kj/table.c++
- c++/src/kj/table.h
- c++/src/kj/test.h
- c++/src/kj/thread.c++
- c++/src/kj/tuple.h
clang-cl defines a really old version of _MSC_VER which trips up some of
the version detection and also would trigger unnecessary workarounds
that clang is able to handle.
Additionally remove a MSVC 2015 workaround since 2017 is the minimum
version anyway.
Audit all _MSC_VER usage throughout codebase to try to handle it
correctly. There are still places that access _MSC_VER when they
probably mean to check if building for Windows - those places are
untouched.
Not sure how to integrate this into automated build support. Will be testing it
on my own build farm but I don't run the capnp unit tests so there could be a potential
gap there.
> Improve clang cl support

- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/parser.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/serialize-async-test.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-win32.c++
- c++/src/kj/async-win32.h
- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/debug.c++
- c++/src/kj/exception.c++
- c++/src/kj/filesystem-disk-win32.c++
- c++/src/kj/io.c++
- c++/src/kj/main.c++
- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/time-test.c++
- c++/src/kj/time.c++
- c++/src/kj/win32-api-version.h
External build systems may override the minimum windows version when
building to be even newer than Vista. Fix the conflict so that if the
macro is a baked-in parameter for the compiler invocation that
everything still builds.
> Fix Windows version friendliness with external build

- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
- c++/src/capnp/compat/json.h
Hi kentonv,
I would like to propose the attached change to libcapnp-json. It adds an opt-in flag to make JsonCodec's decoding fail when encountering unknown fields.
My use case, which I believe requires this change, involves a tool for preserving/archiving an inbound JSON data stream in Cap'n Proto's wire format. A failure scenario exists where a client is changed to provide data not yet known to the archival tool (and thus not yet approved by the archive owner). Given my philosophy of "fail early", I would like the tool to reject messages unless it is sure that no data is lost in the conversion process. Forward compatibility is of insignificant importance compared to a risk of data loss or maintenance cost of storing inbound data in multiple formats.
An alternative to this change would …
> Add option to reject decoding of JSON messages with unrecognized fields

- c++/src/capnp/compat/json.c++
I noticed that json.c++ references unneeded headers for strtod, which is no longer used directly. This merge request removes the obsolete includes.
> Remove obsolete strtod includes from json.c++

- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
In the event that detached promises are used (which is highly discouraged!), they need to be destroyed before disconnecting the executor. Otherwise, if any detached promise is waiting on a cross-thread event, the target thread will abort when it can't reply to the calling thread.
> Fix destruction order in EventLoop.

- c++/src/kj/async.c++
This can prevent issues where `drain` is called and the promise is destroyed, preventing further `drain`s from being done.
> Check if fufiller is waiting before asserting that the fulfiller exists

- c++/src/capnp/reconnect-test.c++
This is a bug in the test, not in the code it is testing.
> Fix use-after-free in reconnect-test.

- c++/src/kj/one-of.h
MSVC seems to be having a tough time dealing with the `->template get<>()` syntax inside the initial `for` declaration.
Fixes #1041.
> Work around VS2019 ICE in KJ_CASE_ONEOF()

- c++/src/kj/async-io-unix.c++
SocketAddress::socket() has long (since 2013) put newly created socket streams into
TCP_NODELAY mode to get around the performance problems caused by the
combination of capnproto making a lot of small writes and Nagle's
algorithm not playing nicely with all those small writes.
I've found that when using capnproto over high latency links it's
important to also set TCP_NODELAY on the server side, since the server
can make lots of small writes as well, and without this an extra TCP
round trip can often be needed for the client to ack the server's first
packet before the server's second packet is sent (and thus before the
client can start doing any useful work).
It's very possible there's a better place to put this, but this works and as far as I can tell all sockets handled here are indeed …
> Set TCP_NODELAY on servers as well as on clients

- c++/src/kj/compat/readiness-io-test.c++
- c++/src/kj/compat/readiness-io.c++
- c++/src/kj/compat/readiness-io.h
- c++/src/kj/compat/tls.c++
This is a bit hacky, but it's a quick fix that makes a noticeable
difference in the number of small packets we send over the wire,
especially now that TCP_NODELAY is enabled on the server side.
If you'd prefer a different approach, let me know.
I also added a tiny little second commit that's mostly unrelated, which I can remove if you don't care about it.
> Combine small writes together in TLS compatibility layer

- c++/src/kj/compat/http.c++
https://godbolt.org/z/nP5fcc
```
In instantiation of 'static constexpr bool FastCaseCmp<first, rest ...>::apply(const char*) [with char first = 'f'; char ...rest = {'O', 'o', 'B', '1'}]':
<source>:25:38:   required from 'constexpr bool fastCaseCmp(const char*) [with char ...chars = {'f', 'O', 'o', 'B', '1'}]'
<source>:29:47:   required from here
<source>:11:29: error: bitwise comparison always evaluates to false [-Werror=tautological-compare]
11 |         ? (*actual & ~0x20) == first && FastCaseCmp<rest...>::apply(actual + 1)
|           ~~~~~~~~~~~~~~~~~~^~~~~~~~
```
> fastCaseCmp: workaround gcc -Wtautological-compare

- c++/src/kj/async-io-unix.c++
- c++/src/kj/common.c++
- c++/src/kj/common.h
- c++/src/kj/debug-test.c++
- c++/src/kj/debug.c++
- c++/src/kj/one-of-test.c++
This change cleans up compiler output when building capnproto in a project that is using clang with `-Wunreachable-code`.  I'm not sure if there is a cleaner way to do this, or one that could be applied to more compilers.
(Since these are `#pragma`s, I assume there's no way to substitute them via macros, so I assume we'd otherwise have to resort to tiny `#include` files, which seemed kind of messy?)
> Disable clang unreachable code warnings for known-unreachable code

- c++/src/capnp/CMakeLists.txt
when installing capnp to a non-standard location (out of `/usr` or `/usr/local`), the `capnp compile` must be issued with the `-I` option even for the standard `/capnp/c++.capnp` import. Some projects that use `capnp compile` directly, not via cmake (e.g. [capnproto-java](https://github.com/capnproto/capnproto-java/blob/b60bc1e7148893ad584e369b7bd3c1717f1d2cb0/compiler/pom.xml#L87)) cannot be built in this configuration.
> cmake: set CAPNP_INCLUDE_DIR

- c++/src/capnp/serialize-text-test.c++
- c++/src/capnp/serialize-text.c++
The error messages always started with `kj::str(message, " (", startByte, ":", endByte, ").") =` due to the use of KJ_FAIL_ASSERT. This garbage clearly wasn't intended to be part of the error message.
I also went a little further and computed the line number and column numbers, which is usually nicer than a byte span.
> Fix TextCodec parse error formatting.

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/async.h
Additionally, the documentation for the bool result from Canceler.isEmpty was reversed.
---
All credit to @harrishancock
> Fix canceler.isEmpty() check in http-over-capnp

- doc/encoding.md
Fixes #1085.
This is what the implementation already does, and you can make the
argument that it is implied by the previous description, but this makes
it unambiguous.
> Clarify canonicalization behavior on zero-sized values.

- c++/src/capnp/reconnect-test.c++
- c++/src/capnp/reconnect.c++
- c++/src/capnp/reconnect.h
It still reconnects eagerly, but not establishing the initial connection
until the first time the capability is used is nice for capabilities
that are expensive to set up but often not used.
> Add lazy option to autoReconnect to avoid connecting until used

- c++/src/kj/common.c++
- c++/src/kj/common.h
I noticed the comments around this when at work today and (because of reasons\*) I wanted to look into it a little more when I got off of work (as it's irrelevant to my actual job).
Recent MSVCs support a handful of clang/gcc-like `__builtin` functions so I figured I'd check, and it seems these two are totally supported, even as far back as libkj's min supported MSVC version (_MSC_VER >= 1910 is checked elsewhere in common.h). Godbolt proof that it works on that old of a MSVC: https://gcc.godbolt.org/z/7q6rsn
This simplifies and reduces the amount of code (compiler-specific code no less), and removes another use of the c++ stdlib (which appears to be one of libkj's aspirations).
The drawback is that I... can't find much in the way of docs about MSVC supporting these... I could have sworn …
> Support constexpr `kj::nan()` under MSVC

- c++/src/capnp/compiler/capnp-test.sh
src/capnp/compiler/capnp-test.sh was failing `make check` for me when building in an out-of-source build. This fixes that.
> Fix for `make check` in an out-of-source build directory

- super-test.sh
IIRC c++1y should hit some draft of C++14, perhaps the relatively trivial fix is worthwhile?
> Cleanup: rewrite c++1y to c++14

- c++/src/capnp/capability-test.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/generics.c++
- c++/src/capnp/test.capnp
- c++/src/capnp/testdata/errors.capnp.nobuild
- c++/src/capnp/testdata/errors.txt
This is hoping to solve #1089. This time I managed to get to a point where it works for me, with a small example using a list of capabilities defined as:
```
fetchCapabilities @0 () -> (caps :List(Capability));
```
With those changes, I can pass a list of capabilities through `fetchCapabilities` by modifying the calculator example, and it works. I finally realized that I should handle the `AnyPointer` type further in the pipeline. I was first trying to do that in `schema.h`, but I think that it did not work because an `Unconstrained::Capability` is not an `InterfaceSchema`, though both are `INTERFACE`s in the end.
Resolves #1089.
> Add support for List(Capability)

- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
Consider this situation:
* Client makes call to server.
* The server method tail-calls back to a capability hosted by the client.
* While the server is doing this, the client cancels the original call.
In this situation, the server ends up sending the client messages saying "start this new call, and then use the results to satisfy this other outstanding call you made to me".
However, in the case where the client has already canceled the original call, the code failed to clean up properly. As a result, it ended up never sending a return message for the server -> client call. This would leak some resources, especially including the RPC object to which the tail call was directed on the client side.
In addition to this bug, cancellation was not propagated correctly through these tail calls. …
> Fix leak when an RPC tail call is canceled.

- c++/src/kj/mutex.c++
mutex code uses SYS_futex, which it expects from system C library.
in glibc (/usr/include/bits/syscall.h defines it in terms of of NR_futex)
rv32 is using 64bit time_t from get go unlike other 32bit architectures
in glibc, therefore it wont have NR_futex defined but just NR_futex_time64
this aliases it to NR_futex so that SYS_futex is then defined for rv32
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> mutex: Fix build on 32-bit architectures using 64-bit time_t

- c++/src/kj/async.c++
I wasn't sure what the message should actually say...
> Change Canceler's default exception type to DISCONNECTED

- c++/src/capnp/encoding-test.c++
- c++/src/capnp/list.h
These should be using `Orphan<List<T>>`, not `Orphan<T>`.
A bug as old as time, apparently.
I noticed this while reviewing #1112.
> Fix `List<List<T>>` `adopt()` and `disown()`.

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
- c++/src/kj/async.h
The old Event::trace() in particular was nonsense -- it didn't actually trace back to the next event and so on, instead it would trace _forwards_ through `PromiseNode`s.
Additionally, the output of the old traces was not particularly useful, as it would tell you the types of the promises but not line numbers.
The new tracing code produces a list of instruction addresses, just like regular stack traces. It can be passed into all the regular stack tracing tools.
Additionally, a new global function `kj::getAsyncTrace()` gets a trace of the promises leading up to the currently-executing code. Previously, such traces were generated when you threw an exception and it actually passed through the promise chain, but there was no way to get a meaningful async trace e.g. in a crash handler. Now …
> Redesign async trace code

- c++/CMakeLists.txt
Paths defined in `CMAKE_MODULE_PATH` by callers are lost with current CMakeLists. Best practice is to always append new values in CMAKE_MODULE_PATH. For conan package manager, it leads to issues because it injects specific paths in this variable.
> CMake: append cmake folder into CMAKE_MODULE_PATH instead of set

- c++/src/capnp/compat/byte-stream-test.c++
CI failed to catch this because... apparently this code isn't covered by Makefile.am currently. But this broke the build of Ekam.
> Fix use of C++17 features in byte-stream-test.

- c++/src/capnp/compat/byte-stream-test.c++
Turns out the test was not initializing its test string, and only actually worked when the string was full of zeros, due to another typo in the test.
> Fix byte-stream-test harder.

- c++/src/kj/filesystem-disk-unix.c++
Android got both fallocate and posix_allocate only in API 21. For this reason there is no way to get os-asisted file zeroing.
> Do not use fallocate on Android API < 21

- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/kj/debug-test.c++
- c++/src/kj/debug.c++
- c++/src/kj/debug.h
- c++/src/kj/filesystem-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
- c++/src/kj/test.h
When `KJ_ASSERT(foo == bar)` fails, `foo` and `bar`'s actual values will be stringified in the error message. How does it work? We use template magic and operator precedence. The assertion actually evaluates something like this:
if (auto _kjCondition = kj::_::MAGIC_ASSERT << foo == bar)
`<<` has operator precedence slightly above `==`, so `kj::_::MAGIC_ASSERT << foo` gets evaluated first. This wraps `foo` in a little wrapper that captures the comparison operators and keeps enough information around to be able to stringify the left and right sides of the comparison independently. As always, the stringification only actually occurs if the assert fails.
You might ask why we use operator `<<` and not e.g. operator `<=`, since operators of the same precedence are evaluated left-to-right. The …
> Implement magic assert stringification.

- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
- c++/src/capnp/membrane.c++
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/test-util.c++
- c++/src/capnp/test-util.h
- c++/src/capnp/test.capnp
This makes it possible, when an RPC forwards to another RPC, to start forward pipelined calls on the first to the second, before the first RPC actually completes.
> Introduce CallConetxt::setPipeline().

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc.c++
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
This makes it easier to figure out why RPC became disconnected, based on having the exception thrown at you later when you try to use the connection.
> Retain stack traces on exception thas disconnect the RPC.

- c++/src/kj/async.c++
This `static_cast` is casting the value to the type it already is. I think it may have been a copy-pasto from a version of the code that actually had to do a downcast here.
This is just something I noticed while reading. This change has absolutely no effect on actual behavior.
> Remove a redundant static_cast.

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc-twoparty.h
Historically we assumed that any write failure on the underlying socket would probably manifest as a read failure at the same time, but this is not necessarily true in practice, especially with exotic socket types like kTLS.
> In rpc-twoparty, propagate write failures to read failures.

- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-io-unix.c++
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/io.c++
- c++/src/kj/miniposix.c++
- c++/src/kj/miniposix.h
On platforms that need iovMax to be queried via sysconf, iovMax
does an unnecessary syscall on every call to `iovMax`. This value isn't
going to change during runtime though. Move this to a constant that's
initialized only once and remove the `count` argument into iovMax since
it's actually superfluous to the API. The more correct action is to just return
`std::numeric_limits<size_t>::max()` and let the caller figure out what
the value is.
Open question is whether this should be just an implementation detail of
`iovMax` (i.e. hide the lazy initialization of the runtime value there) or to
make it the responsibility of the caller. My personal preference is to hide
it within `iovMax` but figured that may be more controversial.
> Minor speedup for miniposix::iovMax

- c++/src/capnp/serialize-async-test.c++
- c++/src/capnp/serialize-async.c++
- c++/src/capnp/serialize-async.h
- c++/src/kj/async-io.h
In order to support batching up some of the small writes that capnproto
tends to do in practice when you're sending lots of pipelined RPCs.
---
This could use unit tests, and perhaps should also have versions of the methods added onto the `MessageStream` type, but I wanted to get your feedback on the core approach before going the rest of the way.
> Add writeMessages for serializing multiple messages to an output stream

- c++/src/kj/async-io.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/test.h
This way we don't have to parse each frame that passes through.
> Optimise WebSocket pumps between raw streams to a raw stream pump.

- c++/src/capnp/stringify.c++
- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/encoding.h
Adjust encodeCEscape() to generate encoding that is compatible with utf-8 which is used in python3 when presented with a binary blob, which means escaping upper half of the code space. Without this attempt to make printable representation of the valid otherwise binary data in python would sometimes fail with something like this:
```
Traceback (most recent call last):
File "./tools/lib/logreader.py", line 147, in <module>
print(msg)
File "capnp/lib/capnp.pyx", line 1092, in capnp.lib.capnp._DynamicStructReader.__str__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 118: invalid start byte
```
The structure in question is:
```
struct CanData {
address @0 :UInt32;
busTime @1 :UInt16;
dat     @2 :Data;
src     @3 :UInt8;
}
```
The data:
```
( logMonoTime = …
```
> Pretty-print binary blobs (aka Data) properly.

- c++/src/kj/async-io.c++
This seems like the easiest way to get it to stop showing up in our error logs when Workers don't write as much data as they promised.
> Change exception for 'pipe ended prematurely' to DISCONNECTED.

- c++/src/kj/compat/http.c++
For Workers, our ingress proxy should already be guarding against oversized headers, but we're seeing a trickle of errors, probably because of internal headers that have been added to the request after the early check.
> Bump max header size 64k -> 128k.

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
This is useful when creating an array of an immovable type, where the constructor takes one parameter.
I don't actually need this for anything. I thought I did, but then it turned out I didn't. But I wrote it and it seems useful.
> Add `kj::arrOf<T>()`, similar to `kj::arr()` but with explicit type.

- doc/index.md
Based on archive.org, this link has been broken since ~2017.
The latest archive.org link with a redirect that I found directs to https://code.google.com/p/protobuf/ which in turn redirects to http://github.com/google/protobuf
> Fix link to Google protobuf

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This allows for the usage of named / reusable lambdas with `kj::defer()`, which is especially helpful in testing functions.
> `kj::defer`: allow lvalue lambda reference

- c++/src/kj/compat/url.h
- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/encoding.h
- c++/src/kj/filesystem.h
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
- c++/src/kj/units-test.c++
- c++/src/kj/units.h
The biggest issue is that C++20 greatly expanded the overload search space for comparison operators. In particular, when evaluating `a == b`, C++20 will now look for overloads for both `a == b` and `b == a`. If it finds matches for both, with no reason to think one is "better" than the other, it will pronounce them ambiguous and error out!
This turns out to play very poorly with implicit conversions. If you have two types that can implicitly convert to each other (including two specializations of the same template), and both of them implement `operator==`, then you can no longer compare type A against type B, because the compiler can't decide whether to convert A to B or B to A. (Previously, it was always the right-hand side of the comparison that would be converted.)
It turns out this is …
> Fix build with C++20.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
This is redundant, we obviously already know that `protocolError.description` describes an error. If the error is going to be rendered somewhere else where that's not otherwise obvious, then whatever is doing the rendering should add the prefix.
> Don't add 'ERROR:' prefix to every protocol error description.

- c++/src/capnp/rpc-prelude.h
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.h
This allows users of the RPC system to detect when the accept loop stops
for some reason.
---
An alternative would be to have people manually start the RPC system and own the actual promise. It was a bit surprising to me (but not necessarily bad) that the system runs itself on construction.
> Expose RpcSystemBase's accept loop promise

- .github/workflows/quick-test.yml
- c++/src/kj/async.c++
- c++/src/kj/exception.h
We give this the same treatment as we did PromiseFulfillerPair: If a `Canceler` is canceled because it is simply destroyed, we propagate the in-flight exception if there is one, otherwise we produce an exception that includes a stack trace to the destructor, in addition to the trace to the canceled operation.
> Create better exceptions when default-canceling a `kj::Canceler`.

- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
For use cases that fit, this should be significantly easier to use, and also perform better, than `Executor` has been.
> Implement `newCrossThreadPromiseFulfiller()`.

- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
(This turns these into application-visible errors in CF Workers, rather than internal errors.)
> Report WebSocket handshake errors via HttpClientErrorHandler.

- c++/src/kj/async.c++
- c++/src/kj/exception.c++
When I previously factored out `getDestructionReason()` from `WeakFulfillerBase::disposeImpl()` (in #1176), I had intended to move it to `exception.c++`. I even declared the prototype in `exception.h`. But I forgot to move it.
This PR just moves the code without changing anything else.
> Move `getDestructionReason()` to correct file.

- c++/src/kj/exception.c++
> Actually use defaultFile and defaultLine passed to getDestructionReason().

- c++/src/kj/exception.c++
Prior to these changes, using KJ_CLEAN_SHUTDOWN results in the following error:
```
failed: unknown non-KJ exception of type:
kj::TopLevelProcessContext::CleanShutdownException
```
> [WIP] fix `KJ_CLEAN_SHUTDOWN` behavior

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This has come up before as something people (me) didn't expect. I _think_ the consensus was:
* You shouldn't try to use a moved-out-of-object
* ...but leaving the moved-out-of Maybe in a valid state for things like `int` is a foot gun for people who expect it be left "empty" after a move
It's a bit scary since this is technically backward incompatible...
> Leave Maybe<T> empty after its contents are taken by another Maybe

- c++/src/capnp/compiler/module-loader.c++
Multiply signed by unsigned number would get unsigned.
```
$ capnp_tool compile -oc++ a20.capnp base.capnp
../third/capnproto/c++/src/capnp/compiler/module-loader.c++:118:65: runtime error: signed integer overflow: 1613965689944811244 * 73 cannot be represented in type 'long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../third/capnproto/c++/src/capnp/compiler/module-loader.c++:118:65 in
```
> Undefined behavior sanitizer on FileKeyHash()

- c++/src/kj/async.c++
This causes a lot of unnecessary backtraces.
Regression was introduced in #1176.
> Fix dumb performance regression.

- c++/src/kj/async-unix.c++
sigemptyset isn't guaranteed to clear the structure to a level where a
byte-level comparison is safe (e.g. padding, unused fields, etc).
Explicitly 0-initialize the structs before comparison.
This was found by running async-unix-test under valgrind 3.16.1 on Arch
running 5.10.23-1-lts and glibc 2.33. Didn't happen always, but like
80-90% of the time. After this change confirmed that valgrind doesn't
complain about use of uninitialized memory.
> Make sigset safe to use in memcmp

- c++/src/kj/debug-test.c++
- c++/src/kj/debug.c++
- c++/src/kj/exception.c++
It seems that the mechanism for capturing logs in the logging tests also ate
the exceptions that the asserts rely upon, so many of the test assertions had
no effect.
> Fix logging tests, context filename trimming

- c++/src/capnp/compiler/node-translator.c++
The "holes" array tracks the location of padding in the layout of a struct's data section. At any time, there can be at most one hole of each power-of-2 size up to 32 bits: 1-bit, 2-bit, 4-bit, 8-bit, 16-bit, 32-bit. The algorithm never creates more than one hole of any size: a new hole only needs to be created as the result of splitting a larger hole in order to allocate space for a field of the same size or smaller, but if a hole already exists, then the existing hole would just be used.
Hence, we end up with a holes array of size 6.
`HoleSet::tryExpand()` attempts to expand an existing non-hole of a particular size by merging it with holes appearing immediately after it. This can be needed in particular when allocating fields that are part of groups nested within unions -- it's …
> Fix OOB array access in compiler.

- c++/src/kj/one-of.h
Follows the work done in e475d03, just with even more variants supported.
> Extend OneOf to support 20 variants.

- c++/src/kj/debug-test.c++
- c++/src/kj/debug.c++
Omits the value label when the logged expression starts with `kj::str(`, mimicking the handling of literal strings.  This gives us a way to log dynamic content without including an expression label.
Of course, this is not foolproof... Doing something like `KJ_DBG(kj::str("yes") == "no");` will just log `false`.  But of course, the current handling of literal strings has the same drawback.
> Omit label when logging kj::str(...) expression parameters

- c++/src/capnp/arena.c++
- c++/src/capnp/arena.h
Under a certain workload TSAN will complain about ReadLimiter which is a
false-positive signal per the class comments. Switch to relaxed atomics
because they should make TSAN happy while not altering the performance
characteristics of what we were doing.
> Fix TSAN unhappiness

- .github/workflows/quick-test.yml
- c++/src/kj/async.c++
Fix for #1209, and also CI issue identified in #1025.
VS2017 apparently doesn't properly coerce from nullptr, and it was difficult to solve this in the __atomic_exchange_n macro since the VS2017 template engine didn't seem capable of template deduction either.
> Fix for VS2017 Builds and CI.

- c++/src/kj/async-inl.h
- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
* Rename newCrossThreadPromiseAndFulfiller -> newPromiseAndCrossThreadFulfiller.
At least one user of this interface did not realize that it's only the fulfiller that is cross-thread-safe, no the promise. Hopefully this helps.
* Define CrossThreadPromiseFulfiller with a const interface.
This further helps people understand that the fulfiller is cross-thread but the promise is not. It's also helpful for people who are using cross-thread fulfillers in code that uses `const` for checking thread safety, as KJ style recommends.
> Tweak cross-thread promise fulfiller interfaces

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.h
I ended up not needing this, but figured I'd merge the code anyway in case it's useful in the future.
> Add `ForkedPromise::hasBranches()`.

- c++/src/kj/table-test.c++
- c++/src/kj/table.h
So this is embarassing... the size of a HashIndex would grow more-or-less with the number of insertions, even if most inserted items were removed later.
Fixing this not only fixes the memory leak, but makes the benchmark 30% faster. When compared to unordered_map, HashMap goes from being 66% faster to being 116% faster.
> Fix HashIndex memory leak when doing lots of erasures.

- c++/src/capnp/compat/websocket-rpc.c++
The error is:
websocket-rpc.c++:103:26: error: no matching constructor for initialization of 'kj::ArrayPtr<kj::ArrayPtr<const kj::ArrayPtr<const word>>>'
Bizarrely, the error only seems to manifest with certain compiler flags. It happens in our (CF Workers) debug build, but not our release build. And it didn't happen in Cap'n Proto's own CI.
/cc @zenhack
> Fix build error in websocket-rpc.c++.

- c++/configure.ac
- c++/pkgconfig/capnp-websocket.pc.in
I didn't test the new capnp-websocket.pc.in, just copied and modified capnp-json.pc.in. Note that the CMake build enumerates over all its targets to find .pc.in files, meaning adding a target without a corresponding .pc.in file breaks the CMake build, which is how I noticed.
> Add pkgconfig/capnp-websocket.pc.in

- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/compat/tls.c++
To enable users of IO streams that correspond to underlying sockets to
use the sockets directly for special cases.
I didn't bother providing an implemention that returns non-null on
AsyncPipe or any of its variants, but let me know if you think I should.
I also didn't add a similar method to ConnectionReceiver and its
child classes given I don't have any particular need for it, although
you could easily put one there as well.
> Add a getFd() method to AsyncIoStream

- c++/src/kj/hash.h
I assumed we wanted this done with compiler intrinsics rather than using `type_traits`?
> add hashcode implementation for enums

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This makes it consistent with what other `Maybe` types do.
> Auto-nullify `kj::Maybe<T&>` after moving away.

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/common.h
Add copyOrAddRef specialization for `Maybe<Own<T>>` to make this compatible with `ForkedPromise`.
An open question is whether `addRef` should be allowed to change the returned type.
I don't think that's true for `Own<T>` so I kept it consistent, but I thought I read some documentation somewhere
where `addRef` is supposed to allow to transmute to `Own<U>` (in which case there's a bug here).
> Make Maybe<Own<T>> compatible with ForkedPromise

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/http-over-capnp.h
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
This allows users of the code to build the header table earlier than construction of the factory.
> Refactor: Move header table building out of HttpOverCapnpFactory's constructor

- c++/src/kj/string.h
When CMake passes MinGW `-std=gnu++2a`, then MinGW GCC defines `__cplusplus` as `201709L` even though C++20 features are active. This causes Cap'n Proto's conditional compilation to think the compiler is in C++17 mode, despite the compiler running in C++20 mode, resulting in build errors (in the case of `char8_t`) or miscompilations and infinite recursion (in the case of `operator==`).
MSVC is even worse, since it unconditionally reports __cplusplus = 199711L, unless you pass in /Zc:__cplusplus in addition to /std:c++xyz ([source](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/)).
This pull request feature-tests C++20 features by name (rather by compiler version) when conditionally compiling code based on those features. This PR fixes "kj/string.h" and makes …
> Fix String/StringPtr compilation on MinGW/MSVC C++20

- c++/src/kj/async-io-test.c++
Saw an EADDR in use failure in CI for this test.
> Use unique Unix address for test.

- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
It's useful for the caller to be able to validate whether it's a valid
header value in case they want to handle such a situation a different
way.
> Expose isValidHeaderValue in HttpHeaders

- c++/src/capnp/CMakeLists.txt
CMake versions >= 3.13 make use of Windows support for symlinks;
previously `cmake -E create_symlink` was a no-op. However, symlinks
are only available in Windows 10 > build 1607 with developer mode
enabled. Otherwise, the install step fails with:
```
EXEC : CMake error : failed to create symbolic link 'C:/bld/capnproto-build/install/bin/capnpc.exe': operation not permitted
```
This commit checks the error status of the create_symlink install
command, and reports failure as a warning but does not error out.
> Turn create_symlink failure on Windows into a warning

- c++/src/kj/compat/tls.c++
- c++/src/kj/compat/tls.h
- c++/src/kj/memory.h
This adds a new required constructor argument (a `Timer`) to `TlsContext`... if we want to prevent breaking existing code I could get cute and make it optional and throw an error if you try to use `acceptTimeout` without it?
> Add 'acceptTimeout' option to TLS

- c++/src/kj/async-io-unix.c++
This is unlikely to be particularly useful, but I'll take what I can
get in case it helps illuminate any patterns in our errors.
> Add a bit more detail on writev errors in AsyncStreamFd::writeInternal

- c++/src/kj/async.c++
The effect of this bug is that a chunk of an async trace would be lost. For example, say you have:
promise.then(foo).then(bar).then(baz).fork().then(qux);
Say that `foo` returns a promise, but `bar` and `baz` do not (they are simple transformations). In this case, the async trace would fail to report `bar` and `baz` -- it would trace directly from `foo` to `qux`.
> Fix async tracing through ForkedPromise.

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
This perhaps isn't the ideal API, but does at least offer a way to get
at underlying control messages if you really care about them.
> Support registering interest in ancillary messages on AsyncIoStream

- c++/src/kj/parse/common.h
"kj/parse/common.h" currently special-cases MSVC to use `std::result_of_t`, but it was removed in C++20. Consequently, if you try compiling with MSVC 2019 in C++20 mode, the build fails because the variable is not found. However, I can't easily test if `result_of_t` was removed, because on MSVC, `__cplusplus` is always `199711L`, and the removal has no corresponding feature flag.
This PR removes the special case for MSVC. The resulting code compiles successfully in the latest MSVC shipping with VS2019, and no longer results in a C2064 error. Testing older MSVC versions on Godbolt, it also successfully compiles on MSVC 19.10 (VS2017, the earliest supported version) and newer. Nonetheless it's possible that that specific older versions of VS2017 not on Godbolt will fail to build.
Fixes …
> Fix kj/parse/common.h not compiling in MSVC's C++20 mode

- c++/src/kj/array.h
- c++/src/kj/common.h
- c++/src/kj/string.h
- c++/src/kj/vector.h
Annotate `Array`/`ArrayBuilder`/`Vector`/`String` with `[[clang::lifetimebound]]` so that the compiler will warn if the lifetime of the used variable exceeds the lifetime of the underlying storage.
Unfortunately I don't think there's a way to track the lifetime bound through multiple objects (e.g. kj::Array -> kj::ArrayPtr -> slice into a new kj::ArrayPtr).
> Annotate lifetimebound

- .github/workflows/quick-test.yml
- c++/Makefile.am
- c++/src/kj/CMakeLists.txt
- c++/src/kj/common.h
- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/mutex.h
- c++/src/kj/source-location.c++
- c++/src/kj/source-location.h
- c++/src/kj/string.h
- kjdoc/tour.md
- super-test.sh
This adds two tracking operations:
* Async signal safe TLS variables to track when a thread is blocked on a lock primitive.
* Per-mutex contextual information pointing to the locked mutex.
These should be sufficient for deadlock detection with the notable exception that I don't know what to do about shared mutexes. By their very nature, I can only track one random acquisition point. If a shared mutex is part of a deadlock chain, it can't be found. To try to track that data seems cost-prohibitive: needs some kind of array per mutex & maybe hope that lock acquisition/release can be reflected with atomics (otherwise it also implies an acquisition of an exclusive mutex to record the TID holding the shared lock).
I added a `kj::SourceLocation` object when building against c++20 since all …
> Mutex tracking

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc-twoparty.h
This is another useful metric for backpressure, when protecting against queued message latency is important as well as protecting against arbitrary memory growth due to an unbounded amount queued message.
I'd have liked to use `kj::List`, but with only a forward declared `OutgoingMessageImpl` getting the pointer-to-member attribute wasn't possible. I'd appreciate advice if there's a way to get around this without polluting the header.
> Add oldestQueuedMessage metric to TwoPartyVatNetwork

- c++/src/capnp/CMakeLists.txt
Current implementation might produce the following CMake error:
```
CMake Error: failed to create symbolic link ...: operation not permitted
```
> Make cmake install more portable on windows

- c++/src/kj/async.c++
- c++/src/kj/common.h
- c++/src/kj/exception.c++
Fix the ASAN problem with RootExceptionCallback by intentionally leaking the pointer.
Fix the apparent leak in FiberPool::Impl (verified that kj/async-tests now pass).
Attempt a cleanup of the TODO in macros.h about RTTI/C++ exceptions. This one is
more "cause I had the macros & wanted to take a stab". Purely cosmetic & can easily
drop it from the stack if there's any concern.
> Sanitizer fixes

- c++/src/capnp/arena.h
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async.c++
- c++/src/kj/common.h
- c++/src/kj/compat/gzip.h
- c++/src/kj/exception.c++
Recommended when building with -Wmissing-noreturn. Unfortunately the
warning isn't quite as helpful as one might like. Ideally it would only
warn about functions with external linkage - I would expect that the
optimizer should be responsible for figuring out the "noreturn"-ness of
functions with internal linkage... Still, maybe not a bad idea for us to annotate
these functions correctly to allow for turning on the warning downstream.
> Add missing [[noreturn]] annotations

- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/compiler/compiler.c++
- c++/src/capnp/compiler/generics.c++
- c++/src/capnp/compiler/node-translator.c++
- c++/src/kj/common.h
- c++/src/kj/encoding.c++
- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/filesystem-disk-win32.c++
- c++/src/kj/hash.c++
- super-test.sh
This allows the code to compile with -Wimplicit-fallthrough on both GCC and Clang. Note that Clang's version of the warning doesn't seem to accept comments the way GCC's does (or I couldn't figure out how to make a comment that it accepted), so I am using the explicit annotation everywhere instead. Technically this annotation wasn't recognized until C++17, but GCC seems to accept it with C++14. I'm hoping the others do to (we'll see what CI says), otherwise I'll need a KJ_FALLTHROUGH macro I guess.
> Annotate all fallthroughs.

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/websocket-rpc-test.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
~~The functions send(), close(), disconnect(), pumpTo() and tryPumpFrom() are modified to return a promise for the number of bytes sent by the respective operations.~~
~~One possible problem with this approach is that if the promise after bytes, we'll lose the count. I wonder if it might be better to store the bytes sent as some field on the WebSocket object itself.~~
Updated the PR to add new methods to the WebSocket interface for returning the number of bytes sent and received. This is still quite a work in progress. Issues:
1) The accounting in::receive() isn't right. It looks at the payload length in the header, but doesn't work if the sender disconnects before sending the entire payload. This is why the new test is currently failing. I haven't figured out exactly how to count …
> Add methods to WebSocket to return bytes sent and received

- c++/src/kj/async-queue-test.c++
- c++/src/kj/async-queue.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
This does the following:
- Adds a new general function ConnectionReceiver::run() to facilitate an async accept loop.
- Adds a queue and a TaskSet to the TlsConnectionReceiver to accept on its inner ConnectionReceiver without blocking on SSL_accept().
- Adds several new tests for the TlsConnectionReceiver.
- Converts several other TLS tests to use convenience helpers.
> Accept TLS connections in their own loop

- c++/src/kj/table-test.c++
- c++/src/kj/table.c++
- c++/src/kj/table.h
Previously, copying of B-Tree table indexes was incorrectly allowed (and
broken) and moving them was also similarly broken.
Specifically, there were two different sources of bad behavior:
* If you copied or moved a B-Tree index, its underlying `tree` memory
would be freed multiple times.
* And if you assigned one B-Tree index over top of another, the target
of the assignment would fail to free its underlying `tree` memory.
I found this when debugging a recently-added memory leak involving a
Table with a TreeIndex stored within an `ExternalMutexGuarded`. The
destructor of ExternalMutexGuarded<T> attempts to clear out its
underlying T object while under the protection of the mutex by assigning
a default-constructed T to it. This triggered the bug where we BTreeImpl
failed to free its memory …
> Disallow copying of B-Tree table indexes and fix their move operations

- c++/src/kj/timer.h
Th original comment was misleading to me. I understood it to mean "Timer counts
on its own, but may get slightly out of sync until the start of the event loop,"
especially because of the "guaranteed to be synchronized" bit. The actual
meaning is "At any given point, Timer is frozen in time, and is only updated at
the start of the event loop."
cc @a-robinson
> Clarify that kj's async Timer only updates when the event loop waits

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
It's often times more terse/readable to use a lazy `orDefault` version
instead of writing out the KJ_IF_MAYBE logic by hand.
> Implement a lazy Maybe::orDefault

- c++/src/kj/async-queue-test.c++
- c++/src/kj/compat/tls-test.c++
It seems I was leaning on elision when I wrote this test and that matters for some compile configurations.
> Explicitly specify rule of five for QueueTest/TlsReceiverTest

- c++/src/kj/mutex-test.c++
- c++/src/kj/source-location.c++
- c++/src/kj/source-location.h
Rather than using magic line numbers, just supply the location used into
the functions so that we can just use plain equality in mutex tests.
Similarly, define an equality operator for SourceLocation so that they can be
used with `KJ_REQUIRE` macros.
> Cleanup mutex tests & SourceLocation equality

- c++/src/kj/string.h
Make begin/end constexpr as they are for ArrayPtr (+ make comparison
against nullptr similarly constexpr).
> Add constexpr annotation to misc StringPtr methods

- c++/src/kj/mutex.c++
- c++/src/kj/mutex.h
This should provide an additional breadcrumb to debug the contended mutex case.
In the future we might want to hide this behind a dedicated separate macro to avoid
the bloat of the `kj::Mutex`.
> Print reader contention location

- c++/src/capnp/dynamic.c++
- c++/src/kj/filesystem.c++
- c++/src/kj/string.c++
Motivated by: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33710
Clusterfuzz considers any UBSAN violation to be a possible security flaw. In practice, none of the actual errors are likely to be exploitable.
This commit fixes all errors reported by `capnp-test` with UBSAN enabled.
> Fix UBSAN errors.

- .github/workflows/quick-test.yml
- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.c++
- c++/src/kj/mutex.h
- c++/src/kj/test-helpers.c++
#1284 might have accidentally broken the lock contention code if not caught in code review. Add a unit test to protect accidental breakage in the future.
> Lock contention tests

- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
If the size of the linked list is really large (e.g. 20000000), it's easy to generate a stack overflow
because the compiler will unwind the object graph through the stack. Switch this to unwind with
a fixed size loop to avoid that problem. Obviously a large list like this can take time to unwind
anyway, so it may be worthwhile to consider adding limits to how large a task set that is directly
under untrusted control is allowed to get.
I don't have a Windows machine so I haven't verified that the stack test without the fix fails on its
own there but presumably this simple test uses roughly the same amount of stack on all platforms.
> Fix stack overflow potential destroying TaskSet

- c++/src/kj/async-test.c++
Looks like `-fno-exceptions` builds have been failing in `Async/LargeTaskSetDestruction` since b6e26ae was merged, because FiberStack's constructor fails when exceptions are turned off.
> Fix large taskset test when building with KJ_NO_EXCEPTIONS

- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/test-util.c++
- c++/src/capnp/test-util.h
- c++/src/capnp/test.capnp
Also, change type of `RpcSystem was destroyed` exception to `DISCONNECTED` to reduce INFO log spam
> Don't add remote exception prefix if already present for exceptions coming in over RPC

- c++/src/kj/async-io-unix.c++
To make the "connect()" error message a bit more useful, add the address that was being attempted.
/cc @kentonv @vlovich 
Signed-off-by: James M Snell <jasnell@gmail.com>
> Add address to connect() error message

- c++/src/capnp/serialize-async.c++
- c++/src/kj/async-queue-test.c++
These were of the form `warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]`.
This shouldn't affect the behavior in practice, but the fix was easy and it makes the build quieter.
> Fix some compiler warnings

- c++/src/capnp/CMakeLists.txt
Currently, running `capnp[c] --version` on Arch Linux (both the current 0.8.0 and my self-built 0.9.0 package) prints "Cap'n Proto version (unknown)" because `VERSION` is a CMake variable but not a C++ definition. This adds `VERSION` as a C++ definition, fixing the resulting binaries. This also switches `CAPNP_INCLUDE_DIR` to a `target_compile_definitions` call for simplicity.
The existing CMakeLists.txt is strange though; the following *overwrites* the list of definitions:
```cpp
set_target_properties(capnp_tool PROPERTIES
COMPILE_DEFINITIONS CAPNP_INCLUDE_DIR=\"${CMAKE_INSTALL_FULL_INCLUDEDIR}\"
)
```
I tried adding variations of `;VERSION="${VERSION}"` to set two definitions, but it was rejected since CMake thought it was multiple arguments to set_target_properties. I decided to append …
> Fix capnp/capnpc --version when built using CMake

- c++/src/capnp/capability.h
Most other hook types already have similar `from()` methods, but this one was missing.
> Add CallContextHook::from().

- c++/src/kj/compat/tls-test.c++
Just a difference in error message, maybe because BoringSSL FIPS is simply so old.
> Fix tls-test.c++ when linked against BoringSSL in FIPS mode

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
The behavior of the `limit` with `tryTee` was unclear. I just assumed that if the new limit is smaller, then we fail the optimization & force the regular `newTee` path, which seems reasonable since the limit applies to the overall tee, not any individual branch.
It's also important to note that I think the way we use the limit may be incorrect, or at least need to feed back into V8's external memory usage calculation. The reason is that if have 200 branches & set a limit of 5 MB on the tee, each branch would be allowed to have a 5 MB buffer...
> Fix tee stack overflow

- c++/src/capnp/compiler/node-translator.c++
- c++/src/capnp/testdata/errors.capnp.nobuild
- c++/src/capnp/testdata/errors.txt
In practice this would only result in incorrect behavior if the uninitialized value turned out to be equal to a certain non-zero constant. Hence, in practice, incorrect behavior was unlikely and maybe impossible. I wasn't able to trigger it in tests.
This is one part of #1311.
> Fix copy-pasto resulting in uninitialized use of `kind`.

- c++/src/kj/async-io-unix.c++
On FreeBSD versions <= 11 the magic value of "0" would be used instead.
> Fix build regression introduced in d3b0dc209 - the SOL_LOCAL is not defined on FreeBSD 11.x and below.

- .cirrus.yml
- c++/src/capnp/compiler/capnp-test.sh
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/string-test.c++
This should run automatically on PRs and commits and will ensure no regressions are made over time (might need project maintainers to make few clicks to enable).
Few issues preventing unit test suite from completing have been identified and fixed.
> Add Cirrus CI configuration to test capnproto on a few actively maintained FreeBSD versions and fix few issues

- c++/Makefile.am
- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-coroutine-test.c++
- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async.c++
- kjdoc/tour.md
- super-test.sh
This adds support for the Coroutines TS to libkj. Specifically, you can now co_await kj::Promise<T> objects from inside functions which themselves return kj::Promise<U> objects.
The integration is header-only, so the only difference in a Cap'n Proto build is that we might conditionally compile the coroutine tests, if the compiler and standard library both support the Coroutines TS.
I tested this with Clang/libc++ 12 and the latest VS2019.
* For Clang with autotools / CMake it should be sufficient to configure the toolchain like so, then configure and build like normal:
export CC=clang
export CXX=clang++
export CXXFLAGS="-std=gnu++17 -fcoroutines-ts -stdlib=libc++"
export LDFLAGS="-fcoroutines-ts -stdlib=libc++"
./configure && make check
* For VS2019, add -DCMAKE_CXX_FLAGS="/std:c++17 …
> Add Coroutines TS support

- c++/src/kj/async-coroutine-test.c++
This failed in our downstream project's CI, but I can't reproduce the failure locally. I don't have time to dig too deep, so let's just disable this test as flakey.
> Disable coroutine trace test on arm64

- c++/Makefile.am
- c++/src/capnp/compiler/capnp-test.sh
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async.c++
It's been on my to-do list for quite some time now, finally got a chance to do it. This PR aims to:
- fix test for systems with bsd cmp
- a single dash is required for bsd style cmp to accept input from stdin
- Allow disable fibers with KJ_USE_FIBERS
- as discussed in https://github.com/capnproto/capnproto/issues/1208 and https://github.com/capnproto/capnproto/issues/1167
- Use appropriate ldconfig command for OpenBSD 
Tested on OpenBSD 7.0-beta/AMD64.
output of `make check`: https://github.com/ZhanYF/static/blob/main/checkLog
- 1 of 3 tests failed, but I guess that's due to not building fibers?
any comment?  I have to admit I'm not familiar with capnproto/fibers/c++ in general, so please feel free to tweak it :)
> Add support for OpenBSD

- c++/src/kj/time.c++
- c++/src/kj/time.h
strPreallocated can now accept kj::Duration/kj::TimePoint/kj::Date and
serialize things safely to not need any memory allocation. This is
pretty convenient and these types were accidentally used in Workers.
My primary motivation here was to fix the signal safety issue more robustly
and the bike-shedding in #1330 is dragging on far longer than I anticipated so
pulling in a targeted fix that should hopefully not be objectionable.
> Make kj time types safe to serialize in signal handler

- c++/src/kj/source-location.h
Use __has_builtin instead of checking clang version. Upside is that this
is also supported in GCC10 & newer.
Fixes #1305 1305
> Support building with Apple clang

- c++/src/kj/test-helpers.c++
When I vendored capnproto into a C++20 project, test-helpers.c++ failed to build on Windows Clang for two reasons:
- std::boyer_moore_horspool_searcher() takes begin and end, not begin and size.
- std::search() requires #include <algorithm>.
This makes me think that the boyer_moore_horspool_searcher codepath was never tested to work. I did not test to ensure that `hasSubstring()` functions correctly, only that it compiles. There may be undiscovered logical bugs even after this PR is merged, so you should test it further yourself.
----
The build doesn't fail on Linux because it takes the memmem codepath. Non-vendored standalone capnproto builds don't fail on Windows, because standalone capnproto configures both Clang and MSVC in C++14 mode, causing them to take the TODO(perf) path.
---- …
> Fix building test-helpers.c++ hasSubstring() on Windows C++17

- c++/src/capnp/CMakeLists.txt
- c++/src/kj/CMakeLists.txt
Previously, the capnp and kj targets exported different header include paths ("c++/src/capnp/.." and "c++/src/kj/.."), even though both resolved to the same folder.
This commit makes CMake resolve both paths to eliminate the ".." before adding them to the target. Now both targets' include paths are "c++/src", and when a user's CMake target includes both capnp and kj, CMake only lists this path once in the compiler command line.
> Eliminate .. and deduplicate CMake target include directories

- c++/src/kj/common.h
MSVC's conformant preprocessor (`/Zc:preprocessor`) adds support for the `##__VA_ARGS__` extension and the `__VA_OPT__(,)` C++20 feature.
(OUTDATED) Technically `_MSVC_TRADITIONAL` is a [reserved identifier](https://stackoverflow.com/q/228783) and we shouldn't be defining it, though I don't think it's a problem in practice. If you don't like this, whether because it defines a reserved identifier, or because defining the identifier in a library header will affect users which check for the macro, there are alternative (but less clear IMO) approaches I listed in #1307.
Fixes #1307.
> Fix build on MSVC with conformant preprocessor enabled

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This provides convenient syntax to return early from a function if a maybe is null, while avoiding the need to KJ_ASSERT_NONNULL() immediately after the check.
Unfortunately, the only way to implement this was with GCC statement expressions, a non-standard feature that MSVC does not support. So we can't actually use this in KJ proper, but it can be used by dependent projects that don't care about Windows.
cc @kkoenig
> Add KJ_UNWRAP_OR_RETURN macro.

- c++/src/kj/hash.h
Currently `hashCode(<string literal>)` takes the pointer-path meaning it
hashes just the pointer. This creates a weirdness in the API because
`hashCode(strPtr) != hashCode(strPtr.cStr())`. Disable hashCode for
naked C strings to avoid the ambiguity.
Similarly block all C arrays for a similar weirdness between T[n] and
ArrayPtr.
> Make hashCode behave more consistently

- c++/src/kj/CMakeLists.txt
This fixes #1351 by making sure that the `zlib` include path is the last in include paths during the local build.
Otherwise it leads to double includes from local build tree and the install path and failing the build.
The issue is that `CMake` appends include directories (by `INTERFACE`) at the end of the include path list and the local paths necessary for the local build are inherited from `kj` `INTERFACE` properties.
Great explanation is here: https://leimao.github.io/blog/CMake-Public-Private-Interface/
> Fixes the double includes in build when ZLIB is found.

- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async.c++
- c++/src/kj/async.h
In the Workers Runtime, the performance cost of this change seems to be well within the noise.
> Track source locations where Events were created in order to provide extra debugging info.

- c++/src/capnp/membrane-test.c++
- c++/src/capnp/membrane.c++
~~It seems to me like the returned promise can outlive the MembraneHook,
and/or the MembranePolicy which can cause a segfault.~~
If MembraneHook::getResolved() is called after MembraneHook::whenMoreResolved(),
but before the continuation in MembraneHook::whenMoreResolved() is called,
MembraneHook::whenMoreResolved will return a new ClientHook without saving
a reference to it, which causes a UAF in ClientHook::whenResolved() later on.
> Fix Potential UAF caused by race in MembraneHook

- c++/src/kj/async-io-win32.c++
When compiling this file under C++20 MSVC gives an error about the addrinfo types being different:
```
1>async-io-win32.c++
1>...\c++\src\kj\async-io-win32.c++(819,28): error C2440: 'initializing': cannot convert from 'addrinfo *' to 'kj::`anonymous-namespace'::SocketAddress::lookupHost::<lambda_1>::()::addrinfo *'
1>...\c++\src\kj\async-io-win32.c++(819,28): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>...\c++\src\kj\async-io-win32.c++(874,1): error C2027: use of undefined type 'kj::`anonymous-namespace'::SocketAddress::lookupHost::<lambda_1>::()::addrinfo'
1>...\c++\src\kj\async-io-win32.c++(874): message : see declaration of 'kj::`anonymous-namespace'::SocketAddress::lookupHost::<lambda_1>::()::addrinfo' …
```
> Fix async-io-win32 for vs2019 & C++20

- c++/src/kj/compat/tls.c++
As of September 30, 2021, old versions of OpenSSL (1.0.x) could no longer verify Let's Encrypt certificate chains by default, due to the problems described here:
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
https://community.letsencrypt.org/t/openssl-client-compatibility-changes-for-let-s-encrypt-certificates/143816
It turns out the problem can be solved by setting a flag. That flag actually became the default in 1.1.0.
Of course, no one should be using OpenSSL 1.0.x anymore, but the various OpenSSL forks fixed this problem at different times, and the FIPS-certified version of BoringSSL is known to have this problem as well, thus requiring the work-around.
> Work around old OpenSSL versions not being able to verify Let's Encrypt certificate chains.

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
This integer is set to an unlikely constant on construction, and set to zero in the destructor. It is then used to detect an event that is armed after destruction.
The previous boolean approach works sometimes but seems unreliable, probably because the successor occupier of the memory often tends to zero out the byte where the boolean is supposed to be.
> Replace boolean `destroyed` with magic integer `live` in `Event`.

- c++/src/kj/table.c++
Previously we would compare slot `i` against slot `i+1` to check that ordering is correct. However, the basic validity of slot `i+1` hadn't been verified yet. It it was wildly invalid, this could segfault. If we instead compare `i-1` against `i`, then we know both slots have been basically verified already. If a slot is totally broken, this should now throw instead of segfaulting.
> Tweak BTreeImpl::verifyNode().

- c++/src/kj/async-io.c++
The effect of this bug is that the optimization wouldn't kick in when using limits since the optimization is only allowed when the limits match.
> Fix tryTee() optimization when limits are used.

- c++/src/kj/compat/http.c++
Previously, KJ would return a 5XX error to the client, but wouldn't actually log the error anywhere,
making it difficult to tell what went wrong.
> Log exceptions when serving HTTP errors by default

- c++/src/kj/compat/http.c++
When we added the ability to suspend HTTP requests, we inadvertently broke tail call optimization in HttpServer::Connection::loop(), causing a memory leak.
> kj-http: Fix memory leak caused by TCO breakage

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
Use this to implement binding to a hostname that resolves to multiple addresses. This is common for `localhost`, which may return both ipv4 and ipv6 addresses.
(I didn't actually create this class for this purpose, but it was super-easy to use it to resolve this very old TODO...)
> Introduce ConnectionReceiver implementation that aggregates from multiple underlying receivers.

- c++/src/kj/async.c++
`makecontext` on the new M1 macs calls `bzero` on the entire stack configured in the `ucontext_t`. Because we set up a guard page, this was faulting. Instead, only pass the usable stack, leaving the guard page below the configured stack start.
Fixes #1386
> Lie about the true size of the fiber stack on M1 Macs

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
Rough tests show this reduces the CPU usage of pumping a large stream by more than half (!).
(I also tried simply increasing the buffer size used by the existing pump implementation, but that didn't seem to affect performance much.)
> Optimize fd-to-fd pumps on Linux using splice().

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
It turns out that the pipe buffer size we were setting is already the default. So we can save a syscall by not setting it explicitly.
Moreover, this entirely avoids the problem we saw in production when too many pipes were allocated. It turns out that by default, Linux has a "soft" limit on pipe allocation but no "hard" limit. What this means is, once a certain amount of pipe buffer has been allocated, Linux will start giving new pipes a 4k buffer instead of 64k, and won't allow them to be grown. If we just live with the buffer size Linux gives us, then there's no problem.
> Restore splice pump optimization

- c++/src/kj/table-test.c++
- c++/src/kj/table.c++
This causes the BTreeImpl to think it has room for one more node than it
really does, leading to reading/writing beyond the end of its allocated
memory.
For example, in the test case this commit adds, at the time of
failure GDB shows the tree having an allocated capacity of 4 nodes but a
tree that contains the 1 root Parent node and 4 Leaf nodes.
The Parent contains:
```
keys = {{i = 7}, {i = 14}, {i = 21}, {i = 0}, {i = 0}, {i = 0}, {i = 0}}
```
The Leaf nodes contain, respectively:
```
rows = {{i = 1}, {i = 2}, {i = 3}, {i = 4}, {i = 5}, {i = 6}, {i = 7}, {i = 0}, {i = 0}, {i = 0}, {i = 0}, {i = 0}, {i = 0}, {i = 0}}
rows = {{i = 8}, {i = 9}, {i = 10}, {i = 11}, {i = 12}, {i = 13}, {i = 14}, {i = 0}, {i = 0}, {i = 0}, {i = 0}, {i = 0}, {i = 0}, {i = 0}}
rows = {{i = 15}, {i = 16}, {i = …
```
> Fix corruption in Tables with a TreeIndex after clear()

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
If a newly-accepted connection was immediately broken such that the very first read failed without even blocking then the loop itself would terminate early due to failing to the exception being thrown synchronously.
Fixes #1219.
> Fix bug where HttpServer listen loop would terminate early.

- c++/src/kj/async-io-unix.c++
I don't really understand why it passed the current CI, but with the latest PR in capnproto, both the tests and samples fail to build for me. It works from commit 8009588ff84cbdf233f6d23d1d507462b050b427.
The error I get is:
```
[ 44%] Linking CXX executable kj-heavy-tests
/usr/bin/ld: libkj-async.a(async-io-unix.c++.o): in function `kj::(anonymous namespace)::AsyncStreamFd::splicePumpLoop(kj::(anonymous namespace)::AsyncStreamFd&, int, int, unsigned long, unsigned long, unsigned long)::{lambda()#3}::operator()() const':
async-io-unix.c++:(.text+0x1f1d): undefined reference to `kj::(anonymous namespace)::AsyncStreamFd::MAX_SPLICE_LEN'
collect2: error: ld returned 1 exit status
```
I don't think that it is necessary to add this github workflow, because capnproto already should cover that …
> Build fails with -O0 on Ubuntu 20.04

- c++/src/kj/CMakeLists.txt
An potential issue I saw when re-reading the code (I was the original author of the WITH_OPENSSL CMake stuff).
> CMake: don't overwrite tls-test.c++ COMPILE_DEFINITIONS, append to it

- c++/src/kj/async-coroutine-test.c++
- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
This behavior was erroneous, and broke the guarantee that calling code could observe its own subsequent synchronous code run before newly-enqueued asynchronous code.
> Disable the coroutine immediately-ready optimization before the first suspension

- c++/src/kj/filesystem-disk-unix.c++
This PR adds a check for `SYS_renameat2` which is needed on older Linux; specifically [manylinux2014](https://www.python.org/dev/peps/pep-0599/) which is essentially CentOS 7.
Here is a test on a Linux system with Docker for reproducibility:
```console
$ docker run --rm "dockcross/manylinux2014-x86@sha256:8adf47eceeeeab1d1a14c43e425de1c75004cf0f7bca5705d21164335d5cc97d" > ./dockcross
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
$ bash dockcross ./super-test.sh cmake
...
[ 13%] Building CXX object src/kj/CMakeFiles/kj.dir/parse/char.c++.o
cd /work/c++/cmake-build/src/kj && /opt/rh/devtoolset-10/root/usr/bin/g++   -D KJ_HAS_ZLIB=1 -Wall -Wextra -Wno-strict-aliasing -Wno-sign-compare …
```
> Check if SYS_renameat2 defined before using it

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
The HttpHeaderTable::Builder class allows you to reference its future table before it is fully built. But that HttpHeaderTable must be used to make HttpHeaders instances only after HttpHeaderTable::Builder::build() is invoked under peril of index out of bounds error in debug mode or segfault in release mode. These errors can be somewhat mysterious since they usually occur on a different stack from where the HttpHeaders instance was made. This commit adds an assertion that makes this situation more evident and logs useful diagnostic info about which header id was added after the construction. Hopefully, it should downgrade a segfault to failed Promise or thrown Exception for most users.
> Assert that HttpHeaders instances know about indexed ids

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
Before this PR, sending a message over a two party connection with an empty queue, after not having sent a message for some time, would cause incorrect queue wait time metrics to be reported until the message is actually written.
> Fix bug with queue wait time metrics in TwoPartyNetwork

- .github/workflows/quick-test.yml
- c++/CMakeLists.txt
- c++/cmake/CapnProtoConfig.cmake.in
- c++/configure.ac
- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
Add support for musl systems both for cmake and makefile (related to #1167).
* For makefile, it searches for the `getcontext` symbol in `libucontext`, and adds `-lucontext` if it is found.
* For cmake, it searches for `libucontext` using `pkg-config`, and links it if found.
Note: this PR makes the assumption that a system that has `libucontext` needs it for the `getcontext`, `makecontext` and `setcontext` symbols.
The CI fails for two tests, I believe because docker on the github workflow does not support ipv6 (see https://github.com/actions/virtual-environments/issues/668):
```
2022-01-15T01:25:57.4242371Z kj/async-io-unix.c++:865: failed: ::bind(sockfd, &addr.generic, addrlen): Address not available; toString() = [::1]:0
2022-01-15T01:25:57.4242816Z [ FAIL ] capnp/ez-rpc-test.c++:32: …
```
> Add support for musl

- .github/workflows/quick-test.yml
- .gitignore
**This PR should not be merged yet! ** It contains a GitHub Actions commit that will be removed when complete.
This PR adds a `dockcross manylinux2014` test target for GitHub Actions. Using `dockcross` gives a modern compiler (GCC 10.2 right now) while `manylinux2014` gives an old glibc ABI from 2014.
Some tweaks included in this PR:
* Put in flags to disable 32-bit testing (dockcross only includes either 64-bit and 32-bit, not both) and disable valgrind testing (dockcross does not provide this).
Maintenance cost: Every 4 years or so the "manylinux2014" will need to be bumped (ex. manylinux2018). `dockcross/manylinux2014-*` is implicitly `dockcross/manylinux2014-*:latest` which will always use a modern GCC compiler. For reproducibility we may want the Docker image pinned to a specific …
> Add dockcross/manylinux2014 to tests

- c++/src/kj/windows-sanity.h
Since `ERROR` is conditionally defined, we can't write `using win32::ERROR` later in the file. Use `using namespace` instead to pull in everything.
I also renamed the namespace to be more unique.
Fixes #1421.
> Fix windows-sanity.h in NOGDI case, again.

- c++/src/kj/filesystem-disk-test.c++
Test fails in ekam since it also runs as a generic Unix test, which doesn't have O_DIRECTORY. This should fix the test in the short-term.
> Fix computeCurrentPath test with generic Unix test

- c++/src/kj/compat/http.h
It's not immediately clear how one should try to access unindexed headers. This comment clarifies why we don't have a `get` method for unindexed headers, and is similar to an existing comment under the `unset` method.
> Add comment clarifying how to get unindexed headers

- c++/src/capnp/schema-parser.c++
- c++/src/capnp/schema-parser.h
This allows you to write a tool that parses a bunch of schemas and then dumps the whole set of compiled schemas.
> Add `SchemaParser::getAllLoaded()` to get all parsed schemas.

- c++/src/kj/common.h
I have a use case for cancelling a kj::defer(), rather like a transaction commit/rollback. I can write:
```
bool success = false;
KJ_DEFER({ if (!success) abort(); });
```
...but it seems a bit sad to keep track of another flag! Deferred is private, though, so not sure if this patch is the best approach.
> allow defer to be cancelled

- doc/_includes/footer.html
- doc/faq.md
- doc/index.md
Sandstorm-the-company no longer exists, and these references have been inaccurate for many years.
Some places describe Cap'n Proto as being owned by Sandstorm. What this was meant to describe is that Sandstorm was primarily responsible for development at the time, and held copyright of the code it developed. All code is copyright by whoever wrote it, or their respective employer. There are no registered trademarks. Kenton owns the domain, which was registered long before Sandstorm existed.
> Update outdated references to Sandstorm.

- c++/src/kj/async-coroutine-test.c++
This function was recognized as unused for MSVC and arm builds.
> Move `countLines()` inside if pragma

- c++/src/kj/common-test.c++
- c++/src/kj/memory.h
Add a lazy `orDefault(F&&)` function to the `kj::Maybe<kj::Own<T>>` specialization, similar to what was added in https://github.com/capnproto/capnproto/pull/1266.
cc @kentonv @vlovich
Refs: https://github.com/capnproto/capnproto/pull/1266
> Implement lazy Maybe<Own<T>>::orDefault

- c++/src/kj/async-test.c++
> Work around getcontext() being broken on manylinux2014-x86.

- .github/workflows/quick-test.yml
The musl build fails in https://github.com/capnproto/capnproto/pull/1460 because alpine doesn't have bash by default. I don't know why it was working before, but this fixes it.
> CI: alpine needs bash to run the tests

- c++/src/kj/async-inl.h
- c++/src/kj/async-io.h
- c++/src/kj/async-unix.h
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
KJ I/O objects cannot cross threads. This implies that objects which can cross threads must never own KJ I/O objects, execpt perhaps through specific mechanisms designed to allow it. This commit introduces some utilities that can be used to detect when KJ I/O objects are held in the wrong places.
> Introduce a debugging aid to detect when KJ I/O objects are held in the wrong places.

- c++/Makefile.am
- c++/src/kj/CMakeLists.txt
The 0.10.0 release package doesn't actually build on Windows because this header isn't in the package. :(
> Add missing header to makefiles.

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/units.h
Make `ArrayPtr<T>::operator==` much faster when `T` is an integral type, including `const char`, which is used by `StringPtr`.
> Optimize ArrayPtr::operator== for integral types

- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/exception-test.c++
- c++/src/kj/exception.c++
It appears ASAN now by default tries to detect stack-use-after-return. This breaks our assumptions in requireOnStack() and totally breaks fibers.
For requireOnStack() we can just skip the check in this case.
For fibers, we need to implement the ASAN hints to tell it when we're switching fibers.
> Fix ASAN problems under Clang 15.

- c++/src/kj/io-test.c++
- c++/src/kj/io.h
My use case is that I want to repeatedly `capnp::writePackedMessage` so I'd like to use and reuse a `kj::VectorOutputStream` for that. If you have a better solution I'll take it but this seemed reasonable.
> Add kj::VectorOutputStream::clear()

- c++/src/capnp/compat/std-iterator.h
Instead, define type aliases directly.
> Don't use deprecated std::iterator

- c++/src/capnp/compiler/error-reporter.h
- c++/src/kj/async-inl.h
- c++/src/kj/async-io.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-queue.h
- c++/src/kj/async.h
- c++/src/kj/timer.h
bazel doesn't support relative includes across library boundaries, thus makes it impossible to defined componentized build.
> using absolute includes across library boundary

- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
It might be useful to consumers to be able to poll for a bounded number of
events in order to yield control of the thread over to other time-sensitive
processing that is unable to run on another thread.
Added a test case to assert that events are only processed up to the max turn
count.
> Overloaded kj::WaitScope::poll to accept a max turn count argument

- c++/src/capnp/schema.c++
- c++/src/capnp/schema.h
As mentioned in #1490, in order to accurately reconstruct brand bindings in a way that will lead to identically comparing schemas, I need to be able to get an exact list of binding scopes. This PR adds a new method to the schema class that lists all the brand binding scopes of the underlying RawBrandedSchema. This should hopefully be both simpler to review and a lower-risk addition, as it only reads information instead of mutating the schema loader's state.
> Added method to list brand binding scopes

- c++/src/capnp/BUILD.bazel
- c++/src/capnp/reconnect.h
Fixing relative include path across component boundariess.
> [bazel] adding remaining capnp tests

- c++/src/capnp/c++.capnp
- c++/src/capnp/c++.capnp.c++
- c++/src/capnp/c++.capnp.h
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/test-import2.capnp
Reverts capnproto/capnproto#1502
This didn't actually remove the schema declarations, only the definitions. As a result the code fails to link under certain conditions (unclear what conditions, seems to affect cmake and bazel but not automake).
> Revert "Implement $Cxx.omitSchemas annotation"

- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
- c++/src/kj/async-unix.h
It turns out that creating a signalfd is weirdly expensive. But, due to their unintuitive behavior of always checking the signals of the calling thread, not the creating thread, we can actually share just one among many threads, as long as those threads are waiting on the same signals.
We should probably stop using signalfd altogether, maybe falling back to the old longjmp() trick we use on other platforms, but that's a bigger change than I want to make right now.
> Introduce the ability to share the same signalfd among many threads.

- c++/.bazelrc
It seems we need to mess with toolchains, which I'd rather not do, if we want to set these up in a more sophisticated way.
> [bazel] using correct warning settings

- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
- c++/src/kj/async-unix.h
Instead, use `epoll_pwait()` to wait on epoll events and signals at the same time.
Reasons are explained in the comment in `UnixEventPort::wait()`:
```
// Note: Once upon a time, we used signalfd for this. However, this turned out to be more
// trouble than it was worth. Some problems with signalfd:
// - It required opening an additional file descriptor per thread.
// - If the set of interesting signals changed, the signalfd would have to be updated before
//   calling epoll_wait(), which was an extra syscall.
// - When a signal arrives, it requires extra syscalls to read the signal info from the
//   signalfd, as well as code to translate from signalfd_siginfo to siginfo_t, which are
//   different for some reason.
// - signalfd suffers from surprising lock contention during epoll_wait …
```
> Stop using signalfd on Linux.

- c++/src/kj/test.c++
Fixes stack format when KJ_HAS_LIBDL is defined
> Use stringifyStackTraceAddresses in kj_test

- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc-twoparty.h
- c++/src/capnp/serialize-async.c++
- c++/src/capnp/serialize-async.h
I'm not sure if we want this to be a default, or configurable behavior -- If your event loop was backed up enough for this to cause problems, I think that you'd be hurting from queueing writes regardless. And even if so, you could run into stack overflow if you queue enough messages, which this PR should also stop from happening.
First commit is same as (https://github.com/capnproto/capnproto/pull/1509) but I can't set the merge target to a branch in my own repo for a PR in this one.
> Buffer writes using `evalLast` in TwoPartyVatNetwork

- c++/src/capnp/membrane-test.c++
- c++/src/capnp/membrane.h
As discussed with Kenton, the `shouldResolveBeforeRedirecting` feature shouldn't be enabled by default. This is a simple PR to flip the default. It is a breaking change but it's unlikely to be used in the wild and I am preparing a PR for sandstorm to ensure things continue working there.
> Changes shouldResolveBeforeRedirecting default to false in membranes.

- c++/src/kj/string.h
Avoids a call to ::strlen(), but will now copy any embedded null characters and beyond.
> use size when converting between std::string and kj::String

- c++/src/capnp/dynamic.c++
- c++/src/kj/arena.h
- c++/src/kj/array.h
- c++/src/kj/common.h
__has_trivial_constructor etc. are deprecated since Clang 15: https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#non-comprehensive-list-of-changes-in-this-release
> Some type-trait builtins, such as `__has_trivial_assign`, have been documented as deprecated for a while because their semantics don’t mix well with post-C++11 type-traits. Clang now emits deprecation warnings for them under the flag `-Wdeprecated-builtins`.
> Prefer __is_trivially_constructible etc. intrinsics

- c++/src/capnp/compiler/capnp-test.sh
- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/compiler/module-loader.c++
- c++/src/capnp/compiler/module-loader.h
- c++/src/capnp/compiler/parser.c++
- c++/src/capnp/compiler/parser.h
- c++/src/capnp/schema-parser-test.c++
- c++/src/capnp/schema-parser.c++
- c++/src/capnp/schema-parser.h
- c++/src/capnp/testdata/no-file-id.capnp.nobuild
Assigning file IDs is a pointless exercise when using capnp files as configuration. Typically this involve files that don't even define any types, just constants. The ID does not affect the output of `capnp eval` in any way. So, we should not require file IDs to be present in this case.
Also expose this option on `SchemaParser`, for applications which use that class to parse config.
> Allow file IDs to be omitted when using `capnp eval`.

- c++/src/kj/BUILD.bazel
Without this, I got a bunch of linker errors.
> [bazel] Add missing async-coroutine-test -> kj-test dependency

- c++/src/kj/async-prelude.h
- kjdoc/tour.md
This avoids deprecation warnings when using modern clang builds.
Still need to test this in Windows.
> Support C++20 coroutines

- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
Hex value was converted wrongfully to a code-point value. Test added.
> Fix utf-8 escape sequences parsing for json strings

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
As mentioned in the PR to enable compression in Workers, I suspect we don't need to extract the extensions from the websocket. Happy to do that if I'm mistaken, though in that case I may have a follow up question regarding the fact that a KJ websocket is unaware whether it's on the client/server side. This makes it a bit tricky to determine if `inbound` maps to client or server (unless we know for certain whether our websocket is client or server side).
> Add `getPreferredExtensions()` to WebSocket class

- c++/CMakeLists.txt
- c++/src/kj/CMakeLists.txt
Similar, but better than #1137 which is generating an empty `libkj-gzip.a`, whereas this one is just not building it at all if `ZLIB` is disabled (just like the Makefile does, I checked). I added the author @ScatteredRay as a co-author here :+1:.
@harrishancock had a mention there:
> On a related note, do we need to add a find_dependency(ZLIB) call to capnproto/c++/cmake/CapnProtoConfig.cmake.in? Similar to: https://github.com/capnproto/capnproto/blob/master/c%2B%2B/cmake/CapnProtoConfig.cmake.in#L52-L63
I think this is a valid point, but I would need to test it to be sure. I will open another PR if I get to that. This PR has no impact on it however (it just feels like a somehow related bug in CapnProtoConfig.cmake.in), so IMO it could be merged as-is.
> cmake: add ZLIB option

- c++/src/capnp/capability.c++
- c++/src/capnp/compat/byte-stream-test.c++
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/ez-rpc.c++
- c++/src/capnp/membrane.c++
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/serialize-async.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-test.c++
- c++/src/kj/async.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
Because it felt like it would not hurt to try removing this pre-C++14 workaround :innocent::
```cpp
template <typename Func, typename MovedParam>
inline CaptureByMove<Func, Decay<MovedParam>> mvCapture(MovedParam&& param, Func&& func) {
// Hack to create a "lambda" which captures a variable by moving it rather than copying or
// referencing.  C++14 generalized captures should make this obsolete, but for now in C++11 this
// is commonly needed for Promise continuations that own their state.  Example usage:
//
//    Own<Foo> ptr = makeFoo();
//    Promise<int> promise = callRpc();
//    promise.then(mvCapture(ptr, [](Own<Foo>&& ptr, int result) {
//      return ptr->finish(result);
//    }));
return CaptureByMove<Func, Decay<MovedParam>>(kj::fwd<Func>(func), kj::mv(param));
}
```
> Remove mvcapture

- c++/cmake/CapnProtoConfig.cmake.in
- c++/src/kj/CMakeLists.txt
* Fix a bug where heavy-tests do not build if `WITH_ZLIB=OFF` (because they were still linking kj-gzip which is not built in that case).
* Have `CapnProtoConfig.cmake` find ZLIB if `WITH_ZLIB=ON` since it's a transitive dependency (just like OpenSSL).
* Do not build `kj-tls` if `WITH_OPENSSL=OFF`. I don't see a use-case where one would want that, and it ends up in `undefined reference` errors at link time instead of complaining at configure time.
@harrishancock: FYI
> Various CMake improvements for WITH_ZLIB=OFF and WITH_OPENSSL=OFF

- c++/src/kj/async.c++
- c++/src/kj/async.h
One of the unit tests checks that multiply-invoking a coCapture()ed function object throws. When I imported the code, I inadvertently broke this test by making it a debug-only check.
> Fix async-coroutine-test

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
While implementing TCP sockets for workerd I ran into a few things which I fix in this PR:
* NetworkHttpClient::Connect wasn't implemented (Kenton suggested we implement this as a direct TCP connection, I left a link to where he suggested this in a code comment). It works well for direct (non-proxied) connections in workerd.
* Reads of zero bytes (indicating a socket disconnect) weren't working. I narrowed it down to two things: BlockedPumpFrom and DelayedEofIoStream.
* ~~The former seems to not be handling EOF correctly, though perhaps it is meant to block on EOF by design as well and I should instead fix the code so it's not used in the HTTP CONNECT code path?~~
* ~~The latter is that ConnectResponseImpl uses a DelayedEofIoStream wrapper, I am not sure why this is used but removing it …
> Implements NetworkHttpClient::Connect and fixes for EOF

- c++/src/kj/async-prelude.h
To fix the [issue](https://github.com/capnproto/capnproto/issues/1573) we need some more checks in async-prelude.h:
```
#if __cpp_coroutines && (__cpp_impl_coroutine >= 201902L) && __has_include(<coroutine>)
// C++20 Coroutines detected.
#include <coroutine>
...
#elif __cpp_coroutines && (__cpp_coroutines >= 201703L) && __has_include(<experimental/coroutine>)
// Coroutines TS detected.
#include <experimental/coroutine>
...
#endif
```
The first check would cover gcc + libstdc++ and clang (from version 14)
The second check would cover clang + libc++ (up until version 13)
> Issue with coroutine header when using Clang + libstdc++

- c++/src/kj/async-io-internal.h
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
These were buggy because allowing "public" and "network" were incorrectly implemented by adding 0.0.0.0/0 to the allow list and then adding non-public and non-network ranges to the deny list. If a separate rule tried to allow those ranges, the deny rules would take precedence since they had the same specificity.
Instead we special-case "public" and "network" as boolean flags instead of trying to represent them as CIDR unions.
Fixes https://github.com/cloudflare/workerd/issues/62
cc @dom96 (GitHub won't let me set him as reviewer)
> Fix restrictPeers allowing public+private, network+local, public+local.

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.h
- c++/src/capnp/serialize-async-test.c++
- c++/src/capnp/serialize-async.c++
- c++/src/capnp/serialize-async.h
This should improve performance by reducing syscalls needed to read several small messages.
I felt bad about playing "Bring me a rock" on #1528 so I took a shot at writing it. I think this code came out a lot simpler than previous attempts, but please let me know if I missed something important.
> Introduce buffered reads for RPC message streams.

- .github/workflows/quick-test.yml
- .github/workflows/release-test.yml
- c++/src/kj/async-test.c++
- c++/src/kj/compat/http.c++
It looks like GitHub might have just updated ubuntu-latest to ubuntu-22.04, and everything is broken there (mostly because we try to install specific compiler version packages which are no longer available, but there is at least one real error with OpenSSL 3.0). Need to come back to this later.
> Pin CI to ubuntu-20.04.

- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/http-over-capnp-perf-test.c++
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/http-over-capnp.capnp
- c++/src/capnp/compat/http-over-capnp.h
- c++/src/kj/async-inl.h
- c++/src/kj/async-io.c++
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/compat/gzip.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/tls.c++
Most of the gain here is in the http-over-capnp protocol change. Unfortunately it is backwards-incompatible, so will require a multi-step deployment. The code currently defaults to using the old protocol but provides a way to opt into the new protocol.
This PR provides a 12% or so CPU improvement on the http-over-capnp test.
> Simplify http-over-capnp protocol, and other optimizations

- c++/src/capnp/c++.capnp
- c++/src/capnp/c++.capnp.c++
- c++/src/capnp/c++.capnp.h
- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
- c++/src/capnp/compat/byte-stream.capnp
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/http-over-capnp.capnp
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/dynamic-capability.c++
- c++/src/capnp/dynamic.h
- c++/src/capnp/membrane-test.c++
- c++/src/capnp/membrane.c++
- c++/src/capnp/persistent.capnp.h
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/test-util.c++
- c++/src/capnp/test-util.h
- c++/src/capnp/test.capnp
- c++/src/kj/common.h
This PR rips out `allowCancellation()`, then re-introduces it as an annotation.
This performs much better -- especially when the annotation is set -- as a lot of bookkeeping can be skipped.
The performance improvement in the local-call http-over-capnp test is ~12%. For the full RPC test, the improvement is more like 5%.
This is a breaking change, but only if people call `allowCancellation()` today, in which case they will get a nice compiler error telling them what changed.
cc @xortive
> Change allowCancellation from a method call to an annotation

- c++/src/kj/compat/http.c++
Saw an event where decompression failed, but since we didn't log the error code we can't determine what went wrong.
> Include error code when (de)compression fails

- doc/language.md
The current documentation caused confusion with the term "absolute path" in import statements in combination with the search path directories. An example should avoid this confusion.
closes #1595
> Clarify doc on absolute path imports

- .github/workflows/quick-test.yml
- c++/src/kj/compat/readiness-io.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
- super-test.sh
This is based on #1434, but I went ahead and made KJ treat unexpected EOF as an error -- even with OpenSSL 1.x -- since this is technically important to prevent truncation attacks.
(It turns out that lots of apps than use OpenSSL 1.x are vulnerable to truncation attacks, which is why OpenSSL 3 decided to strengthen the error reporting to make it clearer that this situation _should_ be an error, but this was considered a breaking change. So KJ is not alone in having this bug, but I went ahead and fixed it even when using OpenSSL 1.x.)
NOTE: I'm flying blind here as my local Debian machine is still on OpenSSL 1.x. Gonna do a little CI-driven-development. I'll mark this no longer a draft once I get CI passing...
> Support OpenSSL 3.0

- c++/src/kj/compat/http.c++
The error message for an unknown transfer-encoding header value includes the pointer value instead of the string itself.  Seems to have been introduced accidentally in PR#1454?
https://github.com/capnproto/capnproto/pull/1454/commits/a267d653340198e268782ac856951ee8a23de107#diff-09d28b46bd98866f20dd7241e02c70338a76fdb59a483ed02d4c16bbe6bcc3a1R1889
> Fix log for unknown transfer encoding error

- c++/src/capnp/cc_capnp_library.bzl
Without this fix src path for generated files is somewhere in bazel internals. We need to tell capnp to strip this part of the name.
> [bazel] supporting generated capnp files

- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/http-over-capnp.capnp
- c++/src/capnp/compat/http-over-capnp.h
- c++/src/kj/compat/http.c++
In internal repo for ASAN:
```
$ bazel test //src/ew/tests:sockets/sockets-tcp-test.ew-test-bin@force-process-sandboxing
$ bazel test @capnp-cpp//src/capnp/compat:http-over-capnp-test --config=asan --test_timeout 5
```
> Implements HTTP Connect in http-over-capnp.

- c++/src/capnp/rpc.c++
On the receiving end, we need to make sure the `RpcCallContext` lives at least until `Finish` is received. Otherwise, when the context is destroyed, it will prematurely remove the answer table entry making pipelined calls fail, defeating the purpose.
Unfortunately we'll have to wait for this to roll out fully before we can actually use `sendForPipeline()`.
> Fix bug in sendForPipeline().

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/refcount-test.c++
- c++/src/kj/refcount.h
Various ad hoc versions of this have appeared all over the place, but many of them -- including the one replaced in this PR -- do more allocation than necessary. By building this into refcounted.h, we can take advantage of friendly knowledge that `Refcounted` itself implements `Disposer`, and that said disposer doesn't care what pointer is passed into it, because it knows it's supposed to dispose itself. So we can set the refcounted wrapper as the disposer on an `Own<T>` pointing at the wrapped object, avoiding the need for an additional allocation that would otherwise be needed if we used `kj::attachRef`.
@dom96 can you review? (GitHub won't let me formally set you as reviewer unless I make you a project member, but it'll still let you approve the PR.)
> Introduce RefcountedWrapper to refcount types that don't inherit Refcounted.

- c++/src/capnp/compat/http-over-capnp.c++
> Cleanup unused promises variable in http-over-capnp

- c++/src/capnp/cc_capnp_library.bzl
the previous version didn't work from external repository upstream.
> bazel: better fix for generated capnp files

- c++/src/kj/string-test.c++
Like other versions before, gcc 13 moved some includes around and as a result <cstdint> is no longer transitively included. Explicitly include it for uint8_t.
> Fix build with gcc 13 by including <cstdint>

- c++/src/benchmark/runner.c++
- c++/src/kj/debug-test.c++
- c++/src/kj/string.c++
There were only a couple usages and they are all cases that are formatting a single integer therefore couldn't possibly overrun the buffer. Plus most are in test code. But it's easy enough to call snprintf().
This fixes the mac build, which recently started failing due to a deprecation warning for sprintf().
> Change sprintf() -> snprintf() to silence warnings.

- c++/src/kj/compat/http.c++
I had an idea for an alternative way to implement the UAF protection introduced in #1612.
This approach has a few benefits:
* No extra allocation is needed.
* It applies to both input and output streams (readers and writers).
* It enforces / takes advantage of the fact that there's only one wrapper stream at a time -- no refcounting needed.
* I think the code is a little more self-contained (modulo some refactoring of the affected classes).
> Alternative version of HTTP body stream UAF protection.

- c++/src/kj/string.h
An operator!= suppresses the reversed equality comparison candidate generation.
This is visible in clang 16 (rc0 just released) and in gcc trunk (so probably gcc 13).
> Remove operator!= synthesized by spaceship

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
A canceled read from an HTTP body can leave the body stream in an invalid state if some data was read but never processed. This is usually fine because reads are only canceled when the whole operation is being canceled, but let's guard against attempts to read further to be safe.
> Add guards against canceled HTTP reads.

- c++/src/capnp/capability.c++
`tailPipelinePromise` is returned by `context->onTailCall()`, therefore it must hold a strong ref to the context.
This is hard to trigger, because `tailPipelinePromise` is `exclusiveJoin()`ed with `pipelinePromise`, which itself holds such a ref. So, the only way this promise could still exist after `context` has been dropped is the case where this promise is also imminently going to be canceled. But it is actually possible to wedge a continuation in between that UAFs.
This only seems to kick in with `sendForPipeline()` since in the common case the non-pipeline branch also holds the `context` ref long enough to prevent any issue.
> Fix obscure UAF with sendForPipeline().

- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/filesystem-disk-win32.c++
- c++/src/kj/filesystem.h
We don't recurse into symlinks, we just delete the symlink. But it's possible that at the time we checked the file type, it was an actual directory, and then someone swapped it out for a symlink before we tried to recurse into it.
Rust recently fixed the same bug, which they treated as a CVE: https://github.com/rust-lang/rust/security/advisories/GHSA-r9cc-f5pr-p3j2
This is only a security issue if the program doing the deleting is a privileged process, and it is deleting directories which are writable to an attacker.
I am not calling this a CVE in KJ because I feel quite comfortable saying that nobody is using KJ filesystem in this way today. It's likely that literally no one is using the recursive-delete feature at all, and no one except my own projects are even using this entire API. …
> Fix TOCTOU bug when recursively deleting a directory with symlinks.

- c++/src/capnp/c++.capnp.h
- c++/src/capnp/compat/json.capnp.h
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/grammar.capnp.h
- c++/src/capnp/compiler/lexer.capnp.h
- c++/src/capnp/persistent.capnp.h
- c++/src/capnp/rpc-twoparty.capnp.h
- c++/src/capnp/rpc.capnp.h
- c++/src/capnp/schema.capnp.h
- c++/src/capnp/stream.capnp.h
Some tools will ignore missing headers, so if 'capnp/generated-header-support.h' is not in the include path, we would warn about a version mismatch instead of a missing include.
> Emit a different error if CAPNP_VERSION is not defined in generated headers

- c++/src/kj/filesystem-disk-unix.c++
This work-around has been used internally in the Workers Runtime codebase for a long time, but is kind of awkward to apply there. Baking it into KJ makes things cleaner.
> Work around broken open("/") under qemu-user.

- c++/src/kj/async-io.h
- c++/src/kj/compat/BUILD.bazel
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
- c++/src/kj/compat/tls.h
* In order to access `TlsContext` from a `TlsNetwork` I needed to introduce a new SecureNetworkWrapper.
* The `tlsStarter` callback API isn't perfect, but seems to be our best idea. If anyone has others please share.
```
bazel test @capnp-cpp//src/kj/compat:tls-test --config=asan --test_timeout 5
```
> Implements StartTLS in HttpConnectSettings and NetworkHttpClient.

- c++/src/kj/async-io.h
- c++/src/kj/compat/BUILD.bazel
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
- c++/src/kj/compat/tls.h
Reverts capnproto/capnproto#1635
This actually breaks the workerd build and possibly others, due to the breaking API change which I pointed out and which was not, contrary to the PR thread, actually fixed.
cc @dom96
> Revert "Implements StartTLS in HttpConnectSettings and NetworkHttpClient."

- c++/src/kj/async-io.h
- c++/src/kj/compat/BUILD.bazel
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.h
Corrected version of https://github.com/capnproto/capnproto/pull/1635.
For reference, we want to ensure:
* No API breakage
* That kj-http doesn't depend on kj-tls.
This new PR should now ensure this.
```
bazel test @capnp-cpp//src/kj/compat:tls-test --config=asan --test_timeout 5
```
> Implements StartTLS in HttpConnectSettings and NetworkHttpClient. (Followup)

- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
Without this change there are compiler errors. ~This isn't really the ideal fix (it implies a `Maybe<void>` which obviously doesn't work)... but it fixes the errors without introducing any actual new problems.~ I made it better.
> Fix `Maybe<Own<void>>`

- c++/src/kj/async-win32.c++
This commit fixes a bug observed under Windows. It can happen that wake() is concurrently called while waitIocp is executing within the IoPromiseAdapter destructor. In such case, when wait() is called, the event posted by wake() has already been consumed and thus wait() waits forever to be resumed.
See issue #1623.
> Fix potential hang of EventPort::wait on Windows

- c++/.bazelrc
- c++/src/capnp/BUILD.bazel
- c++/src/kj/BUILD.bazel
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-test.c++
- c++/src/kj/async-win32.c++
- c++/src/kj/async-win32.h
- c++/src/kj/async.c++
- c++/src/kj/common.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/exception.c++
_(dependency of https://github.com/cloudflare/workerd/pull/452)_
Hey! 👋 This PR enables Cap'n Proto and KJ to be built and tested on Windows under Bazel, in addition to CMake. It also makes a few changes to enable `workerd` to be built on Windows. I've configured Bazel to use `clang-cl` as that's what `workerd` needs, but I suspect native MSVC should work.
> Fix Bazel builds on Windows

- doc/otherlang.md
Currently, the other languages page on the capnproto website implies that the capnproto implementation for the C# languages only supports .NET Core but as of now that is not the case. [The C# implementation](https://github.com/c80k/capnproto-dotnetcore) supports the .NET Standard 2.0 and has for a while now.
> Updated the C# other-lang header to be just 'C#' instead of 'C# (.NET Core)'

- doc/otherlang.md
The Go link on the current website version *does* redirect, but we are a couple redirects deep at this point. I also propose that maintaining a link to a older version of the same implementation that hasn't been committed to in four years is probably unnecessary at this point.
Finally, the chain of maintainers of this project is up to like... five people now? I propose rather than including the full list of authors and forks for this implementation, we replace "by" with "currently maintained by", and link @zenhack and @lthibault. The full list, of course, continues to be available at https://github.com/capnproto/go-capnp/graphs/contributors
> Website: Update Go implementation info

- c++/src/capnp/schema-parser.c++
Using `bool` essentially turns the hash map into a bad linked list: lookup is `O(n)`.
> Fix return type of hash operator (`bool` -> `size_t`).

- c++/src/capnp/capability.h
- c++/src/capnp/compat/byte-stream-test.c++
- c++/src/capnp/membrane.c++
- c++/src/capnp/membrane.h
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc.c++
See commit descriptions and comments.
This could cause the spurious error: `'Disembargo' of type 'senderLoopback' sent to an object that does not point back to the sender.`
The error would also be followed by closing the connection.
/cc @zenhack @dwrensha in case their implementations might have the same bug.
> Fix subtle bug with multi-hop disembargos.

- c++/src/kj/exception.c++
For the SymGetLineFromAddr64 method in the Windows dbghelp library, the pdwDisplacement argument requires a non-nullptr.
> Fix nullptr dereferencing in stringifyStackTrace

- c++/WORKSPACE
The macOS zlib build has been broken with recent versions of XCode, see https://github.com/bazelbuild/bazel/issues/17956 for additional discussion. Changing the C standard version for zlib is a relatively painless workaround. Note that build systems other than bazel link the system zlib and are not affected by this issue.
> [bazel] Fix zlib compilation on macOS

- c++/src/capnp/compat/json.capnp.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/grammar.capnp.c++
- c++/src/capnp/compiler/lexer.capnp.c++
- c++/src/capnp/generated-header-support.h
- c++/src/capnp/persistent.capnp.h
- c++/src/capnp/rpc-twoparty.capnp.c++
- c++/src/capnp/rpc.capnp.c++
- c++/src/capnp/schema.capnp.c++
- c++/src/capnp/stream.capnp.c++
Clang 15+ in C++17 mode (or higher) with `-Wdeprecated` issues a warning in
the generated code ([godbolt](https://godbolt.org/z/M5bvn5Y66)):
```
warning: out-of-line definition of constexpr static data member is
redundant in C++17 and is deprecated [-Wdeprecated]
```
It is rather annoying for downstream users of Capnp, since there's no
way to disable the specific warning. Instead, fix it here for code
compiled for C++17 and newer.
See [cppreference]:
> A constexpr static data member is implicitly inline and does not need
> to be redeclared at namespace scope. This redeclaration without an
> initializer (formerly required) is still permitted, but is deprecated.
> (since C++17)
[cppreference]: https://en.cppreference.com/w/cpp/language/static
--- 
Some more thoughts:
- This warning exists …
> Fix redundant constexpr warning in generated code

- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/byte-stream.capnp
- c++/src/capnp/compat/byte-stream.h
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/http-over-capnp.capnp
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Implements tlsStarter support for CONNECT via http-over-capnp.
```
$ bazel test @capnp-cpp//src/capnp/compat:http-over-capnp-test --test_timeout 5
$ bazel test //src/capnp/compat:http-over-capnp-test --test_timeout 5
```
and upstream tests.
> Implements tlsStarter for http-over-capnp.

- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/compat/http.c++
- kjdoc/tour.md
@dom96 and I were recently bitten rather hard by a latent bug in `HttpServiceAdapter::connect()`, in which pump exceptions do not eagerly cancel the returned promise, but instead hang in limbo.
We know roughly what a solution should look like: a fail-fast form of `joinPromises()`. I took a stab at implementing such a thing in this PR, which I called `joinPromisesFailFast()`.
A subsequent commit in the PR uses `joinPromisesFailFast()` to solve a few of the places we know this bug exists. Notably, `HttpServiceAdapter::connect()` required slight adjustments in order to keep tests passing, because exceptions from the pump promises must not cancel the returned promise in the event of an error response.
> Implement `joinPromisesFailFast()`

- c++/src/kj/compat/http.c++
Turns out there's a "reason" string for what went wrong when attempting to inflate the compressed data; we should add this to the error.
> Include additional ws compression error reason

- c++/src/kj/compat/http.c++
This should resolve some Sentry spam we are seeing.
> Ignore DISCONNECTED exceptions in AsyncIoStreamWithGuards::shutdownWrite

- c++/src/kj/common.h
while it works on practice it triggers ubsan and is easy to fix.
> fixing undefined behavior when ptr == null

- c++/src/kj/hash.h
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
This type is useful for cases where you want to store a borrowed StringPtr or an owned String and don't care about mutability of the String itself.
> Add new type ConstString

- c++/src/capnp/rpc.c++
Read failure probably means broken transport. Do not report shutdown exception in such case.
> capnp rpc: do not report shutdown error after read exception

- c++/src/kj/table.h
while works in practice, it triggers the ubsan. easy to fix and overhead is probably negligible.
> fixing memset undefined behavior

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
kj::WebSocketImpl::receive(maxSize) should let you receive a message that is at most maxSize bytes, but actually you only get maxSize-1 bytes. This commit makes the obvious fix.
> Fix off-by-one in WebSocket maximum message size.

- doc/language.md
> Clarify that retroactive unionization is not forward-compatible.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Currently, there's no good way to distinguish between WebSocket errors caused by the peer sending invalid data and WebSocket errors from other causes: they all result in FAILED-type exceptions.
This commit lets WebSocket users define a custom error handler for peer-caused errors. It only allows for customizing the thrown exception.
> Improve WebSocket protocol error handling.

- c++/src/capnp/rpc.capnp
I had for some time been under the mistaken impression that this could only occur in a scenario involving >2 *distinct* vats, and thus assumed it did not concern level 1 implementations. This patch adds some more comments calling out the fact that this is not the case.
> rpc.capnp: add a note clarifying the 4-way race

- c++/src/capnp/rpc.c++
Restoring the original change back since we don't think it was causing issues anymore.
Reverts capnproto/capnproto#1696
> Revert "Revert "capnp rpc: do not report shutdown error after read exception"

- c++/src/kj/timer.c++
It has been observed that in rare circumstances, clock_gettime may return a non monotonic timestamp even when using CLOCK_MONOTONIC. This triggers the assertion in "advanceTo", breaking applications built on top of the KJ library.
This commit removes the assertion for those platforms on which the problem has been observed (only Mac with x86 processor).
> Fix non-monotonic time on Intel Mac machines

- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Both bugs were abort propagation bugs, one affecting http-over-capnp, one affecting kj-http.
> WebSocket bugfixes

- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
It'd be nice to have a convenient way of creating `kj::Own`s for resources allocated by C APIs like `getaddrinfo`.
This is more of a suggestion. If there is already a way to do this or a suggested alternative approach, I'm all ears.
> Add kj::rawPtr()

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
When an exception propagated through a coroutine, the trace simply skipped the coroutine altogether, rather than reporting the locations of the co_awaits.
I've tested this manually but it's hard to write a unit test since KJ currently cannot symbolize stacks without outside help.
> Fix stack traces through coroutines

- c++/src/kj/compat/tls-test.c++
- c++/src/kj/test.h
For some reason our CI seems to declare (in the header) that it is v3, but the text it produces looks like v1. Maybe the header is a different version than the library? I don't actually care. Let's match both messages.
> Fix tls-test on Windows

- c++/src/kj/debug.h
- c++/src/kj/test.h
https://github.com/capnproto/capnproto/issues/1307#issuecomment-1182584709
Since MSVC does not support the gcc/clang statement expression extension, change KJ_REQUIRE_NONNULL to use the conformant iife strategy.
> Fix MSVC build with /Zc:preprocessor

- c++/src/kj/async-io-test.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Our recent http-over-capnp WebSocket abort propagation fix (in #1704) uncovered a latent bug in a downstream test runner, which treated the newly-correctly-propagating WebSocket abort as an application error. In order to fix that downstream bug, we need to use `handleApplicationError()` ... which turns out to be buggy. This PR fixes that bug.
I also included a drive-by fix from #1717.
> Fix WebSocket application error handling

- c++/src/capnp/message.h
- c++/src/kj/common.h
- c++/src/kj/timer.c++
@kentonv Turned out that `i386` (i.e. specifically 32-bit Intel) also needs the same arena fix.
Other two commits address issues already discussed.
For mutices, I requested @catap to take a look, and hopefully we will come up with a solution for them soon.
> Fixes for Darwin, second go

- c++/src/kj/mutex.c++
Very old macOS has a wired behaviour that statically initalized and not used pthread primites returns EINVAL on attempt to be destroyed.
calling `pthread_*_init` on not used objects fixes all such errors.
Closes: https://github.com/capnproto/capnproto/issues/1715
> Enforce call of `pthread_*_init`

- c++/src/kj/compat/http.c++
Most KJ errors are space-separated; "code=N" was atypical. This confused things that parse exception messages expect the usual format.
> Improve error string for WebSocket protocol errors.

- .github/workflows/quick-test.yml
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compiler/node-translator.c++
- c++/src/kj/common.h
- c++/src/kj/string.h
This PR:
- fixes a couple compiler warnings
- disables a few `operator!=()` implementations in C++20 mode to get Clang 16 working
- and ports our Musl build to Clang 16 -- partly to prove that Clang 16 works, and partly because we will soon need to when we require coroutines (GCC ICEs on our coroutines).
> Fix Clang 16 build

- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.h
This commit adds a function to AsyncIoStream that helps in the interoperability of the class with other libraries. It allows to reclaim ownership of a file descriptor from an AsyncIoStream. This can allow for example to use KJ ConnectionReceiver, but then use the file descriptors natively, or pass them to another library.
> Expose Win32 handle in AsyncIoStream interface

- c++/src/kj/common.h
The code in common.h for the definition of KJ_MSVC_TRADITIONAL_CPP was
active only in debug. However, it is used in debug.h even when not in
debug. Thus, while the fix worked for debug builds, it did not work
for release builds.
This was probably undetected because CI builds only Debug for MSVC.
> Define KJ_MSVC_TRADITIONAL_CPP also in Release

- c++/src/capnp/encoding-test.c++
- c++/src/capnp/membrane-test.c++
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/serialize-test.c++
- c++/src/kj/arena-test.c++
- c++/src/kj/array-test.c++
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/common.h
- c++/src/kj/compat/gtest.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/debug-test.c++
- c++/src/kj/exception-test.c++
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/filesystem-disk-win32.c++
- c++/src/kj/main.c++
- c++/src/kj/map-test.c++
- c++/src/kj/mutex-test.c++
- c++/src/kj/one-of-test.c++
- c++/src/kj/refcount-test.c++
- c++/src/kj/test-test.c++
- c++/src/kj/test.h
- super-test.sh
Also delete `kj::mvCapture()` as a drive-by.
> Remove no-exceptions mode.

- c++/src/kj/common.h
Type cast to char was supported since commit 98f9c8fca5c49f.
Signed-off-by: Jianyong Chen <baluschch@gmail.com>
> kj/common: remove obsolete comments on minValue and maxValue.

- c++/src/kj/async-inl.h
Split off from #1754, since it doesn't depend on how we implement coroutine parameter validation.
> coroutines: Add a `KJ_CO_MAGIC` define

- c++/src/capnp/blob.h
Fix #1622, #1752
With LLVM 17 and gnu++20, blob.h got 'invalid operands to binary expression' error.
This PR will fix that by swapping the elements.
```
capnproto/c++/src/capnp/blob.h:176:74: error: invalid operands to binary expression ('const char *' and 'kj::StringPtr')
176 | inline bool operator==(const char* a, const Text::Builder& b) { return a == b.asString(); }
|                                                                        ~ ^  ~~~~~~~~~~~~
```
> blob.h: Fix invalid operands to binary expression

- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
Should reduce the likelihood of stack overflow in cases involving very large TaskSets.
> Ensure TaskSet destructor unlinks Tasks, even when an exception occurs

- c++/src/capnp/compat/json.c++
- c++/src/capnp/compiler/evolution-test.c++
- c++/src/capnp/schema-loader.c++
- c++/src/capnp/serialize.c++
- c++/src/capnp/stringify.c++
- c++/src/kj/array-test.c++
- c++/src/kj/array.c++
- c++/src/kj/array.h
- c++/src/kj/async-io-unix.c++
- c++/src/kj/cidr.c++
- c++/src/kj/common.h
- c++/src/kj/debug.c++
- c++/src/kj/exception.c++
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/hash.h
- c++/src/kj/io.c++
- c++/src/kj/main.c++
- c++/src/kj/parse/char.c++
- c++/src/kj/string.h
We'd like to be able to use KJ_STACK_ARRAY in coroutines, but KJ_STACK_ARRAY uses variable-length arrays on compilers which support them (that is: GCC). ~~So, we're dropping support for VLAs from KJ_STACK_ARRAY.~~
It's worth noting that at present, we don't actually support GCC, so we have no target which even uses VLAs anymore. But, we'd like to support GCC again in the future, once its coroutine support is fixed.
Update: Instead of dropping support for VLAs from KJ_STACK_ARRAY, we're replacing the macro entirely with `kj::SboArray`.
> Replace KJ_STACK_ARRAY with kj::SboArray and kj::SboArrayBuilder

- c++/src/capnp/BUILD.bazel
- c++/src/capnp/compat/BUILD.bazel
- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/test-util.h
Follow-up to #1763.
The JSON test was mistakenly not included in the bazel build, so compile issues with it were not being detected. I fixed this locally to verify that the changes in the previous PR are correct, but didn't have them cleaned up yet.
For the benchmark, this is largely similar to the workerd JSON benchmark, but uses a different test message for the parsing test.
Suggestions for how to structure the benchmark are welcome – not sure if adding more complex tests, removing KJ_EXPECT statements or moving this to a new file would be helpful.
> Include JSON test in bazel build, support compiling it, add simple benchmark

- c++/src/kj/async-io-test.c++
for some environments the previous one was not huge enough fixes #1781
> async-io-test: increase huge buffer

- c++/src/kj/async-test.c++
...in configurations where we can't test stack limits with fibers but can test them with pthreads.  Also, exercise the pthreads-based code where possible, to reduce the likelihood of future breakage.
> Fix compilation of async stack limit tests

- c++/src/kj/compat/http.c++
The reference to the inner output stream provided by HttpChunkedEntityWriter's base class's getInner() can be invalidated before the HttpChunkedEntityWriter. To put it another way, body streams which we provide to user code (the HttpChunkedEntityWriter) can be prolonged by the user beyond the lifetime of the underlying connection. getInner() is written in such a way to catch the issue, by checking for validity before returning a reference, and I think the tryPumpFrom() implementation probably should call it after every resumption.
> http: Call getInner() after every co_await in HttpChunkedEntityWriter

- c++/src/capnp/BUILD.bazel
this way we won't need to exclude it everywhere
> mark fuzz_test as manual

- c++/src/capnp/compat/std-iterator.h
Per [\[input.iterators\]](http://eel.is/c++draft/tab:inputiterator), `*a` should return `reference`. `IndexingIterator::operator*` returns `Element`, not `Element&`, so `reference` should be `Element`, not `Element&`.
This is usually not a problem; we only noticed it because the following code started breaking when using libstdc++ debug iterators `_GLIBCXX_DEBUG` https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html:
```c++
#include <vector>
#include <capnp/compat/std-iterator.h>
void f(capnp::List<int>::Reader l) {
std::vector<int> v;
v.insert(v.end(), l.begin(), l.end());
}
```
```
$ g++ -std=c++20 -D_GLIBCXX_DEBUG a.cpp -I c++/src
In file included from /opt/gcc-13.1.0/include/c++/13.1.0/debug/debug.h:141,
from /opt/gcc-13.1.0/include/c++/13.1.0/bits/stl_algobase.h:69, …
```
> iterator_traits<IndexingIterator>::reference should not be a reference

- c++/src/kj/common.h
Now array.slice(1234) will return a slice from 1234 to the end of the array, this is the same behaivor as kj::StringPtr's slicing.
> Add single param slice to arrays

- c++/WORKSPACE
- c++/src/kj/array.h
- c++/src/kj/async-coroutine-test.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/async.h
- c++/src/kj/common-test.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/test.h
Ignoring a promise is almost never intentional. Now it generates a compiler warning.
If you do want to ignore a promise, call `Promise::ignore()`. It does nothing but appease the compiler.
> Warn when ignoring a Promise.

- c++/src/kj/array.h
- c++/src/kj/exception.c++
We originally merged this in my earlier SmallArray PR, which we had to revert. We should still make this change, though, so I'm submitting it separately, to try to isolate it from whatever the issue with the SmallArray PR was.
> Make Array destructor noexcept(false)

- c++/src/kj/compat/http.c++
This will hopefully make debugging somewhat easier.
If the changes to the conditions on length are undesired, I can instead add an originalLength field.
> Add the expected and actual content length in http.c++ exception

- c++/src/kj/array.h
- c++/src/kj/exception.c++
This reverts commit 14c4469ee4b89ee89eb5ec11ef28ca5f9d03d3dc.
This seems to expose a bug downstream in the Workers runtime, reverting for now.
> Revert "Make Array destructor noexcept(false)"

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Replaces assertion in `readHeader` with protocol error propagation. I have stopped these errors with assertions in places where appropriate error handling isn't available. 
Returning the error takes special care to give client a chance to read it before dropping the connection.
> gracefully handling http 431 error

- c++/WORKSPACE
- c++/src/capnp/blob.h
- c++/src/kj/string.h
Hello,
Here is a fix I would be interested to have in the v1 branch (I guess it applies to v2 too) to fix some build issues.
The issue is on a "legacy" codebase with `using namespace boost::filesystem in header files and combined with a recent boost version (1.82).
I considered multiple fixes but I feel like the proper one would be if KJ was stricter in its std::string interop.
> less ambigous STL string interop SFINAE

- c++/src/capnp/compiler/capnp.c++
- c++/src/kj/filesystem-disk-test.c++
Those issues are found on a machine that have i-node(file or directory) number exceeding 2^32:
https://github.com/capnproto/capnproto/blob/c3b4b54f22f11b57e057e1aacd937d83fc9ba5c0/c%2B%2B/src/capnp/compiler/capnp.c%2B%2B#L444-L445
coming from `capnproto.c++`
```
libtool: link: g++ -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -O2 -DNDEBUG -DKJ_USE_FIBERS -o .libs/capnp src/capnp/compiler/module-loader.o src/capnp/compiler/capnp.o  ./.libs/libcapnpc.so ./.libs/libcapnp-json.so ./.libs/libcapnp.so ./.libs/libkj.so
./capnp compile --src-prefix=./src -o./capnpc-c++:src -I./src $(for FILE in src/capnp/test.capnp src/capnp/test-import.capnp src/capnp/test-import2.capnp src/capnp/compat/json-test.capnp; do echo ./$FILE; done) …
```
> Fix stat overflow on x86_32bit

- c++/src/capnp/generated-header-support.h
- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/async-coroutine-test.c++
- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
- c++/src/kj/common.h
- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.h
- c++/src/kj/exception.c++
- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
- c++/src/kj/one-of.h
- c++/src/kj/source-location.h
- c++/src/kj/string-test.c++
@kentonv 
This is continuation of the effort from #1814. Following your recommendations, I cherry-picked the few commits from `v2` branch which were addressing the issues I saw when building `release-1.0.1` with MSVC with C++20 standard.
I had to put one fix from @harrishancock (aa4d3699fc7c7a1524d377f55494fb2b7134592f) into a conditional compiled block as the fix only worked with higher C++ standard than C++14 which `v1` targets.
I tested this on MSVC v193 (VS2022) compiling with C++14, C++17, C++20 and it works - sort of.
The problem I found is that the `Release` build crashes in `kj-heavy-tests.exe` in particular in `async-test.c++` and `fiber pool limit`. What makes it a bit hard to debug is the fact that it only crashes in the release build (the `Debug` runs fine and even …
> Fix MSVC with C++20 on 1.x branch.

- c++/src/kj/string-test.c++
- c++/src/kj/string.c++
- c++/src/kj/string.h
While it's possible to implement `find` (and therefore, `contains`) with a few lines of code, I'd rather implement them in `kj` so we can share the implementation more widely.  See issue #868.
This is a simple implementation that uses memmem on platforms that provide that function and a naive algorithm on other platforms.
> Implement find and contains for kj's String, ConstString, and StringPtr classes

- c++/src/kj/compat/tls-test.c++
- c++/src/kj/mutex-test.c++
- c++/src/kj/test-helpers.c++
- c++/src/kj/test.h
Now that we have StringPtr::contains, hasSubstring is redundant.
Inspired by issue #868.
> Remove hasSubstring in favor of StringPtr::contains

- c++/src/kj/async-io-test.c++
- c++/src/kj/debug-test.c++
- c++/src/kj/exception-override-symbolizer-test.c++
- c++/src/kj/exception-test.c++
We can replace uses of strstr with StringPtr::contains and StringPtr::contains
Inspired by issue #868.
> Clean up uses of strstr in tests

- c++/src/kj/cidr.c++
Without this, the following build error occurs:
```
➜  build git:(v2) ✗ ninja
[1/48] Building CXX object c++/src/kj/CMakeFiles/kj.dir/cidr.c++.o
FAILED: c++/src/kj/CMakeFiles/kj.dir/cidr.c++.o
/usr/local/bin/clang++17  -I/home/alex/software/capnproto/c++/src -g -std=gnu++20 -Wall -Wextra -Wno-strict-aliasing -Wno-sign-compare -Wno-unused-parameter -pthread -MD -MT c++/src/kj/CMakeFiles/kj.dir/cidr.c++.o -MF c++/src/kj/CMakeFiles/kj.dir/cidr.c++.o.d -o c++/src/kj/CMakeFiles/kj.dir/cidr.c++.o -c /home/alex/software/capnproto/c++/src/kj/cidr.c++
/home/alex/software/capnproto/c++/src/kj/cidr.c++:116:71: error: member access into incomplete type 'const struct sockaddr_in6'
116 |         otherBits = reinterpret_cast<const struct sockaddr_in6*>(addr)->sin6_addr.s6_addr;
| …
```
> Fix build on FreeBSD

- c++/src/capnp/capability.h
I found this while reading the header file.  ispell didn’t find any other misspelled words.
> Fix typo in capability.h

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
The `isCompressed` bit is captured but not used in this case. Instead of #ifdefing it out, I went ahead and used it to provide a nice error message.
This should fix the musl build.
> Fix compiler warning when zlib not available.

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
String, StringPtr, Array, ArrayPtr gain as<T>() method which is a syntax sugar for T::from(this).
This enables defining conversion domains (such as Std in tests) and use `.as<Std>()` chained calls for more fluid expressions.
> as<T>() syntax sugar methods for primitive types

- c++/src/capnp/compat/BUILD.bazel
- c++/src/capnp/compat/json-rpc.c++
- c++/src/capnp/compat/json-rpc.capnp
json-rpc and json-rpc-test were not included in bazel so far. Adding the test to bazel resolves an internal issue (EW-6927).
> Add json-rpc-test in bazel

- c++/src/kj/filesystem-test.c++
- c++/src/kj/filesystem.c++
- c++/src/kj/filesystem.h
In this mode, InMemoryDirectory works as normal, but when it creates a File, instead of using InMemoryFile, it uses DiskFile wrapping a memfd.
This creates a nice compromise for writing tests of code that depends on files being backed by real file descriptors, but does not need the same for directories.
(If we wanted similar functionality on other operating systems, we could create an InMemoryFileFactory that backs files with anonymous temporary files on disk...)
**Also in this PR:** Fix InMemoryDirectory deadlock bug.
(Some SRS tests I'm writing require both of these changes.)
> Allow InMemoryDirectory to be backed by memfds

- c++/src/kj/filesystem.c++
- c++/src/kj/filesystem.h
I noticed a few of these while reading https://github.com/capnproto/capnproto/pull/1889/files.
> Typos and whitespace fixes for the filesystem files

- c++/src/kj/string-test.c++
- c++/src/kj/string.h
- Remove usage of designated member assignment in StringPtr::attach
- Test StringPtr::attach lifetimes (same as ArrayPtr::attach)
> Fix compilation error for c++14 and c++17 and add tests

- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.h
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
- c++/src/kj/async-unix.h
- c++/src/kj/timer.c++
- c++/src/kj/timer.h
This makes it possible to use UnixEventPort inside a thread running some other event loop, by arranging for that other event loop to listen for the UnixEventPort's epoll FD becoming ready. Whenever it does, the application must pump the KJ event loop.
This also could allow multiple event loops to run in the same thread, or even across some thread pool, as long as only one event loop is active in a thread a time, and each event loop is active in no more than one thread at a time. A scheduler could schedule event loops to threads when their epoll FD becomes ready. 
**Reviewer:** Be sure to read the headers first, they explain a lot of what's going on.
> Extend UnixEventPort on Linux to allow external polling.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
A buffer was read after being freed when two unusual things happened together: 1) Some of the initial connection content arrived immediately with the HTTP response headers, causing there to be a `leftover` buffer. This is rare because the response headers would normally be returned when the connection was opened, but the nature of TCP doesn't allow the server to return any bytes until an additional network round trip has occurred. 2) The application tried to read with a `minBytes` greater than the size of this leftover. (This is unusual because most use cases set `minBytes` to 1, which can't possibly be larger than a non-empty leftover size.)
In this case, the leftover's backing buffer was destroyed, but the ArrayPtr pointing into it was not reset, so the next read would try to read it …
> Fix leftover handling in HTTP CONNECT implementation.

- c++/src/kj/async-inl.h
- c++/src/kj/common-test.c++
- c++/src/kj/common.h
Allows a type to be explicitly marked in a way that prevent it from being passed into a kj promise coroutine as an arg.
```
class Foo {
private:
KJ_DISALLOW_IN_COROUTINE();
};
kj::Promise<void> simpleCoroutine(Foo foo) { // Compile Error!
co_return;
}
kj::Promise<void> simpleCoroutine2(Foo& foo) { // Compile Error!
co_return;
}
kj::Promise<void> simpleCoroutine3(Foo* foo) { // Compile Error!
co_return;
}
```
> Add new KJ_DISALLOW_IN_COROUTINE mechanism

- c++/src/kj/compat/http.c++
This should cause us to stop logging spurious sentry issues for client errors.
> On WebSocket handshake errors, throw DISCONNECTED at server.

- c++/WORKSPACE
The zlib.net host eagerly deletes older zlib releases as they become obsolete, this can cause unexpected build failures whenever there is a new zlib version.
> Update to zlib 1.3.1, switch to fetching from GitHub

- c++/src/kj/async-io.c++
This is essentially the same as #1859 but extended to the two other `teeException*` helpers which I for some reason failed to notice when creating the original fix.
> Fully fix exception-masking bug in async pipe.

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Prior to this commit, `WebSocket::getPreferredExtensions()` had a default implementation, which meant derived classes would not be required to implement the method themselves.
Derived classes probably shouldn't refer to some default implementation, so we require it to be implemented going forward.
> Make getPreferredExtensions pure virtual func

- .github/workflows/quick-test.yml
- c++/build/configure.bzl
- c++/src/capnp/cc_capnp_library.bzl
- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/compiler/compiler.c++
- c++/src/capnp/serialize-async.c++
This mirrors the cc_library off-by-default changes in workerd and edgeworker, also includes some minor cleanup. Also see the workerd and downstream branches felix/refactor-012624 and felix/lib-off-by-default.
> [nfc] Assorted build system cleanup

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
WebSocketImpl already knows what to do with a custom error handler; this PR just adds plumbing.
> Allow custom WebSocket error handlers for kj::HttpClient.

- c++/src/kj/table.h
This constructor is currently unused, so the current issue has no immediate impact.
Signed-off-by: Jianyong Chen <baluschch@gmail.com>
> kj/table: fix the initialization of BTreeImpl::MaybeUnit with uint.

- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
Fixes potential read-after-free that can happen if the connection's shutdown() method throws an exception.
> capnp-rpc: retain RpcConnectionState reference in error handling lambda

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
Empty AggregateConnectionReceivers work fine, except those methods which access the first entry.
> check for empty AggregateConnectionReceiver

- c++/src/capnp/arena.h
- c++/src/capnp/capability.h
- c++/src/capnp/rpc.c++
- c++/src/kj/async.h
- c++/src/kj/common.h
- c++/src/kj/exception.c++
I came across a few typos while working on https://github.com/capnproto/capnproto/pull/1460, and I thought it wouldn't hurt to share them :blush:.
Feel free to just close if it is irrelevant.
> nitpick: fix a few typos in the comments

- c++/src/kj/compat/http.c++
This error log is necessarily followed by a use-after-free later on that can be nasty. We should crash eagerly instead.
> In ~ConcurrencyLimitingHttpClient(), crash more eagerly.

- c++/src/capnp/compat/byte-stream-test.c++
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/byte-stream.h
This makes it so the application can choose to implement ExplicitEndOutputStream in order to get explicit end() calls from the byte-stream implementation.
We already supported the other direction: having the application request an ExplicitEndOutputStream when converting from a ByteStream capability.
> byte-stream: Allow ExplicitEndOutputStream in other direction.

- .github/workflows/quick-test.yml
The capnproto pendant to https://github.com/cloudflare/workerd/pull/1646. This is necessary based on the upcoming node 16 deprecation (https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
Capnp equivalent of https://github.com/cloudflare/workerd/pull/1646
> [CI] Update actions/checkout to v4

- c++/src/kj/filesystem-disk-unix.c++
The title pretty much says it. INFO messages are not printed by default, so changing the log message from WARNING to INFO suppresses it by default. 
The issue was that this warning was printing inside a container and in a CICD pipeline when it was not needed and unwanted since processes were monitoring stderr and tests were failing as a result.
> Fix for issue 1976 - Changed warning to info for log message causing unwanted/unneeded prints

- c++/src/kj/exception-test.c++
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
Compared to #1975, this version maintains a very simple map of type IDs to bytes.
I actually decided that the fancy templating and expectation of serialize/deserialize methods doesn't work. In our specific case, serialization and deserialization wolud require a V8 isolate lock to operate, and there may be use cases where we'll want to detach the bytes without deserializing them. Better to let the caller get access to the raw bytes and use them as they see fit.
> Add exception detail API.

- c++/src/kj/memory-test.c++
- c++/src/kj/memory.c++
- c++/src/kj/memory.h
`Pin<T>/Ptr<T>` pair is designed to replace `T/T&` usage with additional runtime checks for T's lifetime.
> kj::Pin<T>, kj::Ptr<T> smart pointers

- c++/src/kj/async-unix.c++
> Use kj::none in the poll(2) implementation of UnixEventPort.

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
We have the single-parameter slice methods in ArrayPtr and they’re
really convenient.  While it’s always possible to use Array::asPtr()
to convert an Array to an ArrayPtr, that’s extra noise when we could
add these methods on Array directly.
> Add Array::slice(start) methods

- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/json-test.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/exception-test.c++
It is very common to create literal byte sequences (even more so after IO api change), _kjb utility
removes some noise.
> ""_kjb byte array pointer literal 

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This is very useful when working with local buffers.
> arrayPtr() utility for fixed-sized arrays

- c++/src/kj/array-test.c++
These tests fail in “release” mode because they use KJ_IREQUIRE and KJ_IREQUIRE doesn’t fire in release mode.
> Run Array::slice throw tests in only debug mode

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This is another memset alternative: `kj::ArrayPtr::fill()` function.
The implementation uses memset for small T and normal for-loop otherwise which should be easy to vectorize.
> kj::ArrrayPtr<T>::fill()

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This PR introduces `kj::memzero<T>()` utility to 0-initialize memory. It is intended to be used as a type-safe alternative to some usages of `memset` (other additions are coming).
The provided `kj::memzero<T>(T&)` version works for normal storage as well as for arrays.
An alternative design is to define `kj::memzero<T>(T*)` but that wouldn't let us provide array version and is
less type-safe (because you can pass array to it).
> kj::memzero<T>() - zero-initialize memory region

- c++/src/capnp/capability.c++
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/rpc.c++
- c++/src/kj/async.c++
- c++/src/kj/common.h
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/readiness-io.h
- c++/src/kj/timer.c++
While reading some code in async.c++, I noticed a place where we nullify a Maybe with a nullptr, which surprised me, because I thought we had deprecated all such code. It turns out that while our default Maybe<T> implementation bans pointer assignment,  our Maybe<T&> specialization does not. This commit adds a deprecated nullptr assignment operator overload to Maybe<T&> to flush out any last remaining nullptr nullifications.
Note that this doesn't fix any bug in our code or anything, it just makes the nullification call sites a bit clearer.
> Fix Maybe nullptr assignment deprecation notice loophole

- c++/src/kj/main.c++
- c++/src/kj/main.h
- c++/src/kj/test.c++
In a test that I wrote using threads, I noticed my test program still succeeded (by exiting with a 0 return code) when the program logged an ERROR-severity log message in the non-main thread.  This happens because TestExceptionCallback does not implement getThreadInitializer, so we get a default RootExceptionCallback.  The RootExceptionCallback will write errors to stderr, but doesn’t inform the ProcessContext that an error has occured and the process should exit with a non-zero return code.
The way to fix this is to implement getThreadInitializer in TestExceptionCallback.  My implementation is simple: in a new thread, I construct a new TestExceptionCallback and then run the thread’s main function.
Tehnically, such a construction is not thread-safe because the ProcessContext we use isn’t …
> Initialize TestExceptionCallback in new threads

- c++/src/kj/common.h
- c++/src/kj/compat/brotli.c++
- c++/src/kj/compat/gzip.c++
Should reduce noise in stack traces, and also ensures that clang will tell us if future code changes inadvertently prevent tail call optimization.
> Add clang::musttail attributes to a couple recursive calls

- c++/src/capnp/rpc.c++
- c++/src/kj/array.h
Fixes an instance of undefined behavior when calling `releaseAs*()` on a kj::Array that has been allocated using a nullptr to indicate an empty array and thus has a nullptr disposer.
There might be more places where releaseAs is used in this way and a better way to fix this, open to suggestions here but also want to ship this soon.
Added a second commit to fix a remaining issue. Also see the downstream branch.
> Fix undefined behavior violations

- .github/workflows/quick-test.yml
I look at https://github.com/capnproto/capnproto/commits/v2/ and it doesn't seem that we have builds enabled.
> enable CI on v2 branch

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
For trivial types, heapArray returns unitialized memory, which could be a security issue.
While the implementation is possible for non-trivial types, it is less of an issue and will probably be seldom used.
As an alternative I could suggest `heapZeroArray()` and provide only zero-initialized heap arrays.
> heapArray filled version

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This is a common operation when dealing with IO.
> kj::arrayPtr<T>(T &t) creates a single-element array pointer

- .gitignore
one day we might want to provide our configuration, but ignore this folder for now.
> ignore .vscode/ folder

- c++/.bazelrc
- c++/CMakeLists.txt
- c++/Makefile.ekam
- c++/ekam-build.sh
- c++/samples/calculator-client.c++
- c++/samples/calculator-server.c++
- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.c++
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/test-util.h
- c++/src/kj/async-io.h
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/tls.h
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/memory-test.c++
- c++/src/kj/test-helpers.c++
- c++/src/kj/thread-test.c++
- c++/src/kj/timer.h
- super-test.sh
Having override annotations in place greatly helps with API
refactorings. I also believe this is a commonly accepted coding
practice.
> enable -Wsuggest-override

- c++/build/configure.bzl
These are obsolete after #1944 and break `bazel cquery 'deps(//...)'` since the corresponding bool_flags are no longer available.
> [nfc] Clean up remaining lock blocking tracking bazel configuration

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
The original implementation can't be used because of cast limitations: https://godbolt.org/z/fWb7ncrh5
This version casts each character separately to achieve the goal (by @harrishancock)
> supporting constexpr _kjb suffix

- .github/workflows/quick-test.yml
Be more intentional about what dependencies we use. This should make CI run a bit faster.
> [CI] Reduce set of build dependencies

- doc/otherlang.md
Hi, thank you for the project.
I'd like to propose adding link to [Cap'n Proto RPC Tracer](https://github.com/toyota-digital-cockpit-pf/capnp-trace) in Tools section.
[Cap'n Proto RPC Tracer](https://github.com/toyota-digital-cockpit-pf/capnp-trace) can trace Cap'n Proto RPC like `strace` command.
Roughly speaking, this tool sniffs Unix Domain Socket communication by `ptrace` and `process_vm_readv`,
and deserialize it with `capnp::SchemaLoader`.
I believe this tool can be useful for Cap'n Proto users.
> Website: Add link to RPC Tracer

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
Some people use these address ranges -- especially 240.0.0.0/4 -- as private networks. Is this wise? I dunno. Here's a blog post with extended discussion:
https://blog.benjojo.co.uk/post/class-e-addresses-in-the-real-world
KJ previously totally disallowed use of these ranges. With this change, they are now allowed, but not considered part of any of the named groups (public/private/network/local) -- you have to allow them explicitly.
Note that this also means that these addresses will now be allowed by the default network when no filter has been applied. I think this is OK because if you haven't appplied a filter at all you presumably trust your addresses.
> Allow reserved address ranges to be explicitly allowlisted in network filters.

- c++/src/kj/async.c++
This attaches a name to the relevant entries in /proc/<pid>/smaps.
> Set name for anonymous virtual memory areas allocated for fiber stacks.

- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
- c++/src/capnp/membrane.c++
- c++/src/capnp/reconnect.c++
- c++/src/capnp/rpc-prelude.h
- c++/src/capnp/rpc.c++
- c++/src/kj/hash.h
Just a series of small cleanups and refactors, mostly of `rpc.c++`, some of them leading up to three-party handoff although no actual 3PH logic is implemented yet.
Be sure to read each commit separately.
> Various RPC refactoring and cleanup

- c++/src/capnp/compiler/capnpc-c++.c++
This change is tested by compilation failures when it is implemented incorrectly.
> capnpc-c++.c++: memcmp == 0 -> arrayptr ==

- c++/src/capnp/any.c++
These two cases are tested in `any-test.c++:307: legacy test: Any/Equals`.
> any.c++ memcmp == 0 -> ArrayPtr ==

- c++/src/capnp/compiler/module-loader.c++
This is in the compiler and isn't a tested case, I think this small change is fine, however if we want a more tested compiler we'd need to invest in a proper framework for that.
> load-module.c++ memcmp == 0 -> ArrayPtr equality

- c++/src/kj/debug.c++
This is tested in `debug-test.c++:398: legacy test: Debug/Context`.
> debug.c++ memcmp == 0 -> ArrayPtr equality

- c++/src/kj/hash.h
- c++/src/kj/table-test.c++
- c++/src/kj/table.c++
- c++/src/kj/table.h
Previously, `hashCode()` merely needed to return a value that was likely to be unique. When the input was already a 32-bit integer, it was acceptable to just return exactly the input value. However, this meant that the distribution of hashes wasn't necessarily uniform. To compensate for this, the hashtable implementation would use prime-number bucket counts. This, however, made computing the correct bucket expensive, as it required an integer division operation.
After this change, `hashCode()` is expected to return a uniform distribution. Thus, hashtables can have power-of-two size, avoiding the integer division. This improves performance in our string-keyed hashtable benchmark by 10%. The integer-keyed benchmark is slower, due to the need to spend more cycles computing hashes, but …
> Improve hashCode().

- c++/src/capnp/rpc.c++
- c++/src/kj/async-coroutine-test.c++
- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-win32-test.c++
- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
**Rationale**
This PR introduces a series of patches related to promises that are intended to reduce code size and compile times.
Investigating the slow compile time of `kj/compat/http.c++` led me to look at the generated object file – it turns out that it defines ~15,000 symbols in ~8,000 lines on Darwin when optimization/inlining is disabled (< 5,000 symbols with -O1 enabled). This is believed to be a major driver of its slow compile time and code size. Looking at the generated object symbol names with [bloaty](https://github.com/google/bloaty) showed that many symbols are functions of the templated `TransformPromiseNode` class in `kj/promise.h`. This class is used in promise continuations (among other things), causing dozens of templated functions to be defined with every `then()` …
> Rework promise continuations to reduce amount of templated functions, code size

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
Adds a new overload of ArrayPtr::fill that takes another ArrayPtr as an argument. This is useful for cases where we want to fill the target with a sequence of values rather than a single repeated value.
> Add ArrayPtr fill(ArrayPtr<T>) variant

- c++/src/capnp/capability-test.c++
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/kj/async.c++
That should actually cover the remaining evalLater()/evalLast() calls that can be simplified, please correct me if I'm wrong.
> [nfc] Convert remaining evalLater() calls to yield where possible

- c++/src/capnp/dynamic-test.c++
- c++/src/capnp/dynamic.c++
- c++/src/capnp/test-util.h
- c++/src/kj/io.c++
This fixes #1980 and #2067 and adds a test case that would have fired on #2067. Based on master because I still work on v1 and didn't want to port it forward and back again.
> Fixes for group assignment in dynamic API and BufferInputStreamWrapper::tryRead

- c++/src/capnp/capability.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/capnpc-capnp.c++
- c++/src/capnp/schema-loader.c++
- c++/src/capnp/schema-parser-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/io.c++
- c++/src/kj/time.c++
- c++/src/kj/timer.c++
This is more consistent and allows us to eliminate the large <algorithm> header in some places. I am assuming that both of these are functionally equivalent.
\- Drop unused AsyncOutputStream in http.c++
\- Clean up a few unused STL headers
\- I needed this for a downstream change to add _LIBCPP_REMOVE_TRANSITIVE_INCLUDES there, c++/src/kj/timer.c++ should either be including <algorithm> or not using std::max
> [nfc] Replace std::min/max with kj::min/max

- c++/src/capnp/rpc-prelude.h
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc-twoparty.h
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.h
- c++/src/kj/async-coroutine-test.c++
- c++/src/kj/debug-test.c++
- c++/src/kj/exception.c++
The last (main) commit of this PR adds an API by which the RpcSystem will inform the VatNetwork when a connection is "idle", meaning it has no active calls or capabilities on it in either direction.
This gives us a reasonable way to shut down connections that are "done", which will enable us to switch over to a connection-per-session approach rather than our current connection-per-destination approach. This will in turn be important to make three-party handoff work well.
> RPC: Implement idle hints and other refactoring

- c++/compile_flags.txt
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
I was just sort of messing around with promise ordering, trying to use depth-first scheduling in more cases, and it revealed some bugs.
In a big of a yak shave, I ended up changing `WebSocket::disconnect()` to be synchronous, which I've wanted to do for a while.
> Make WebSocket::disconnect() synchronous and fix some obscure promise ordering bugs

- c++/src/capnp/rpc-prelude.h
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.capnp
- c++/src/capnp/rpc.h
- c++/src/capnp/schema-test.c++
- c++/src/capnp/schema.c++
- c++/src/capnp/schema.h
- c++/src/capnp/test-util.c++
- c++/src/capnp/test-util.h
- c++/src/capnp/test.capnp
Just deleting some APIs that have been marked deprecated for a long time (and updating tests that were still using said APIs).
> Delete some deprecated stuff

- c++/src/capnp/blob.h
- c++/src/capnp/compat/std-iterator.h
- c++/src/capnp/compiler/capnp.c++
- c++/src/capnp/dynamic-test.c++
- c++/src/capnp/dynamic.c++
- c++/src/capnp/test-util.h
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.h
- c++/src/kj/cidr.c++
- c++/src/kj/common.h
- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/io.c++
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
I was curious if the v2 branch was missing any important changes that were contributed to the master branch and reviewed all code changes present on master but not on v2 – turns out that this largely consists of smaller changes that are not very relevant to downstream projects, so there's **no need to prioritize** porting them. I still wanted to track them here so we don't lose them. I'm not sure if cherry-picking the changes individually is even the right approach for this, but this should include all relevant code changes as of writing. 2a9ba4eca3253a3e53ac91b6aefaa7e0f9475474 which fixes compilation errors for recent compilers is not included as we already resolved that differently.
Cherry-picked commits:
9da0b118049cbf017935ac20a04a9aa5bbc54514
2d41340e102607d4478b7b79d0dcfe5fdd7f67be …
> [RFC] Backport v1.x fixes to v2

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/string.h
ArrayPtr comparators  are implemented by implementing `operator<` and `operator==`.
This was chosen over `operator<=>` or spaceship as that generally requires the `compare` header which was deemed to include too much of stdlib and thus make compilation times less under our control.
> Support comparators for ArrayPtr and refactor StringPtr to use them internally.

- c++/src/kj/refcount.h
T* get() 
People have asked for it, and it makes migrating easier. The only danger is using addRef(T&) again, but that is on the implementer to carefully analyze the usage.
> kj::Rc and kj::Arc escape hatches

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
I've observed null pointer dereferences with stack traces showing CoroutineBase::tracePromise() calling into ChainPromiseNode::tracePromise(). The only explanation I could think of is that perhaps the coroutine's tracePromise() function is being called after a currently-awaited ChainPromiseNode has transitioned to STEP2, which could invalidate the promiseNodeForTrace reference stored in AwaiterBase. To fix this, I'm storing a reference to the currently-awaited OwnPromiseNode, rather than to PromiseNode directly.
I tried to modify async-coroutine-test.c++'s trace test case to validate this change (by modifying the awaited .then() promise to return NEVER_DONE, and tracing after fulfilling the base promise on which .then() was called), but was unable to reproduce the buggy behavior. I'm open …
> Attempt to fix an obscure tracePromise() UaF

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This should force comparisons with `memcmp` much easier to manage because it is very easy to force now.
> Add `asBytes` functions to easily convert to ArrayPtr<byte>

- c++/src/capnp/common.h
- c++/src/capnp/layout.c++
Fixes misspelled constant name that was introduced in #437.
> MAX_STUCT_DATA_WORDS -> MAX_STRUCT_DATA_WORDS

- c++/src/kj/array.h
- c++/src/kj/common.h
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
This pull-request adds `constexpr` qualifier to kj::string* methods just like `std::string_view` and other string classes have. The goal of adding `constexpr` is to add support for evaluating the value of the expression on the runtime and as a result, improve the performance. Prior to this change, any function that calls the changed methods in this pull-request, can't add a `constexpr` qualifier due to the lack of support.
> make kj::string* methods constexpr

- c++/src/capnp/capnp_gen.bzl
- c++/src/capnp/cc_capnp_library.bzl
Rust and js rules basically copy it and are not compatible with each other. By having reusable implementation not only language rules are simpler, but they will also support language-independent deps because they will share provider.
No functional change at all, just a copy-paste + attr rename
> [nfc] extracting bazel capnp_gen rule

- c++/src/kj/timer.c++
The issue was originally observed only on Macs with intel processor, and it was believed to affect only those. However the issue has been observed on a Mac with M2 processor, thus the need to relax the preprocessor directive.
> Fix non-monotonic time on all Mac machines

- c++/src/capnp/rust_capnp_library.bzl
Generated code expects it too be available under `crate::capnp`
> [rust] import capnp crate in rust_capnp_library.bzl

- c++/src/kj/encoding.c++
Optimize `kj::encodeHex()` by allocating the string up front to avoid allocating memory for every input byte. This drastically improves performance, even when optimization is enabled. A number of downstream tests that include large text files benefit from this.
It is trivial to get another performance improvement by looking up a byte at a time in a larger lookup table but this is "good enough" for our needs.
> Make kj::encodeHex() go brrrrr

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async-unix-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
This goes further than kj::yieldUntilQueueEmpty() by also making sure the OS-level I/O queue (e.g. `epoll`) is empty.
Also in this PR: EventLoopLocal, which is like thread_local but attached to the current EventLoop.
Hint: These are things needed for implementing green threads.
> Add kj::yieldUntilWouldSleep() and EventLoopLocal

- c++/src/kj/CMakeLists.txt
- c++/src/kj/compat/BUILD.bazel
- c++/src/kj/compat/tls.c++
Under windows SSL_CTX_set_default_verify_paths doesn't populate the trusted ca store with all the trusted CAs. This commit should fix the error.
> Fix useSystemTrustStore behaviour in Windows

- c++/src/kj/io.c++
Fixes #2187.
Unsure how to test this as making unit tests allocate multiple gigs of RAM and then try to write them to a file doesn't seem like a great idea.
> Clamp writes on bad OSes that get confused by sizes greater than INT32_MAX.

- c++/src/kj/async-io-win32.c++
Silences the following compiler warning:
```
src/kj/async-io-win32.c++(355,16): warning: 'getWin32Handle' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
```
> Silence compiler warning about missing override identifier

- c++/src/capnp/BUILD.bazel
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/configure.bzl
**Motivation**
For downstream projects, parsing capnproto headers is a major factor in slow compile times. This is mediated by capnproto definitions being compiled to classes with many sub-classes and functions, including templated ones; defining sub-classes which can't be forward declared; and relying on recursively including generated headers. Based on compiler profiling, parsing generated capnp headers is disproportionately more expensive than parsing other headers; I assume having many small functions plays a role here. On many downstream source files that include capnp headers, the compiler spends more time parsing capnp headers than doing anything else, including codegen.
**Proposed change**
capnpc-c++ translates capnp files to a C++ source and header file. Most class methods are …
> [build][perf][capnpc] Move function definition in generated capnp files out of headers

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
On certain systems, such as NetBSD, the `AI_V4MAPPED` flag is not defined in the `netdb.h` header.
See: https://man.netbsd.org/getaddrinfo.3
Should be ported to the `master` and `release-1.0.*` branches.
Fixes https://github.com/capnproto/capnproto/issues/2201.
> Check for `AI_V4MAPPED` before usage

- c++/samples/CMakeLists.txt
As per the CMake document, we should call the cmake_minimum_required() command at the beginning of the top-level CMakeLists.txt file even before calling the project() command.
> Fix warning: cmake_minimum_required() should be called prior to this top-level project()

- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
- c++/src/capnp/compat/http-over-capnp.c++
Unfortunately I don't understand how this could be happening but I'm pretty sure it's benign. See comment for the full story.
This is currently the most prolific error log in production.
> Silence log: "capability was revoked  (RevocableServer was destroyed)"

- c++/src/kj/refcount-test.c++
- c++/src/kj/refcount.h
These two functions allow the user to release and later reacquire ownership of a kj::Arc<T>. This is useful for transporting an Arc across an FFI boundary, where we might only be able to pass a raw pointer.
I'm using this in a downstream PR, https://github.com/cloudflare/workerd/pull/3280, to avoid a nasty hack.
> Add Arc::disown() and Arc::reown()

- doc/otherlang.md
Hi, thank you for the project.
I'd like to propose updating [the link to RPC Tracer in Tools section](https://capnproto.org/otherlang.html#:~:text=by%20%40xmonader-,RPC%20Tracer,-by%20%40t%2Dkondo).
When I've added the link in #2054 , the repository was hosted in [toyota-digital-cockpit-pf](https://github.com/toyota-digital-cockpit-pf/) organization.
But now, I can use [Toyota](https://github.com/Toyota) organization and transfer the repository into it.
This modification is not mandatory because GitHub redirects the access to legacy URL automatically.
However just I want to clean it up.
> Website: Update link to RPC Tracer

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
Originally, nesting the Awaiter class inside of the Coroutine class was the only way I could figure out to get the specific `coroutine_handle<T>` type I needed in `await_suspend()`'s function signature.
It appears possible to infer the coroutine type by making `await_suspend()` a function template, which makes it possible to un-nest PromiseAwaiter (new name) from the Coroutine class. This allows us to implement Awaiter types for other awaitables without having to modify the Coroutine class.
> Decouple PromiseAwaiter from the Coroutine class

- c++/src/kj/async-inl.h
- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/test-helpers.c++
Currently, `newPromiseAndCrossThreadFulfiller()` can only create Promises associated with the calling thread's event loop. This is the overwhelmingly common use case for CrossThreadPromiseFulfillers.
Recently, while working on the ability to `co_await` Rust Futures across an FFI boundary, I encountered a case where it would be helpful to create Promises associated with a different thread's event loop.
To elaborate on the use case:
- Rust Futures have a `poll()` function which drives the Future to make some forward progress.
- The caller of `poll()` must pass a reference to a Waker object to `poll()`. Let's call this Waker the "initial Waker". It lives on the stack of the thread which calls `poll()`.
- Waker is an abstract interface, with any number of actual implementations.
- If the …
> Add Executor::newPromiseAndCrossThreadFulfiller()

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
Reverts capnproto/capnproto#2220
Broke the Workers Runtime build.
> Revert "Decouple PromiseAwaiter from the Coroutine class"

- c++/src/kj/refcount.h
- c++/src/kj/units.h
- doc/cxx.md
- kjdoc/tour.md
Using the KJ_IF_MAYBE macro and using `nullptr` to mean an empty Maybe are deprecated. This cleans up a few last places we have them.
> Cleanup KJ_IF_MAYBE / Maybe(nullptr) stragglers

- .github/workflows/quick-test.yml
- c++/src/kj/filesystem-disk-test.c++
- super-test.sh
This PR adds FreeBSD to the CI jobs, inspired by https://github.com/capnproto/capnproto/pull/1796#discussion_r1905782602.
Related comments from https://github.com/capnproto/capnproto/pull/1321:
- https://github.com/capnproto/capnproto/pull/1321#discussion_r698766582:
> Is there really no way to run FreeBSD on GitHub Actions? I was pretty happy that we managed to consolidate our CI a while back...
- https://github.com/capnproto/capnproto/pull/1321#discussion_r698872987:
> but we should have this use `super-test.sh` long-term.
Tested releases:
- Production Release 14.2
- Legacy Release 13.4
- [FreeBSD-CURRENT](https://docs.freebsd.org/en/books/handbook/cutting-edge/#current) snapshot (future 15.0)
Warnings such as the following:
```
clang++: warning: argument unused during compilation: …
```
> ci: Add FreeBSD job to Quick Tests

- c++/src/kj/common.h
GCC and clang do not use same calling convention for passing empty struct parameters. There is more information about this in https://itanium-cxx-abi.github.io/cxx-abi/cxx-abi-dev/archives/2015-December/002869.html
Unfortunately this can create an issue in capnproto if it is built without optimizations in GCC, and the resulting static libraries are used in a clang program, or vice versa.
Depending on what order libraries are specified on the linker command line, and whether code compiled with the other compiler is calling any header functions that cause weak a `operator new(unsigned int, kj::_::PlacementNew, void*)` symbol to be defined in its own objects, this can cause the linker to link a GCC-generated `kj::ctor` with a clang-generated `operator new`, and the resulting program to crash …
> Avoid gcc/clang ABI incompatibility caused by PlacementNew

- c++/src/kj/thread-test.c++
- c++/src/kj/thread.c++
- c++/src/kj/thread.h
(Blind-coded the Windows version, let's see if it works in CI...)
> Add Thread::getCpuTime() to read another thread's CPU usage.

- c++/src/capnp/message.h
- c++/src/capnp/rpc-prelude.h
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/test.capnp
This does not implement embargoes, so e-order may be violated.
As a reminder, none of this is enabled unless the VatNetwork implements new methods, so merging this won't impact existing users.
> 3PH part 3: Basic three-party handoff of capabilities

- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
Without the change in `async.c++`, the newly added test would throw when `TaskSet::trace()` gets called:
```
[ TEST ] async-test.c++:1227: TaskSet::trace() on forked promise                                                                                                                                                                                        
kj/_virtual_includes/kj/kj/memory.h:433: failed: expected ptr != nullptr; null Own<> dereference                                                                                                                                                        
stack: <redacted>
kj::_::inlineRequireFailure(char const*, int, char const*, char const*, char const*) …
```
> Fix crash scenario in TaskSet::trace

- c++/src/kj/async-queue.h
When a `WaiterQueue` is destroyed with unfulfilled promises, these promises become "dangling". I.e. waiting on them will hang indefinitely. This PR changes that by rejecting all unfulfilled promises remaining in the queue.
> Reject unfulfilled promises on WaiterQueue destruction.

- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.capnp
- c++/src/capnp/test-util.c++
- c++/src/capnp/test.capnp
This builds on #2121 by doing some refactoring and then implementing embargoes, so e-order is preserved through a handoff.
(This PR's merge target is set to #2121.)
> 3PH part4: Embargoes for capabilities

- c++/src/kj/async-io.h
This is part 1 of N of async input stream refactoring. Previously I tried to do everything at once but ultimately wasn't successful given the complexity of managing 2 downstreams.
This time I am picking a more gradual approach that will let me migrate clients first and then implementations.
> defining arrayptr-based AsyncInputStream methods

- c++/src/kj/refcount-test.c++
- c++/src/kj/refcount.h
`Arc<T>` should behaves like `Rc<const T>` and have its methods marked as thread-safe (const)
> clarify Arc<T> const-ness

- c++/src/capnp/compat/json.c++
- c++/src/kj/compat/brotli-test.c++
- c++/src/kj/compat/gzip-test.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/readiness-io-test.c++
- c++/src/kj/compat/url.c++
- c++/src/kj/encoding-test.c++
- c++/src/kj/encoding.c++
- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-test.c++
- c++/src/kj/main.c++
- c++/src/kj/string-test.c++
- c++/src/kj/string.c++
Automatic regexp-based translation. Helpful while updating async calls (char => byte) in tests
> nit: use _kj and _kjb where possible

- .github/workflows/quick-test.yml
I think it makes sense to run tests without KJ_DEBUG too. Added `opt` runs to bazel builds
> run CI in opt mode too

- c++/src/kj/common-test.c++
- c++/src/kj/common.c++
- c++/src/kj/common.h
I intend to use it from `refcount.h`. Let me know if `common.h` is not a best place for this. @kentonv
> kj::ThreadId

- .github/workflows/quick-test.yml
- c++/.bazelrc
- c++/src/kj/configure.bzl
- c++/src/kj/memory-test.c++
- c++/src/kj/memory.c++
- c++/src/kj/memory.h
Will enable additional checks in follow up prs too.
Redoes the way KJ_ASSERT_PTR_COUNTERS is defined, which adresses the comment in #2100.
> KJ_DEBUG_MEMORY flag

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
I found it useful when passing parameters requiring long conversion chains.
> kj::some() helper function

- CMakeLists.txt
- c++/CMakeLists.txt
- c++/samples/CMakeLists.txt
- c++/src/kj/CMakeLists.txt
Fixes build errors when using CMake 4.0. Technically, just 3.5 would be sufficient to avoid the errors, but targeting 3.10 avoids deprecation warnings as well.
> Update minimum CMake version to 3.10.

- c++/src/capnp/compiler/capnpc-c++.c++
Pretty much the title. In my case I want to change generic's parameter type, and reader is passed as const reference. Maybe this function should be also marked as `const` in Builders and Clients.  
```
struct Msg(T) {
val @0 :T;
metadata @1 :Text;
}
struct SimpleMessage {
val @1 :UInt32;
}
```
```c++
capnp::FlatArrayMessageReader reader{...};
processSimpleMessage(reader.getRoot<Msg<SimpleMessage>>());
void processSimpleMessage(const Msg<SimpleMessage>::Reader &message) {
debugDump(message.asGeneric<capnp::AnyStruct>()); // <-- now it fails because Reader::asGeneric is not const
// ...
}
void debugDump(const Msg<capnp::AnyStruct>::Reader &message) {
// dump message
}
```
> Allow calling Reader::asGeneric() on const readers

- doc/otherlang.md
This PR adds a link to the Cap'n Proto Language Server on [otherlang.md](https://github.com/capnproto/capnproto/blob/master/doc/otherlang.md), as suggested in https://github.com/capnproto/capnproto/discussions/2124#discussioncomment-12381176.
> Add link to Cap'n Proto Language Server

- c++/src/capnp/compiler/node-translator.c++
- c++/src/capnp/schema.capnp
- c++/src/capnp/schema.capnp.c++
- c++/src/capnp/schema.capnp.h
There was no discussion, sorry about that, but I figured the change is small enough that a PR could illustrate the change and host discussion if needed.
(And emit source information for `Annotation`s as per https://github.com/capnproto/capnproto/pull/2126#discussion_r2029886844).
This follows the work in #2126.
> Add member startByte and endByte

- c++/src/capnp/compiler/node-translator.c++
That is, set `startByte` / `endByte` in generated method params and result types, and in generated group structs.
Given `test.capnp`:
```capnp
@0xf46795117f51d8f6;
interface I {
method @0 (param :Text) -> (res :UInt32);
}
struct S {
group :group {
field @0 :Text;
}
}
```
Compiled and printed to stdout with (filtering out struct and interface definitions to keep the output simple):
```sh
capnp compile test.capnp -o- \
| capnp convert binary:text c++/src/capnp/schema.capnp CodeGeneratorRequest \
| perl -0pe 's/(struct|interface) = \((\n\s{8,}.+)*/$1 = (...),/g'
```
Before:
```capnp
( nodes = [
( id = 17611208770238666998,
displayName = "test.capnp",
displayNamePrefixLength = 5,
scopeId = 0,
nestedNodes = [
(name = "I", id = 9865039190638141284),
( name = "S",
id = 12715584206684640787 ) ], …
```
> add source information to generated structs

- c++/src/kj/one-of-test.c++
- c++/src/kj/one-of.h
- c++/src/kj/string.h
Made this with openai o4-mini-high. Tried claude code multiple times, which utterly failed each time, despite receiving a more detailed prompt than chatgpt.
Constraints are necessary to avoid compilation failures for types that try to instantiate this stringify implementation in debug code.
> implement stringification for kj::OneOf

- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.h
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/reconnect-test.c++
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc.c++
- c++/src/kj/array.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/memory.h
- c++/src/kj/units.h
This simplifies a bunch of code and reduces the debug binary size by 0.9% downstream if the sendIgnore() trick is used where applicable. Let's hope this optimization won't turn out to have pesky side effects 😅
> [nfc] if constexpr and send().ignoreResult() optimizations

- c++/src/kj/BUILD.bazel
I think this is the root cause of win32 linkage problems. kj-async also requires linkstatic
> [bazel] cidr.h uses inet_ntop from Ws2_32.lib

- c++/src/kj/test.c++
KJ currently prints the elapsed time for each test in microseconds. This PR changes this to instead use KJ's duration pretty-printing logic, which automatically selects a suitable unit.
Example:
```
[ TEST ] http-test.c++:6546: HttpServer.listenHttp() doesn't prematurely terminate if an accepted connection is broken
[ PASS ] http-test.c++:6546: HttpServer.listenHttp() doesn't prematurely terminate if an accepted connection is broken (19.842ms)
[ TEST ] http-test.c++:6567: HttpServer handles disconnected exception for clients disconnecting after headers
[ PASS ] http-test.c++:6567: HttpServer handles disconnected exception for clients disconnecting after headers (147μs)
```
cc: @anonrig
> kj/test.c++: Pretty-print test duration

- c++/src/kj/timer.c++
The check was disabled on Mac, but in #2261 it was reported also on Linux. At this point, it makes more sense to remove the KJ_REQUIRE for monotonicity alltogether.
> Remove check for monotonic time

- c++/src/kj/filesystem-disk-unix.c++
At least Linux (including Android) and FreeBSD provide an extension for `open`, [O_PATH](https://man7.org/linux/man-pages/man2/open.2.html#:~:text=O_PATH%20(since%20Linux%202.6.39)), that is essentially an inode-only reference; it avoids potential permission issues. When available, replacing O_RDONLY with it in DiskFilesystem's openDir appears to be compatible with capnproto's use case.
When compiling for Android API >= 30 (for memfd_create), testing on an Android device passes all tests except the DiskDirectory hard linking test (https://github.com/capnproto/capnproto/blob/20af9fe2de10a2e7f621a212351d20860cc32a0d/c%2B%2B/src/kj/filesystem-disk-test.c%2B%2B#L605) , which is not allowed on Android. (Could only test on Android without fibers, as some parts of libucontext will fail.)
Fixes …
> Platform-dependent fix for root permissions error

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
currently canMemcpy<char> is false (because of the second branch)
> fix canMemcpy

- c++/src/kj/array.h
- c++/src/kj/common.h
Depends on #2323 
Downstreams do not have any problem with this.
> restrict asBytes and asChars to canMemcpy types

- c++/src/kj/async-inl.h
Disable `clang-analyzer-core.UndefinedBinaryOperatorResult` error in `PtmfHelper` using a NOLINT comment to appease clang-tidy.
A complete description of the error and rationale for the change is in the commit message.
> PtmfHelper: Use NOLINT to disable UndefinedBinaryOperatorResult error

- c++/src/capnp/rpc.c++
If this happens when we're inside taskFailed(), it's Bad.
> Wrap shutdown() call in disconnect() to catch synchronously thrown exceptions

- c++/src/kj/exception-test.c++
- c++/src/kj/exception.c++
The problem happens because file can point not to the beginning of ownFile.
> fix kj::Exception copy constructor use-after-free

- c++/src/capnp/rust_capnp_library.bzl
The Rust compiler flags `pub use module::*` as unused when the wildcard only brings in a single module (vs multiple items), even though the import is actually used for re-export.
> [rust] fix unused import warnings on re-export

- c++/src/capnp/BUILD.bazel
- c++/src/capnp/cc_capnp_library.bzl
- c++/src/capnp/compat/BUILD.bazel
- c++/src/kj/BUILD.bazel
- c++/src/kj/compat/BUILD.bazel
- c++/src/kj/configure.bzl
- Apply buildifier
- Drop obsolete http-over-capnp-test-as-header target
- Export c++.capnp (the change that will actually be useful downstream)
> [build] 08-08-25 Bazel cleanup

- c++/src/kj/compat/http.c++
the extra whitespace edits here are clang-format bits... can remove them if necessary
> Include header name in invalid value error messages

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/common.h
- c++/src/kj/hash.h
These utilities originally landed in https://github.com/capnproto/capnproto/pull/1762. Unfortunately, they landed at the same time as a [subtle bug in our fiber implementation](https://github.com/capnproto/capnproto/pull/1842) began causing production crashes in the Workers runtime, and we reverted this `SmallArray` feature out of an abundance of caution.
I've been meaning to re-submit `SmallArray`. It is a more ergonomic interface than KJ_STACK_ARRAY, and the primary compiler we target nowadays (clang) does not support VLAs, which is KJ_STACK_ARRAY's competitive advantage.
In the intervening years, some HeapArrayDisposer was refactored to use `if constexpr` instead of a dispatch struct template in: https://github.com/capnproto/capnproto/pull/2288/files#diff-a50b82e04212952a2c02eee72504e7c …
> Implement SmallArray

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/string-test.c++
- c++/src/kj/string.h
Current design converts `as<T>()`` calls into static members of T, which doesn't make it extensible: T needs to know about every type that can be converted.
Updating the design to convert as<T>() in `into(T{}, this)`, which makes T a simple marker object and you can have as many conversion targets as you like.
This is a very breaking change (for implementation, but not for interface) and will require carefull landing across worker-cxx, workerd and workers repository.
See https://github.com/cloudflare/workerd-cxx/pull/67 for similar improvement for the other direction.
See https://github.com/cloudflare/workerd-cxx/pull/69 for downstream changes.
> more powerful as<T>() implementation

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
We really need to transfer the original headers object, not clone it. Usually the headers all point into the original header buffer, but not necessarily always. The headers could have one or more headers backed by its `ownedStrings`.
Luckily as we are dismantling the connection anyway, we're free to take the headers with us.
> Fix transfer of headers when suspending a request.

- c++/src/kj/common.h
- c++/src/kj/string-test.c++
This is similar to https://github.com/capnproto/capnproto/pull/2396 and creates uniform way to define conversion functions like `kj::from<Rust>(rustString)`.
> kj::from<Domain>(t) helper function

- c++/src/kj/cidr.h
it can't include common.h as is because it is part of a different library.
> cidr.h include fix
