- CONTRIBUTORS
- highlighting/emacs/README.md
- highlighting/emacs/capnp-mode.el
Created an emacs major mode to support capnproto syntax highlighting.
> added syntax highlighting for emacs

- doc/install.md
Makes life easier for OS X users using Homebrew
> add installation doc from brew for Mac OS X

- c++/src/capnp/any-test.c++
- c++/src/capnp/any.h
- c++/src/capnp/dynamic-test.c++
- c++/src/capnp/dynamic.h
Also fix AnyStruct::Reader/Builder as methods
> Allow DynamicStruct::Reader/Builder.as<AnyStruct>

- c++/CMakeLists.txt
- release.sh
Otherwise the installed pkgconfig files are broken. The release script
has also been changed to update the version for CMakeLists.txt.
Fixes issue #162
> Also set the version for the CMake build

- c++/src/kj/test.c++
> Cast mmap to char *.

- c++/src/kj/async-io.c++
Short-term fix for #220.
This just ifdefs on `__OpenBSD__`. Suggestions welcome for better ways of switching behaviour.
I opted to just stick this in the existing wildcard section rather than rearrange things and use the following af-conditioned block because this seemed a bit clearer.
> Use ip4 sockets for wildcard on OpenBSD

- c++/src/kj/units.h
Mentioned three days ago, didn't want it to get forgotten
> Typo found by @mquandalle

- c++/src/capnp/capability.h
- c++/src/capnp/rpc-twoparty.h
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.capnp
Also remove an unnecessary refcount increment.
> Fix some outdated comments and error messages.

- c++/src/capnp/compat/json.c++
This encapsulates the input array, hiding it from the parser's methods.
Access is forced to go through `advance` and `consume*` methods on the
new `Input` object. The aim is to make it harder to have errors like
https://github.com/sandstorm-io/capnproto/pull/270
> json: Hide the input array from parser methods

- c++/src/kj/async.c++
Added missing definition for EventLoop::isRunnable().
> Add missing isRunnable implementation

- doc/cxxrpc.md
Server::Context does not have method getRequest
> doc/cxxrpc: use getParams() in server

- c++/src/capnp/compat/json.c++
- c++/src/capnp/dynamic.c++
- doc/language.md
> Bka cleanups

- c++/src/capnp/capability-test.c++
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/encoding-test.c++
- c++/src/capnp/persistent.capnp.h
https://github.com/sandstorm-io/capnproto/issues/334
> capnp-c++: implement asGeneric method for outer template contexts

- c++/setup-autotools.sh
> update setup-autotools.sh to fetch gtest from github

- c++/src/kj/array.h
- c++/src/kj/async-io.c++
> Fix MSVC build errors

- CONTRIBUTORS
> add David Renshaw to CONTRIBUTORS

- c++/src/kj/CMakeLists.txt
- c++/src/kj/compat/http.c++
- c++/src/kj/parse/char.h
- c++/src/kj/parse/common.h
@harrishancock does this look right?
(Yay, AppVeyor will test it!)
> Add kj-http to cmake build.

- appveyor.yml
- c++/CMakeLists.txt
- c++/samples/CMakeLists.txt
- c++/src/capnp/CMakeLists.txt
- c++/src/kj/CMakeLists.txt
- c++/src/kj/common.h
- c++/src/kj/parse/common.h
Fixes #466.
I wanted to have AppVeyor test VS2017 for this PR, too, so I went ahead and added a build matrix. I'm curious to see what this is going to look like...
> Fix VS2017 ICE and add build matrix to appveyor.yml

- doc/_posts/2017-05-01-capnproto-0.6-msvc-json-http-more.md
- doc/install.md
- doc/push-site.sh
- doc/roadmap.md
- doc/stylesheets/stylesheet.css
Preview here: https://capnproto.org/next/news/2017-05-01-capnproto-0.6-msvc-json-http-more.html
> Announce 0.6 release on blog, and update site

- c++/src/kj/compat/http.h
or, the world's least significant pull request.
> Misspelt macro name in undef

- c++/src/kj/compat/make-test-certs.sh
- c++/src/kj/compat/readiness-io-test.c++
- c++/src/kj/compat/readiness-io.c++
- c++/src/kj/compat/readiness-io.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
- c++/src/kj/compat/tls.h
My memorial day weekend project... >_>
> WIP OpenSSL TLS bindings

- c++/Makefile.am
- c++/src/kj/CMakeLists.txt
- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
- c++/src/kj/compat/url.h
Forgot to do this is #490, hence it trivially passed CI. :(
Also add some comments.
> Actually add URL library to makefiles

- c++/src/kj/array-test.c++
- c++/src/kj/array.h
- c++/src/kj/async-io.h
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/url.c++
- c++/src/kj/compat/url.h
- c++/src/kj/vector.h
> Tweaks and bugfixes

- c++/configure.ac
- c++/src/kj/exception.c++
> Do not use execinfo.h with uclibc

- c++/src/capnp/rpc.capnp
https://groups.google.com/d/topic/capnproto/_1kBtRSC51s/discussion
> Clarify RPC spec documentation based on mail thread

- c++/src/capnp/compiler/node-translator.c++
Detected by Debian package linting tools.
> Fix minor typo: varibale -> variable

- c++/src/capnp/rpc.capnp
Based on discussions in the Google group:
https://groups.google.com/forum/#!topic/capnproto/_1kBtRSC51s
> Clarify the RPC spec in some places

- c++/src/kj/async-io-win32.c++
Make win32Socketpair more secure.
In theory if someone guessed the port and connected at just the right time they could break the socket pair. Check peer address to verify this hasn't happened.
(Note that we don't use win32Socketpair() anywhere important today -- mostly just in tests. This is just something that occurred to me white touching related code.)
> Make win32Socketpair() more secure

- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
There are actually two new client types:
- One which always connects to a given NetworkAddress, but will automatically manage a pool of reusable connections.
- One which looks up the remote address based on the URL it is given, and manages a pool of connections for each host.
The latter of these two is a "true HTTP client library".
> Implement HttpClient that automatically manages connections. 

- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
Fixes #286.
Also: Refactor TaskSet to use a list rather than a map (separate commit).
> Add TaskSet.onEmpty() to wait until all tasks have completed

- c++/src/kj/compat/http.c++
Previously we only closed immediately after a response finished.
> Close idle HTTP connections on server drain.

- c++/src/kj/exception-test.c++
- c++/src/kj/exception.c++
This should prevent stack traces from spurriously pointing at the line after the one where the call actually happened.
> Improve stack trace accuracy by subtracting 1 from each return address.

- c++/src/kj/async-io-unix.c++
1. Correctly set nonblocking flag *before* calling connect(). (On glibc-Linux, we create the socket already in nonblocking mode, so this was never an issue.)
2. FDs could be leaked if connect fails. (This applies to glibc-Linux too, although connect() would have to fail immediately without blocking, which is unusual.)
> Fix multiple problems with connect() on non-glibc-Linux:

- c++/src/capnp/membrane.c++
- c++/src/capnp/membrane.h
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.h
- c++/src/kj/async.c++
- c++/src/kj/compat/readiness-io.c++
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
- c++/src/kj/compat/tls.h
These are three tweaks I made that are needed by: https://github.com/sandstorm-io/sandstorm/pull/3007
> Various tweaks needed by Sandstorm HTTP changes

- c++/src/kj/async-unix-test.c++
- c++/src/kj/async-unix.c++
> Fix wrong poll/epoll timeout after EINTR.

- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
Unfortunately we don't have unit tests for DNS lookup since it's not hermetic. :(
Don't forget you can add `&w=1` to the github review URL to get a whitespace-ignoring diff.
> Fix bug where DNS lookup would fail for very long hostnames.

- CMakeLists.txt
- c++/CMakeLists.txt
> Add project() call to root CMakeLists.txt

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Previously HttpService had two virtual methods: request() and openWebSocket(). Since it's legitimate to respond to a WebSocket request with a normal HTTP response, openWebSocket() actually had a default implementation that fell back to request().
In the new design, there is only request(). The HttpService detects a WebSocket request by checking the headers. A convenience method, HttpHeaders::isWebSocket(), is provided for this purpose.
The new approach makes life much easier for services composed of many layers. For example, you might write an HttpService implementation which performs some URL or header rewrite and then calls on to another HttpService. Previously, every such wrapper would have to separately handle regular requests and WebSockets, usually with near-identical code. Of …
> Redesign server-side WebSocket handling.

- c++/src/kj/compat/http.c++
In theory KJ style should allow this to be caught (it doesn't throw if another exception was already thrown), but I've observed this producing an std::terminate() for some reason.
> Don't throw from ~HttpChunkedEntityWriter after write cancellation.

- c++/src/kj/compat/http.c++
It turns out I was testing it wrong, and it still doesn't work. :(
> Really actually fix HttpServer::drain().

- c++/src/kj/compat/url-test.c++
- c++/src/kj/compat/url.c++
I'm not super thrilled about this PR, and wish there were a cleaner solution. My main concern is what happens when a URL is parsed in a request context, then serialized out as a REMOTE_HREF. Since we typically don't percent-decode on URL parsing now in servers, we also don't percent-encode on serialization. Thus, part of the path/query would be lost, instead interpreted as the fragment, unless the calling code anticipated the problem at manually escaped the '#'.
One solution might be to percent-encode such problematic characters during the parsing stage, right before we optionally-percent-decode. This would be similar to what the URL spec does, so we might consider just implementing its behavior.
> Allow hash signs in path and query components in kj::Url request contexts

- c++/src/capnp/rpc.capnp
> Fix a typo

- c++/src/kj/compat/http.c++
Printf debugging at its finest.
> Log unknown Transfer-Encoding values in kj-http

- c++/src/capnp/any.h
- c++/src/capnp/c++.capnp.h
- c++/src/capnp/common.h
- c++/src/capnp/compat/json.capnp.h
- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/compiler/grammar.capnp.h
- c++/src/capnp/compiler/lexer.capnp.h
- c++/src/capnp/dynamic.h
- c++/src/capnp/layout.c++
- c++/src/capnp/layout.h
- c++/src/capnp/message.h
- c++/src/capnp/persistent.capnp.h
- c++/src/capnp/rpc-twoparty.capnp.h
- c++/src/capnp/rpc.capnp.h
- c++/src/capnp/schema.capnp.h
- c++/src/capnp/schema.h
- c++/src/capnp/serialize-test.c++
- c++/src/capnp/serialize.c++
- c++/src/capnp/serialize.h
- c++/src/kj/async.h
- c++/src/kj/compat/gtest.h
- c++/src/kj/debug.h
- c++/src/kj/exception.h
- c++/src/kj/miniposix.h
- c++/src/kj/test.h
- c++/src/kj/windows-sanity.h
- doc/encoding.md
> A bunch of issue fixes for 0.7

- c++/src/capnp/compat/json-test.c++
This is what I get for merging #732 before tests completed.
> Fix json-test on MSVC.

- c++/src/kj/compat/http.c++
In Cloudflare Workers, we've observed applications in the wild that continue to send messages after a Close message. This is incorrect, but it happens, and we end up logging a spurious error as we attempt to proxy the message through.
By removing this restriction, we can now proxy these WebSockets despite the incorrect usage.
> Allow WebSocket to keep sending after close().

- c++/src/kj/array.h
Just a small typo in a comment.
> Typo in c++/src/kj/array.h

- c++/src/kj/compat/http.c++
In setPromise() we chain `task` with an error handler that accesses ResponseImpl, so that means `task` needs to attach a reference to RespnoseImpl... ugh.
> Fix obscure use-after-free in HttpClientAdapter.

- c++/src/kj/compat/http.c++
I don't have a use case, I was just reading the code and noticed it was wrong.
> Fix obscure optimization-blocking bug in PromiseIoStream::tryPumpFrom().

- c++/src/kj/filesystem-disk-win32.c++
Fixes some compilers - pretty self explanatory I think!
> Fix narrowing conversion

- c++/src/kj/compat/http-test.c++
Seems to work reliably under Windows, hopefully also Mac.  I'm not
totally sure why the extra polling is necessary, though.
> http-test: Replace windows-conditional block with extra poll

- c++/src/kj/array.h
- c++/src/kj/map.h
- c++/src/kj/mutex-test.c++
- c++/src/kj/mutex.h
- c++/src/kj/one-of.h
- c++/src/kj/vector.h
This is a collection of unrelated features that I needed in the course of a CF Workers refactoring.
> Feature grab bag

- doc/otherlang.md
Update JavaScript plugin to generate Flow-annotated, ES6 code.
> Update link to @popham plugin

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
Previously if the input stream being pumped from encountered an EOF while the other side of the pipe was being pumped elsewhere, we did not fulfill the tryPumpFrom() promise, leaving it hanging.
> Fulfill AsyncPipe::tryPumpFrom() on EOF

- c++/src/kj/table.c++
> Add OpenBSD to posix_memalign ifdef

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
This information is typically necessary to debug such protocol errors. However, it requires special handling, since it could contain sensitive information.
The code which has the best view on protocol errors is HttpHeaders::tryParseRequest(), which previously returned an empty Maybe<Request> on failure. This commit changes that function to return a OneOf<Request, ProtocolError>. This required some surgery in various other parts of the code to deal with the OneOf.
> Report raw HTTP content when handling client protocol errors in kj-http

- c++/src/kj/compat/http-test.c++
Most (all?) implementations of `write(ArrayPtr<const ArrayPtr<const byte>>)`, if the outer array contains only one inner array, do not use the outer array again after the initial call returns (as opposed to the promise resolving). But, this is not a safe assumption and http-test.c++ should not be relying on it.
(I found this when I tried forcing all writes to complete asynchronously to check if it resulted in any bugs. This is all I found.)
> Fix http-test.c++ to avoid dubious assumptions about gather-writes.

- c++/src/capnp/schema.c++
- c++/src/kj/map.h
- c++/src/kj/table.c++
And fix a bug detected by this.
> Detect and report when a HashMap suffers from excessive collisions.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Ideally, the HttpClient/HttpServer adapters should maintain the invariant that
the behavior of a given client is the same as the behavior of
newHttpClient(newHttpService(client)).  Prior to this change, the HttpClient
wrapper lazily called request(), so a client whose request() eagerly threw an
exception could produce a different exception when called directly versus when
wrapped -- the laziness allowed additional code to run.  This was particularly
evident when making a request with a body, since code using a wrapped client
would be able to set up a subsequent BlockedWrite, eventually resulting in a
"read end of pipe was aborted" exception instead of the actual exception.
This change makes HttpClientAdapter::request() execute the wrapped request()
eagerly.
(Note that it partially undoes …
> Make HttpClient adapter preserve exception behavior

- c++/src/capnp/compat/http-over-capnp.c++
This reverts commit 0123e17116e1a3f0520300cb3670b01a2cd2a1e5.
This wasn't the right place to solve this problem. The same problem applies when calling an HttpService directly, or using an HttpClient that wraps an in-process HttpService. Applications that struggle with this need to find a better solution.
> Revert "Override Content-Length and Transfer-Encoding in http-over-capnp."

- c++/src/kj/async-unix-test.c++
> Add test for FdObserver(..., flags=0)::whenWriteDisconnected() support

- c++/src/kj/one-of.h
I needed a 9 way switch... :blush:
---
Should I be doing something else at this point? Should we go ahead and add even more variants?
> Add a 9-way variant for OneOf matching

- c++/src/kj/map-test.c++
- c++/src/kj/map.h
> Fix HashMap::eraseAll() to match documentation.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
A while ago, I adjusted the HttpClient adapter implemnetation so that the response stream on the client side would delay reading EOF until the HttpService's request() promise had completed. This ensured that the promise didn't get prematurely canceled.
But, originally I only had it delay completion, without propagating any exceptions. It turns out to be useful to propagate exceptions here. Although exceptions would not be propagated over a true network connection, propagating them over in-process adapters seems to make errors easier to debug in practice. This also means they will propagate over http-over-capnp.
I also added tests for this functionality, which were previously missing.
> HttpClient adapter (around HttpService) should propagate exceptions.

- c++/Makefile.am
- c++/configure.ac
- c++/pkgconfig/kj-gzip.pc.in
- c++/pkgconfig/kj-tls.pc.in
Fixes half of #973.
I didn't do cmake because I dunno how.
> Fully support kj-gzip and kj-tls in autotools/pkgconfig

- c++/src/kj/compat/gzip.c++
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
Fixes #988
Also, throw in a change to make gzip streams not generate zero-length writes in the first place, but that's just an optimization, not a bug fix.
> Fix zero-length write to TlsConnection.

- c++/src/kj/async.c++
> Add ifdef to remove fiberCanceledException if exceptions are disabled

- c++/src/capnp/compat/json-test.c++
- c++/src/capnp/compat/json.c++
> Fix JsonCodec::setRejectUnknownFields() to work with annotated types.

- c++/src/capnp/message.h
> Use 8-bit alignment for arenaSpace

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/membrane.c++
- c++/src/capnp/membrane.h
See individual commit descriptions...
> Fix a couple problems causing unnecessary network round trips

- c++/src/capnp/layout.c++
- c++/src/kj/array.h
Address TSAN discussion from https://groups.google.com/g/capnproto/c/634juhn5ap0/m/pyRiwWl1AAAJ
Address UBSAN discussion in #1079 per (at least as I understood) @kentonv's suggestion.
> Fixes to make sanitizers happy

- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/thread.c++
> Fix some random things

- c++/src/kj/debug.c++
- c++/src/kj/exception-test.c++
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
> Add some utilities for debugging exceptions

- c++/src/kj/async-xthread-test.c++
- c++/src/kj/async.c++
> Fix a cross-thread event bug and add some asserts

- .github/workflows/quick-test.yml
- c++/src/kj/exception.c++
I guess we depended on a vulnerability, lol.
> Fix MSVC CI build.

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
> Improve exceptions when dropping the fulfiller of a PromiseFulfillerPair

- c++/src/capnp/rpc.c++
`message->send()` could throw for all sorts of reasons. Previously, in this case, we failed to null out `question.selfRef`, leaving it dangling.
In fact, we probably don't want to propagate these exceptions out of `~QuestionRef()` -- it is refcounted, so this could throw at a weird spot. Instead, we should proabbly kill the connection, by catching and calling `disconnect()`.
> Re-arrange QuestionRef destructor to handle exceptions better.

- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/kj/async-test.c++
- c++/src/kj/exception-test.c++
I broke the no-exceptions build with some recent changes, oops.
> Fix release tests.

- doc/cxxrpc.md
> Use archive of "All Concurrency Models Suck"

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
(@harrishancock, you already reviewed this, and it's already deployed.)
> Allow limiting WebSocket message size.

- c++/src/kj/async.c++
I've been trying to debug a problem where the EventLoop is non-empty at shutdown that seems impossible. I'm hoping this change helps somehow.
> In EventLoop destructor, destroy daemons in a loop.

- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
In particular this can be used to get the raw header data that failed to parse, for diagnostic purposes.
> Add HttpClientErrorHandler, similar to HttpServerErrorHandler.

- c++/src/kj/compat/tls.c++
Before this change a TLS wrapped network used in an accept loop would
have to handle errors that leaked during TLS handshake. This change brings
TLS wrapped networks in line with raw networks, in that only errors
during the underlying raw network accept() call will be thrown since
that indicates an issue with the underlying socket.
---
I guess the log could be more descriptive. I'm open to ideas. The actual function being called is `SSL_accept`.
> Fix TLS handshake errors being leaked from accept

- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
If the client initiates a call and then drops the service capability before the call completes, the server-side service object might be destroyed while the call is still executing.
> Fix HttpService lifetime issue in http-over-rpc.

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc-twoparty.c++
- c++/src/capnp/rpc-twoparty.h
Minor addition to 2330d3dedd76b964b5509e804aed1f2ff871094f (#1169).
> Add ability to query RPC queued message count for TwoPartyVatNetwork

- c++/Makefile.am
- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
- c++/src/kj/list-test.c++
- c++/src/kj/list.c++
- c++/src/kj/list.h
This is a pattern I've repeated a million times in KJ and beyond, it's time to formalize it.
> Introduce kj::List.

- doc/go/capnp.html
Per https://github.com/capnproto/go-capnproto2/issues/166
> Add page to support using capnproto.org for the Go implementation

- c++/src/capnp/rpc.c++
In practice, this leads to duplicate logging from the taskFailed handler
if the higher-level implementation that's calling disconnect() also logs
the reason for disconnecting. We still want to log actual problems
shutting down connections, but if the error is just what's passed in
then there's little value to logging it.
This will still log if the `shutdown()` implementation returns its own new exception, but that kind of seems like the point. Should we add some sort of helpful prefix to the KJ_LOG call in `RpcSystemBase::Impl::taskFailed`? We can't just assume that any failed task within the class is a shutdown task, so I think we'd either have to use a generic statement that doesn't mean much about some task failing in `RpcSystemBase::Impl` or we'd have to create a new wrapper exception …
> Don't log unchanged disconnect() errors in RPC shutdownPromise

- c++/src/capnp/capability.h
- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/list-test.c++
- c++/src/kj/list.h
- c++/src/kj/mutex.h
- c++/src/kj/one-of-test.c++
- c++/src/kj/one-of.h
- c++/src/kj/table-test.c++
- c++/src/kj/table.h
Random grab bag of stuff I added while working on project.
> Add kj::Table::seek() and several other little things

- c++/src/kj/exception.c++
> Fix release build for GCC 11

- c++/src/capnp/compat/byte-stream-test.c++
Not sure why I didn't see this when running ASAN before. My only guess
is that there was a toolchain update that catches this new failure.
> ASAN fix for byte-stream-test

- highlighting/emacs/README.md
- highlighting/emacs/capnp-mode.el
Required fixes to allow upload to melpa https://github.com/melpa/melpa/pull/7613
> Minor package-lint fixes to elisp

- c++/src/kj/mutex.h
Accidentally missed a few spots for making sure the location is
tracking.
> Fix ExternalMutexGuarded location tracking

- c++/src/kj/mutex.c++
Maybe we should also include the time spent holding the exclusive lock
(or at least in KJ_DEBUG?), but I suspect this is sufficient.
> Log the time spent contending the lock

- c++/src/capnp/test.capnp
- c++/src/kj/async-io-test.c++
- c++/src/kj/async.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/tls.c++
- c++/src/kj/exception.c++
(The release script refuses to allow a release with TODO(soon)s present.)
> Defer all TODO(soon)s.

- doc/_posts/2021-08-14-capnproto-0.9.md
> Blog post for release 0.9.

- doc/roadmap.md
- kjdoc/tour.md
- style-guide.md
See each commit for explanation.
> Minor doc improvements

- c++/src/kj/table-test.c++
- c++/src/kj/table.c++
- c++/src/kj/table.h
There's one bug fix, but I don't think it is possible to trigger in practice.
> Various TreeIndex debugging improvements

- c++/src/kj/mutex-test.c++
Finally figured out the LSAN report.
> Add missing timer_delete calls

- c++/src/kj/async-coroutine-test.c++
Fixed port numbers flake in CI.
> Use ephemeral port number instead of a fixed one

- c++/src/kj/compat/http.c++
...when many pending connections are canceled at once
> HTTP concurrency limiter: Avoid unnecessary recursion

- c++/src/kj/compat/http.c++
The first commit is definitely needed to fix a known problem.
The second one (A) might not be needed, and (B) might go too far. All tests pass with it, including internally, but that's far from a sure sign it's ok. So I'm happy to discard it if you aren't sure either.
> Make sure to clean up properly with a pipe hits an exception to avoid inadvertently hanging

- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-disk-unix.c++
> Check ERANGE error from getcwd

- c++/src/kj/table-test.c++
- c++/src/kj/table.h
erase() is supposed to avoid accessing the row that is being erased. This is important in particular when rolling back an insertion due to a later index reporting an insertion failure.
Thanks @tniessen for providing a repro.
Fixes #1436
> Fix bug in TreeIndex erase().

- kjdoc/tour.md
These functions have been super useful for me.
Please feel free to suggest different phrasing.
> Mention map() and orDefault() in KJ tour

- c++/.bazelrc
- c++/src/capnp/BUILD.bazel
- c++/src/capnp/cc_capnp_library.bzl
- c++/src/capnp/compat/BUILD.bazel
Provides cc_capnp_library for capnp compilation.
> [bazel] compile capnp

- c++/src/kj/common.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/string-test.c++
- c++/src/kj/string.c++
- c++/src/kj/string.h
Closed the old PR because I messed up the git history and didn't want to make review unnecessarily challenging.
This is going to be fairly dense, so I think it's better to break it into parts.
This is all that's been done so far. Commits 1-3 represent a stage in extension negotiation, that is:
1. build the extension header for the request
2. parse the offers as the server + build a response
3. parse the servers response as the client
I added a test in commit 4, but since we're doing a lot of string parsing I think more tests are needed.
As of now, we:
- Drop all `Sec-WebSocket-Extensions` aside from `permessage-deflate` before sending the request to the server. The client retains information from its highest preference offer (ex. # bits to use for `client_max_window_bits`) so it can …
> Support `permessage-deflate` WebSocket Extension

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
This is the start of an implementation of CONNECT support for kj http. ~~It's incomplete and fairly rough still. Opening now to start collecting early feedback on the approach here before spending a ton more time on it.~~
> Implement http CONNECT

- c++/src/capnp/compiler/lexer.c++
- c++/src/capnp/compiler/node-translator.c++
- c++/src/capnp/compiler/node-translator.h
- c++/src/capnp/encoding-test.c++
- c++/src/capnp/serialize-text-test.c++
- c++/src/capnp/test.capnp
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/common-test.c++
- c++/src/kj/common.h
- c++/src/kj/compat/tls.c++
- c++/src/kj/compat/tls.h
- c++/src/kj/filesystem-disk-unix.c++
- c++/src/kj/map-test.c++
- c++/src/kj/map.h
- c++/src/kj/string.h
These were things I needed while working on a project.
> Several small random changes

- c++/src/kj/async-unix.c++
We've seen this causes some contention on the signal handler table mutex when lots of threads start simultaneously. Only one thread actually needs to execute this since signal handlers are registered process-wide.
> Only ignore SIGPIPE once per process.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Fixes a race condition where a client disconnection could cause a "failed" exception to be thrown after its "disconnected" exception had already been handled.
> HttpServer: Avoid flushing broken streams when handling errors

- c++/src/capnp/layout.c++
* "Message contained out-of-bounds struct pointer." indicates corruption
* "Message contains non-struct pointer where struct pointer was expected." indicates a schema mismatch
So we might as well include those in the error message to improve clarity.
> Improve description of schema mismatch/corruption errors.

- c++/src/kj/BUILD.bazel
- c++/src/kj/CMakeLists.txt
- c++/src/kj/exception-override-symbolizer-test.c++
- c++/src/kj/exception.c++
Rather then implementing all possible solutions, make it overridable.
> mark stringifyStackTrace() as weak

- .gitignore
- c++/WORKSPACE
- c++/compile_flags.txt
- c++/ekam-build.sh
- c++/src/benchmark/protobuf-carsales.c++
- c++/src/benchmark/protobuf-catrank.c++
- c++/src/benchmark/protobuf-eval.c++
- c++/src/capnp/compat/http-over-capnp-perf-test.c++
- c++/src/ekam-rules
- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/exception.c++
- c++/src/kj/exception.h
- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
- c++/src/kj/test.c++
- c++/src/kj/test.h
In this PR:
* Set up slightly better tooling for working on Cap'n Proto with Ekam independently of any dependent project.
* Create a benchmark covering KJ HTTP and http-over-capnp.
* Improve performance by like 15% with a couple tweaks.
> Tinker with performance

- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/rpc.c++
At present, if you make a streaming call on an RPC capability, then drop the capability, the streaming call could be canceled (`Finish` message sent to the server) before it has returned. This is NOT true of regular calls -- keeping the Promise returned by the call alive prevents it from being canceled. The problem happens with streaming calls because the RpcFlowController is dropped when the capability is dropped, and the flow controller is responsible for waiting for streaming calls to complete.
In the case of byte-stream.capnp, it quite normal for the capability to be dropped before streaming is done, due to the fact that KJ streams currently lack an `end()` call, so instead we invoke it in the destructor and then detach the promise. No one was holding on to the capability in this …
> Fix premature cancellation of streaming calls when capability dropped.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Implements a variation on connect() that allows for optimistic piplining of outbound writes while the CONNECT tunnel is still being established. Useful for reducing latency. Best implemented as a separate method since not all uses will want to, or be capable of, making use of pipelining.
Work in progress: Needs tests
> Implement pipelined connect() on HttpClient

- c++/src/kj/compat/http.c++
Refs https://github.com/capnproto/capnproto/pull/1579/commits/7105b4b893ab2ae9b6d53786fd074017f0163913#r1043683713 and https://github.com/cloudflare/workerd/pull/214#discussion_r1043679895
> Remove fulfiller check in http.c++

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
When sending an empty message, we would fail an assert that checked if the message tail included `0x00 0x00 0xFF 0xFF`.
> Fix WebSocket compression empty message bug

- c++/src/kj/compat/http.c++
The HttpChunkedEntityWriter and HttpFixedLengthEntityWriter both previously held a bare reference to the HttpOutputStream, and both perform additional cleanup in their destructors. If, for whatever reason, the Own<HttpChunkedEntityWriter> or Own<HttpFixedLengthEntityWriter> happened to outlive whatever thing happened to own the HttpOutputStream, a UAF crash can happen. This commit adds some safety rails around it by introducing a ResetableRef utility that will clear the ref when the owning object is destroyed. A once-per-process log entry is emitted to detect problematic usage of both HttpChunkedEntityWriter and HttpFixedLengthEntityWriter.
Eventually, we need to remove the cleanup logic from these types and implement a proper end() function for AsyncOutputStream.
> Add a ResetableRef utility to protect against UAF

- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/byte-stream.h
- c++/src/capnp/compat/http-over-capnp.c++
This fixes an issue in Cloudflare Workers where, when using the new "level 2 optimization" for http-over-capnp, cancellation of HTTP requests would not always propagate correctly. The problem is, despite being canceled, the ByteStream representing the request body would still receive an explicit end() due to the destructor, and the capability would be held open until that end() completed. Holding open the capability prevented cancellation of the `request()` call since the capability was a pipelined capability to be returned by `request()`.
If I were a better person I'd write a test for this, but the conditions to cause the problem are obscure. They are covered by the Workers test suite, though.
> Augment http-over-capnp to explicitly end ByteStreams where practical.

- c++/src/kj/common-test.c++
- c++/src/kj/common.h
This commit adds three new functions to `kj::_:Deferred`:
- A move-assignment operator to allow reuse of the same variable for deferred functors of the same type.
- A `run()` function to immediately run the guard before destruction.
- A `nullptr` assignment operator (nullification) as syntactic sugar for `run()`.
It's worth mentioning that via the magic of kj::Maybe and universal references, `Deferred` maintains the ability to hold lvalue reference to functors instead of functor instances.
> Give deferred function guards the ability to run before destruction

- c++/src/kj/filesystem.c++
I randomly noticed these weren't consistent.
> Fix some error messages in in-memory filesystem implementation.

- .github/workflows/quick-test.yml
We're having upstream compilation problems with clang-16, adding it here so that I can write unit-tests/add fixes.
> add clang-16 build

- c++/src/capnp/compat/http-over-capnp.c++
These errors only arise when an existing client is no longer able to receive a response. In practice, that sort of error is always uninteresting.
> Cleanup: Only log HTTP-over-RPC errors at INFO level

- c++/src/kj/compat/tls-test.c++
```bash
$ cmake -Bbuild-output -DCMAKE_BUILD_TYPE=debug -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%" -DCMAKE_INSTALL_PREFIX=%CD%\capnproto-c++-install
$ cmake --build build-output --config debug --target install
$ cd build-output\src
$ ctest -V -C debug
```
> Fixes NetworkHttpClient with tlsStarter test on Windows.

- c++/src/capnp/compat/http-over-capnp.c++
If the request is canceled, the `ConnectResponse` is no longer valid. RPCs could show up later, we need to make sure to reject them.
@dom96 for review (can't tag you as reviewer since you're not a repo owner)
> Fix UAF in http-over-capnp connect() implementation.

- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
Tested upstream.
Refactoring and change to fix some fatal crashes.
> Pausable async stream fixes

- c++/Makefile.am
- c++/src/kj/BUILD.bazel
- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
- c++/src/kj/cidr.c++
- c++/src/kj/cidr.h
> Exposes CidrRange as a public API.

- c++/src/capnp/rpc.c++
There is suspicious behavior with tcp accept queues occurring since this was merged. Since this was only intended to deal with logging, let's back it out for now.
This reverts commit bb6c6ec477f6e7a63800e89dec559c63b5090574.
> Revert "capnp rpc: do not report shutdown error after read exception

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
We failed to allocate enough space for the message if it was fragmented because subsequent frames don't set the RSV1 (compression) bit.
> Fix compressed websocket fragment bug

- c++/src/capnp/generated-header-support.h
- c++/src/capnp/schema-test.c++
- c++/src/capnp/test.capnp
> Fix incorrect schema construction when using a list-of-enum as a type parameter.

- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
When EOF was received in the read direction, the write direction would also be treated as disconnected, since they shared the same `disconnected` flag.
I think this flag isn't actually needed at all. It looks like it was intended as an optimization of sorts, to avoid calling OpenSSL if we already knew we were at EOF. But the optimization is wrong, since it doesn't distinguish between read and write directions. So I just removed it.
> Fix kj-tls not working in half-duplex mode.

- c++/Makefile.am
- c++/src/capnp/reconnect-test.c++
- c++/src/capnp/schema-parser-test.c++
- c++/src/capnp/test.capnp
- c++/src/kj/CMakeLists.txt
- c++/src/kj/async-inl.h
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-test.c++
- c++/src/kj/async-unix.h
- c++/src/kj/async.c++
- c++/src/kj/cidr.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
- c++/src/kj/test-test.c++
It's time for some CI-driven-development, oh yeah...
> Fix release tests

- .github/workflows/quick-test.yml
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compiler/node-translator.c++
- c++/src/kj/common.h
- c++/src/kj/string.h
> Fix clang 16 for master branch

- c++/src/kj/async-inl.h
I have a use case for implementing a custom coroutine adapter for a type derived from kj::Promise<T>, and would like to re-use the kj::Promise<T> coroutine implementation. It turns out that, with just a few modifications, the kj::Promise<T> coroutine adapter can be used as a component in a wrapper adapter.
> coroutines: Refactor adapter for reusability

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
_(dependency of cloudflare/workerd#942)_
Hey! 👋 This PR adds a parser for HTTP `Range` headers to KJ, as per https://www.rfc-editor.org/rfc/rfc9110#section-14.1. It may make more sense for this code to be in `workerd`, but it seemed like it could be more generally useful, and the private `skipSpace` and `consumeNumber` functions in `http.c++` were very useful. 🙂
> Add HTTP `Range` header parser

- c++/src/kj/compat/http.c++
This required a slight adjustment to a test, due to a change in the eagerness of a promise chain.
> http: Convert HttpInputStreamImpl to coroutines

- c++/src/kj/async-inl.h
Three little changes:
- `WaitScope` parameters are now banned for coroutines, to prevent them from being simultaneously fibers and coroutines. I implemented this in `coroutine_traits` rather than `kj::_::Coroutine<T>`, because I was worried that if I passed `Args...` down to `kj::_::Coroutine<T, Args...>`, it might make coroutine-related error messages a bit too cluttered. That said, it means that custom coroutine adapters based on `kj::_::Coroutine<T>` can't name `kj::_::Coroutine<T>` themselves, but should always go through `coroutine_traits`, in order to benefit from the parameter type validation.
- ~~I made it so that `co_await blah` is now `[[nodiscard]]`. I could go either way on this. It'll lead to explicit `void` casts in a few places, but it also caught a real bug in …
> Coroutine fiddling: WaitScope parameter ban

- c++/src/capnp/any.h
- c++/src/capnp/blob.h
- c++/src/capnp/common.h
- c++/src/capnp/compiler/capnpc-capnp.c++
- c++/src/capnp/dynamic.h
- c++/src/capnp/layout.h
- c++/src/capnp/list.h
- c++/src/capnp/orphan.h
- c++/src/capnp/rpc.c++
- c++/src/capnp/schema-parser.c++
- c++/src/capnp/schema-parser.h
- c++/src/capnp/schema.h
- c++/src/kj/array.h
- c++/src/kj/common.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.h
- c++/src/kj/filesystem.h
- c++/src/kj/io.h
- c++/src/kj/list.h
- c++/src/kj/memory.h
- c++/src/kj/one-of.h
- c++/src/kj/string.h
- c++/src/kj/table.h
- c++/src/kj/units.h
- c++/src/kj/vector.h
See the corresponding workerd and workerd upstream PRs.
> Improve clang 16+ compat by removing redundant != operators

- c++/src/kj/async-inl.h
- c++/src/kj/async-prelude.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
- c++/src/kj/compat/http.c++
lightweight API to save on heap allocations.
> await on ForkedPromise

- c++/src/capnp/compat/json.c++
Implements some memory management optimizations for JSON parsing. While more extensive changes will be needed for further gains in performance, these changes should be relatively easy to review and perform better across use cases.
On a [simple benchmark](https://github.com/cloudflare/workerd/blob/main/src/workerd/tests/bench-json.c%2B%2B) (likely not very representative, but good enough to show impact), I'm seeing an improvement of ~16% for both encoding and parsing (json encode 3.64 => 3.04 us, json parse 4.91 => 4.12 us).
> Optimize JSON memory management

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
May reduce websocket overhead a bit.
> Websockets: ignore older pings in a few more cases

- c++/src/kj/compat/http.c++
I was hoping to avoid allocation in maybeFinishAfter but ended up converting it into coros.
> convert HttpFixedLengthEntityWriter to coroutines

- c++/src/kj/compat/http.c++
the function is way to long to deal with it.
trying to break it up to make it more manageable.
no logic change, just extracted (copy-paste) 3 functions: onHeaders, onRequest, onConnect
> breaking up HttpServer::Connection::loop

- c++/src/kj/compat/http.c++
rather than branching on writing every chunk, use Maybe<Promise> to wait on previous writes.
> http: lazy output stream queue

- c++/src/kj/async-test.c++
...in configurations where we can't test stack limits with fibers but can test them with pthreads.  Also, exercise the pthread-based code where possible, to reduce the likelihood of future breakage.
Reapplying fcad1296 (PR #1786, reverted in 99115bdd) with changes to make pthread-based testing more tolerant of system-dependent minimum stack sizes; expected to fix tests on ARM, where the minimum stack size is apparently larger than 16k.
> Fix compilation of async stack limit tests

- c++/src/kj/compat/http.c++
there are several more promises in the loop remaining, but the code and its decisions are more readable now imo
> converting http server loop to coroutines

- c++/src/capnp/rpc-twoparty.c++
The code immediately before this alerady places a strong ref to the message into `queuedMessages`. There's no need to attach a second strong reference to the pump promise.
This change has no real impact, just makes the code clearer.
> Minor cleanup in rpc-twoparty.c++.

- c++/src/kj/compat/http.c++
Quick little cleaning while I was in the neighborhood, now that we know that this format has a name and spec.
> Update NetworkHttpClient to point to RFC

- c++/src/kj/async.c++
Clang assumes that a stack frame cannot change threads during execution of the function it is associated with, and therefore decides that it's safe to cache the location to the thread's thread_local space. However, `FiberStack::run()` can change threads during its execution, if fiber stacks are being freelisted and reused across threads. Although we don't access any thread_locals directly in its body, with optimization (especially LTO), some thread_local access could end up inlined and then use the cached address. We can avoid the problem by preventing inlining of anything called by `FiberStack::run()`.
> Fix fibers in the face of Clang's caching of thread-local pointer.

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
If we tryPumpFrom() on a pipe, and then read through the pump, and that read throws an exception, the exception would inadvertently be replaced with "disconnected: operation canceled", due to a continuation timing issue.
> Fix exception-masking bug in async pipe.

- c++/src/kj/exception.c++
We've seen evidence that sometimes the value stored here is 1, which is totally invalid. It's not clear how this is possible, though.
> Validate that `currentException` pointer is not an invalid small value.

- c++/src/kj/async-io-win32.c++
This PR follows from the changes in https://github.com/capnproto/capnproto/commit/f812158982f497e5eb0a8ca5ab286097b3d31367 to implement the same functionality for Windows.
Refs https://github.com/cloudflare/workerd/issues/1408
> Add support for binding to a hostname that resolves to multiple addresses

- c++/src/capnp/compat/http-over-capnp.c++
We see this in production, probably after a WebSocket send() has failed due to network errors.
I tried to produce a test for this, but after a few hours of fiddling, decided I have more important things to do.
I would like to rewrite http-over-capnp entirely...
> Fix spurious `expected !currentlySending` exception.

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Relanding #1828.
This reverts commit 4cb0acf98577d8c29921474fcc8a4eec9111314c.
> Revert "Revert "gracefully handling http 431 error""

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
This reverts commit 6c572fbe3134d75232b9725676cc4a8be5ffcb9d.
> Revert "Make getPreferredExtensions pure virtual func"

- c++/src/capnp/compat/BUILD.bazel
- c++/src/capnp/compat/http-over-capnp-old-test.c++
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/compat/http-over-capnp.h
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/compat/http.c++
I really hated that RequestState class!
> Cleanup and simplify http-over-capnp code.

- c++/src/kj/refcount-test.c++
- c++/src/kj/refcount.h
> kj::Arc<T> smart poiner for atomic reference counted objects

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
This reverts commit 20be408666207623fbfd5002628455c41d15e3b9.
> Revert "Revert "Make getPreferredExtensions pure virtual func""

- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.c++
- c++/src/capnp/capability.h
Previously, refcounting a Server object could allow you to create multiple ClientHooks pointing to the same server, which caused problems:
* `thisCap()` could return the wrong one.
* The usual guarantee that streaming calls are called one-at-a-time wasn't honored since the two ClientHooks were unaware of each other's stream queues.
* Probably other issues?
This change makes it so that when we try to create a Client for a Server that already has Clients, we reuse the existing ClientHook. This seems to solve all the problems, with the caveat that we can't have revocable and non-revocable Clients pointing to the same object (but I don't think anyone does that today).
> Allow Server objects to be refcounted, safely.

- .github/workflows/quick-test.yml
Helps get fuller errors picture
> [nfc] bazel build  with -k

- .github/workflows/quick-test.yml
- c++/.bazelrc
- c++/src/capnp/capability-test.c++
- c++/src/capnp/capability.h
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/encoding-test.c++
- c++/src/capnp/rpc-test.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/schema-loader-test.c++
- c++/src/capnp/schema-test.c++
- c++/src/capnp/serialize-async-test.c++
- c++/src/capnp/serialize-test.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.h
- c++/src/kj/common-test.c++
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/readiness-io-test.c++
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/url-test.c++
- c++/src/kj/exception-test.c++
- c++/src/kj/filesystem-disk-test.c++
- c++/src/kj/filesystem-test.c++
- c++/src/kj/map-test.c++
- c++/src/kj/one-of-test.c++
- c++/src/kj/parse/char-test.c++
- c++/src/kj/string-test.c++
- c++/src/kj/table-test.c++
this matches super-test.sh behavior
> run bazel CI build with -Werror

- c++/src/kj/compat/tls.c++
When a client cert is expired, we will get an SSL error informing of that in the server. But we don't log the details of the client that originated this error.
This PR changes `wrapServer` to catch the exception thrown and attach the `stream.peerIdentity` to the `kj::Exception` description.
> Log peerId in kj::Exception when tls cert is expired

- c++/src/kj/async-inl.h
was caught by async-coroutine-test
> fix PromiseArena memory leak

- .github/workflows/quick-test.yml
- c++/.bazelrc
I plan to add ubsan to the matrix next
> [nfc] asan CI build

- c++/src/kj/async-unix.c++
async-unix.c++ is tested in async-io-test.c++
> async-unix.c++ memcmp == 0 -> ArrayPtr ==

- c++/src/capnp/compat/http-over-capnp.c++
> http-over-capnp: Discard disconnect exceptions on final pump.

- c++/src/capnp/compat/byte-stream-test.c++
- c++/src/capnp/compat/byte-stream.c++
- c++/src/capnp/compat/http-over-capnp-perf-test.c++
- c++/src/capnp/compat/http-over-capnp-test.c++
- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/rpc-twoparty-test.c++
- c++/src/capnp/serialize-async-test.c++
- c++/src/kj/async-coroutine-test.c++
- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io-unix.c++
- c++/src/kj/async-io-win32.c++
- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
- c++/src/kj/compat/brotli-test.c++
- c++/src/kj/compat/brotli.c++
- c++/src/kj/compat/brotli.h
- c++/src/kj/compat/gzip-test.c++
- c++/src/kj/compat/gzip.c++
- c++/src/kj/compat/gzip.h
- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
- c++/src/kj/compat/http.h
- c++/src/kj/compat/readiness-io-test.c++
- c++/src/kj/compat/readiness-io.c++
- c++/src/kj/compat/tls-test.c++
- c++/src/kj/compat/tls.c++
tackling write side before moving on to the read side.
> ArrayPtr-based async write API

- c++/src/kj/memory-test.c++
- c++/src/kj/memory.c++
- c++/src/kj/memory.h
> Add disown() method to kj::Own

- c++/src/kj/array.h
> Fix ArrayBuilder on trivially destructible const T

- c++/src/capnp/compiler/capnpc-c++.c++
- c++/src/capnp/rpc.c++
- c++/src/capnp/rpc.capnp
(Split off from #2111)
Just some random fixes and cleanups before implementing starts in earnest.
> 3PH part 1: Random drive-bys

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
Fixes: #2117 
The previous implementation had 2 issues:
1. Compressed messages of exactly maxsize were incorrectly rejected.
2. Compressed messages above maxsize threw exception outside of receive instead of returning status code 1009. I added a test case to ensure that the new implementation is correct.
> Fix websocket handling of oversized compressed messages.

- c++/src/kj/exception.c++
The code was double-closing the stdout pipe on the parent's side, due to the fact that fdopen() takes ownership of the fd, but the code was also closing the fd itself. Errors from close() were being ignored so the problem wasn't noticed. However, when running in a multi-threaded context, the code would occasionally race with an FD being created in another thread, and end up closing that FD which it didn't own. This manifested as a non-deterministic "bad file descriptor" error in srs-test in the workers runtime.
I rewrote the code to use RAII and to check all errors (catching them with an outer try/catch).
> Fix stringifyStackTraceWithLlvm().

- c++/src/kj/compat/http.c++
Opens doors for improved error handling according to the comment.
> convert pumpWebSocketLoop into coros

- c++/src/kj/compat/http.c++
I am debugging websocket issue and stack trace doesn't make much sense. Maybe after getting rid of lambdas it will become clearer.
Not much but I have to start somewhere.
> convert DelayedCloseWebSocket to coros

- c++/src/kj/compat/http-test.c++
- c++/src/kj/compat/http.c++
We weren't applying the mask correctly. (Server->client doesn't have a mask, so wasn't impacted.)
cc @threepointone
> Fix client->server WebSocket pong encoding.

- c++/src/capnp/rpc.c++
Logging here isn't very useful because it doesn't tell us who holds the reference. But if we break the connection with an exception, hopefully we can see where that exception bubbles up. Or if it doesn't show up anywhere, maybe there's no actual problem.
> When the connection is still referenced during idle shutdown, propagate a better error.

- c++/src/kj/async-inl.h
- c++/src/kj/async-test.c++
- c++/src/kj/async.c++
- c++/src/kj/async.h
Executes multiple promises and returns the first successuful result, canceling the rest.
In case of every promise failing fails with the last (in time) error.
> Promise<T> kj::raceSuccessful(kj::Array<T> promises)

- c++/src/kj/filesystem-disk-win32.c++
> Fix Exception on VeraCrypt Partitions

- c++/src/kj/one-of-test.c++
- c++/src/kj/one-of.h
Using concepts to avoid compiler errors for oneof types that don't implement equality as an alternative to sfinae.
> Attempt to add equality comparison to kj::OneOf

- c++/src/capnp/rpc.c++
In `~RpcClient()`, if the capability was used for streaming, we arrange to wait for all streaming calls to complete in the background, by calling `waitAllAcked()` on the flow controller and then adding the task -- with the flow controller attached -- to the connection's `TaskSet`.
This is problematic, though, if the connection was already disconnected. Normally, we clear the `TaskSet` on disconnect, but this is now adding new tasks into it. Moreover, these tasks can cyclically hold the last remaining references to the connection state itself, since it is no longer connected. When the tasks complete, this can lead to a promise canceling itself, because it drops the last reference to the connection, which destroys the TaskSet.
This change refactors all the `tasks.add(waitAllAcked())` calls …
> Fix source of "Promise callback destroyed itself." in RPC system.

- c++/src/kj/async-inl.h
- c++/src/kj/async.h
- c++/src/kj/mutex-test.c++
Fixes #2208.
Also includes some unrelated drive-by typo fixes.
> Make mutex-test less flaky

- c++/src/kj/async-inl.h
- c++/src/kj/async.c++
This reverts commit 8fc9cb7292f95425ae328d11f2b1f88a6481a076.
This requires landing https://github.com/cloudflare/workerd/pull/3392 first.
> Revert "Revert "Decouple PromiseAwaiter from the Coroutine class""

- c++/src/kj/async-io.c++
- c++/src/kj/async-io.h
All usages downstream have been removed
> remove unused read(void*,size_t)

- .github/workflows/quick-test.yml
unfortunately clang 20 is still not available
> add clang 19 to CI

- c++/src/capnp/BUILD.bazel
- c++/src/capnp/compat/BUILD.bazel
> Support building with `KJ_STD_COMPAT` and `bazel`

- c++/src/capnp/compat/http-over-capnp.c++
- c++/src/capnp/rpc.c++
- c++/src/kj/common.h
- c++/src/kj/memory.h
- c++/src/kj/one-of.h
- c++/src/kj/refcount.h
- c++/src/kj/units.h
Some code cleanup and simplifications, taking advantage of C++20 or trying to simplify some templated code that can lead to symbol bloat in downstream code.
> [nfc] C++20 Code cleanup

- c++/src/kj/memory-test.c++
- c++/src/kj/memory.h
...since calling `.attach()` on a `kj::Refcounted` instance is probably a bug.  Just warning via `[[deprecated]]` for now, but can be cleaned up to a `static_assert()` once existing occurrences are fixed.
> Warn against use of kj::Own<T>::attach() for classes deriving from kj::Refcounted

- c++/src/capnp/rpc.c++
If the connection's shutdown task throws an exception during an idle shutdown for any reason, the connection gets torn down again, causing shutdown() to get called twice. This can cause assertions to be thrown in code expecting shutdown() to only be called once which leads to other failures that can cause aborts.
> Set connection state to Disconnected during idle shutdown

- c++/CMakeLists.txt
https://github.com/capnproto/capnproto/issues/2353
> Guard against multiple cmake inclusions

- c++/Makefile.am
- c++/src/kj/BUILD.bazel
- c++/src/kj/CMakeLists.txt
> KJ: Move cidr to kj-async

- c++/src/kj/async-io-test.c++
- c++/src/kj/async-io.c++
Some of our async streams don't allow for concurrent calls to `tryRead()`.
For example, here is `HttpFixedLengthEntityReader::tryRead`:
```c++
Promise<size_t> tryRead(void* buffer, size_t minBytes, size_t maxBytes) override {
KJ_REQUIRE(clean, "can't read more data after a previous read didn't complete");
clean = false;
size_t alreadyRead = 0;
for (;;) {
if (alreadyDone()) {
clean = true;
co_return alreadyRead;
} else if (chunkSize == 0) {
// ...
} else {
// ...
auto amount = co_await getInner().tryRead(buffer, 1, kj::min(maxBytes, chunkSize));
chunkSize -= amount;
if (amount == 0) {
kj::throwRecoverableException(KJ_EXCEPTION(DISCONNECTED, "premature EOF in HTTP chunk"));
} else if (amount < minBytes) {
// ...
buffer = reinterpret_cast<byte*>(buffer) + amount;
minBytes -= amount;
maxBytes …
```
> Async pipes: Avoid causing a concurrent invocation of tryRead() when calling abortRead()
